### PR TITLE
Revert "Plugin unhandled exception (#3349)"

### PR DESCRIPTION
**Pull request by vncoelho**
It is related to https://github.com/neo-project/neo/issues/3356

It does not solve the issue, but make neo-cli working as in the past.
Thus, normal tests on master branch can be done.

The original PR for Unhandled Exception should had been tested in a basic setup before being merged.

### CODE REVIEW

**Comment by vncoelho** [comment]
After the revert the original PR can be opened again in another branch, then, another PR can be made to fix the problem in such branch.

**Review by AnnaShaleva — COMMENTED** [review]
> It does not solve the issue, but make neo-cli working as in the past.

I just like to make it clear: this PR still doesn't prevent the node from exception described in #3356, right? So could you clarify why did you reverted these changes?

**Comment by vncoelho** [comment]
> > It does not solve the issue, but make neo-cli working as in the past.
> 
> I just like to make it clear: this PR still doesn't prevent the node from exception described in #3356, right? So could you clarify why did you reverted these changes?

With this PR you can run the node at least and it "apparently " work normally.
So, at least other PRs can be tested normally and master can be used. Otherwise any basic consensus scenario is broken with leveldb.

I did not yet test Other scenarios with rockdb or RAM memory. The point is that currently my benchmark test was with leveldb.

Perhaps leveldb currently emit some handled exception and resumes. But with the original PR it crashes the node all the time.

The PR may not be wrong. But it should correct basic errors before being merged. Otherwise we can not even run a node and test smart contracts interaction in a simulated env.

**Comment by Jim8y** [comment]
> > > It does not solve the issue, but make neo-cli working as in the past.
> > 
> > 
> > I just like to make it clear: this PR still doesn't prevent the node from exception described in #3356, right? So could you clarify why did you reverted these changes?
> 
> With this PR you can run the node at least and it "apparently " work normally. So, at least other PRs can be tested normally and master can be used. Otherwise any basic consensus scenario is broken with leveldb.
> 
> I did not yet test Other scenarios with rockdb or RAM memory. The point is that currently my benchmark test was with leveldb.
> 
> Perhaps leveldb currently emit some exception and resumes. But with the original PR it crashes the node all the time.
> 
> The PR being reverted may not be wrong. But it should had corrected basic errors before being merged. Otherwise we can not even run a node and test smart contracts interaction in a simulated env.

Feels like you dont really care about the real cause of the problem.

**Comment by cschuchardt88** [comment]
Im reopening this PR. This break workflow with all downstream applications including `neo-express` and `neo-cli` in `docker`. Breaks `leveldbstore` `rocksdbstore` and `snapshot` caches.

image
image

**Comment by gsmachado** [comment]
See https://github.com/neo-project/neo-express/issues/455

**Comment by Jim8y** [comment]
Just set it to Ignore in the config then.

**Comment by vncoelho** [comment]
> Just set it to Ignore in the config then. 

So mark this as default in another PR
If it works then it is fine to me.

**Comment by cschuchardt88** [comment]
> Just set it to Ignore in the config then.

It doesn't help. `Persist` is `sync` operation, `InvokeCommittingAsync` isn't doing that. This needs to be fixed or reverted 💯.

**Comment by vang1ong7ang** [comment]
@cschuchardt88 yes.

I think the `InvokeCommittedAsync` introduced by #3349 behaves differently.

going to investigate more

I suggest to revert it before the issue is confirmed

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
problem all mine, have identified the issue with alibaba, its the async of triggering plugins.

**Comment by dusmart** [comment]
> going to investigate more

yep. tested locally. Plugins's Committing and Committed handler will executed async, no order is kept.

**Review by cschuchardt88 — APPROVED** [review]

**Pull request merged**
