### PR TITLE
Fix CallFromNativeContract

### LINKED ISSUE #2158: Deployment fails when there's a _deploy method
`ManagementContract.Deploy` checks the contract manifest ABI for a method named `_deploy`. If it exists, it tries to invoke it via `ApplicationEngine.CallFromNativeContract` which in turn calls `ApplicationEngine.CallContractInternal`. `CallContractInternal` throws immediately because the method being invoked starts with an underscore

### PR DESCRIPTION
**Pull request by erikzhang**
Fix #2158

### CODE REVIEW

**Review by devhawk — APPROVED** [review]
Looks good. Are there tests for this?

**Comment by superboyiii** [comment]
image
image
I think it's OK.

**Comment by devhawk** [comment]
@superboyiii but can the management contract call _deploy now?

**Comment by superboyiii** [comment]
> @superboyiii but can the management contract call _deploy now?

@erikzhang @devhawk  call _deploy is OK, but `GetSigners` in Maktransaction always return `WitnessScope.None` which makes authorization failed in contract.

**Review by shargon — APPROVED** [review]

**Comment by devhawk** [comment]
> > @superboyiii but can the management contract call _deploy now?
> 
> @erikzhang @devhawk call _deploy is OK, but `GetSigners` in Maktransaction always return `WitnessScope.None` which makes authorization failed in contract. If make transaction by SDK manually, it can be done. So it's another issue, but if we could solve it here is better.

For the scenario I was running, I don't think this will be an issue. I'll update monorepo and neo-express with this update today (USA time) and see if the get signers call is an issue.  Will reopen or file a new issue if there is a problem

**Pull request merged**
