### PR TITLE
add UnlockEmpty

### PR DESCRIPTION
**Pull request by superboyiii**
For empty wallet creation using.

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
still seems weird to me an empty wallet, I prefer an import command

**Comment by erikzhang** [comment]
```
create wallet xxx.json [privatekeytoimport]
```

**Comment by Liaojinghui** [comment]
> ```
> create wallet xxx.json [privatekeytoimport]
> ```
> 
> We can use this command to create a new wallet with the specified private key.

I vote on this command, an empty wallet is tooooo weird

**Comment by superboyiii** [comment]
> > We can use this command to create a new wallet with the specified private key.
> 
> I vote on this command, an empty wallet is tooooo weird

I'll do this.

**Comment by superboyiii** [comment]
@Liaojinghui @erikzhang I'm using create wallet xxx.json [privatekeytoimport] for initial address import by privateky now. But I think we still need `nep6wallet.UnlockEmpty(password)` when import a privatekey to an empty wallet. We can't control users' behaviour.

**Comment by Liaojinghui** [comment]
> We can't control users' behavior.

Personally, I don't think it is necessary to add that function. If we don't need the empty wallet at all, why would we need to unlock an empty wallet? But, I don't mind having it if you think it is better to keep it.

**Comment by erikzhang** [comment]
I think you can call `Unlock()`. It has the same behavior as `UnlockEmpty()` in the case of an empty wallet.

**Comment by superboyiii** [comment]
> > We can't control users' behavior.
> 
> Thank you very much for your great work. Personally, I don't think it is necessary to add that function. If we don't need the empty wallet at all, why would we need to unlock an empty wallet? But, I don't mind having it if you think it is better to keep it.

We don't need empty wallet and not recommand to create an empty one but someone should be able to open an empty one and do whatever he'd like to, such like import key. Otherwise, empty wallet will not be able to set password.

**Comment by superboyiii** [comment]
> I think you can call `Unlock()`. It has the same behavior as `UnlockEmpty()` in the case of an empty wallet.

`Unlock()` has to verify password from the first address first . That's why I have to create `UnlockEmpty()`.
https://github.com/neo-project/neo/blob/master/src/neo/Wallets/NEP6/NEP6Wallet.cs#L325

**Comment by erikzhang** [comment]
> Unlock() has to verify password from the first address first.

https://github.com/neo-project/neo/blob/a48e79a6b9ffbc51d3725bb7520b89b7b5370bdb/src/neo/Wallets/NEP6/NEP6Wallet.cs#L340

**Comment by superboyiii** [comment]
Unlock() is OK, I will close this.

**Pull request closed without merging**
