### PR TITLE
[Neo Plugin Fix] Fix targes

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

This pr fixes the issue of multiple targes for plugins while there is only one target specified. Making it impossible for dotnet publish to automatically detect the target.

Fixes # https://github.com/neo-project/neo/issues/3344

## Type of change

- [x] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by superboyiii — APPROVED** [review]

**Review by cschuchardt88 — APPROVED** [review]
Whats the problem with the `Targets`?

Reason for so we can do `Standard` or any other target in feature. Unless you have a problem coming up, than I dont see the point.

**Comment by cschuchardt88** [comment]
This was fixed already

image

**Review by vncoelho — APPROVED** [review]

**Comment by cschuchardt88** [comment]
Why you approving something is breaks our environment. everyone's inexperienced or lack of knowledge of dotnet is disappointing when the issue is just that. 

#### This break tests and other things in your our `github` workflows.

**Comment by Jim8y** [comment]
> This was fixed already
> 
> image
> 

i know we can do this, but why we need to do this while there is only one target supported? why use targets instead of target? and why this can cause problem?

**Comment by cschuchardt88** [comment]
Because we build for `dotnet` `Standard` too from `solution` or `*.csproj` that is the reason, or it will fail on other OSS.

**Comment by Jim8y** [comment]
Close as https://github.com/neo-project/neo/pull/3343#issuecomment-2173438881

**Pull request closed without merging**
