### PR TITLE
Fix native contract stack

### LINKED ISSUE #2085: onPayment Context Evaluation Stack not empty on unload
I'm trying to transfer Nep17 GAS to a contract using neo master branch. In preview 3, transfer info was passed via notifications. post-preview 3, there's now a onPayment contract method that gets called. 

If my contract doesn't have an onPayment method, contract invocation throws in CallContractInternal "Method onPayment Does Not Exist In Contract 0xba518ba007f853a2e8b388d4e9968abe62a3a429'". Is this expected? I thought the onPayment method was optional, but now I'm not sure.

Regardless, if I add an onPayment method to my contract, contract invocation now thows in `ContextUnloaded` method. The return type of the context being unloaded is ReturnTypeConvention.EnsureIsEmpty, but the context.EvaluationStack.Count is 1

### PR DESCRIPTION
**Pull request by erikzhang**
Close #2085

### CODE REVIEW

**Review by shargon — APPROVED** [review]
Code looks good, wait for @superboyiii test

**Comment by ProDog** [comment]
I found `Runtime.InvocationCounter` changed to 2 here:
 https://github.com/neo-project/neo-devpack-dotnet/blob/821f834485a30e1254eaef15a2a8f0483ce214ef/templates/Template.NEP17.CSharp/NEP17.Crowdsale.cs#L28

**Comment by superboyiii** [comment]
OnPayment is fine now.

```
        public static void OnPayment(UInt160 from, BigInteger amount)
        {
            if (AssetStorage.GetPaymentStatus())
            {
                Payment(from, amount);
            } else
            {
                throw new Exception("Payment is disable on this contract!");
            }
            
        }
```

```
neo> deploy Template.NEP17.CSharp.nef Template.NEP17.CSharp.manifest.json
Contract hash: 0x5ac8d09e4039571141b7b923e11fac46f0eddd81
Gas: 3.91626

Signed and relayed transaction with hash=0x35a0b1222733ac0b486bb8cccedd8f0f5ca074e2413c773c9faa80d3a6e4f345
neo> invoke 0x5ac8d09e4039571141b7b923e11fac46f0eddd81 enablePayment [] NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp  NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp
Invoking script with: 'EMAMDWVuYWJsZVBheW1lbnQMFIHd7fBGrB/hI7m3QRFXOUCe0MhaQWJ9W1I='
VM State: FAULT
Gas Consumed: 0.0101539
Result Stack: []
Error: Called Contract Does Not Exist: 0x5ac8d09e4039571141b7b923e11fac46f0eddd81
neo> invoke 0x5ac8d09e4039571141b7b923e11fac46f0eddd81 enablePayment [] NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp  NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp
Invoking script with: 'EMAMDWVuYWJsZVBheW1lbnQMFIHd7fBGrB/hI7m3QRFXOUCe0MhaQWJ9W1I='
VM State: HALT
Gas Consumed: 0.0391795
Result Stack: [{"type":"Any"}]
Relay tx(no|yes): y
Signed and relayed transaction with hash=0x3d15ca5c9e599d42fb9f9341c094b668d4dfadf1b7465e6b3aad8288fa5382e6
neo> send gas 0x5ac8d09e4039571141b7b923e11fac46f0eddd81 100
password: *
TXID: 0x0f70b1a8409d81334990276a41ad3d53085cc359679960111d9b206932d7179c
neo> invoke 0x5ac8d09e4039571141b7b923e11fac46f0eddd81 disablePayment [] NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp  NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp
Invoking script with: 'EMAMDmRpc2FibGVQYXltZW50DBSB3e3wRqwf4SO5t0ERVzlAntDIWkFifVtS'
VM State: HALT
Gas Consumed: 0.0281795
Result Stack: [{"type":"Any"}]
Relay tx(no|yes): y
Signed and relayed transaction with hash=0x937bc1f50696cc7c1055ca8cc07fe0d99d8c336de61c54b26eabdcd50aa5697b
neo> send gas 0x5ac8d09e4039571141b7b923e11fac46f0eddd81 100
password: *
Error: An unhandled exception was thrown. Payment is disable on this contract!
```

**Comment by shargon** [comment]
> I found Runtime.InvocationCounter changed to 2 here:

From this PR?

**Comment by ProDog** [comment]
> From this PR?

Yes.

**Comment by roman-khimov** [comment]
> This PR is ok, I just see `Runtime.InvocationCounter` changed to 2, I can reopen an issue to discuss it.sweat_smile

This particular contract can probably be changed to using `onPayment` *instead of* `Mint`, but see #2092 also.

**Review by devhawk — APPROVED** [review]

**Comment by Tommo-L** [comment]
Merge?

**Pull request merged**
