### PR TITLE
Add Star History to README.md

### PR DESCRIPTION
**Pull request by RichardBelsum**

### CODE REVIEW

**Comment by RichardBelsum** [comment]
@dotnet-policy-service agree

**Comment by RichardBelsum** [comment]
> @RichardBelsum please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by Liaojinghui** [comment]
This is good. But we will only process history issues and prs for now. Will try to have it after we finished the monorepo merge process.

**Comment by shargon** [comment]
It looks like we have a unit test that fails arbitrarily...

**Review by Liaojinghui — APPROVED** [review]

**Review by shargon — COMMENTED** [review]
It's possible to choose a different font?

**Comment by Liaojinghui** [comment]
> It's possible to choose a different font?

They are all this weird font. check this one https://github.com/Significant-Gravitas/AutoGPT

**Comment by cschuchardt88** [comment]
Is this even necessary? It's very childish looking.

**Comment by Jim8y** [comment]
> Is this even necessary? It's very childish looking.

Not a thing of necessary, neither a very childish looking. I've seen many `hot` projects to add it showing off how `hot` they are. Wont hurt to have it, wont hurt not having.

**Comment by steven1227** [comment]
Need a more formal graph..

**Review by shargon — CHANGES_REQUESTED** [review]
Agree with @steven1227

**Comment by Jim8y** [comment]
stargazers

https://seladb.github.io/StarTrack-js/#/preload?r=neo-project,neo

**Comment by cschuchardt88** [comment]
@RichardBelsum you going to make change?

**Comment by Jim8y** [comment]
> @RichardBelsum you going to make change?

This is it, no other style, we can close this pr if the font is not liked.

**Comment by cschuchardt88** [comment]
Its looks like a doodle. I'm sure he or we can find another graphy somewhere else.

**Comment by shargon** [comment]
the style is not very professional

**Pull request closed without merging**
