### PR TITLE
Plugins from List to array

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo/issues/1295

### CODE REVIEW

**Comment by shargon** [comment]
Do you think that now is better?

**Comment by lock9** [comment]
But don't we check this list everytime a new block, message or log appears? (if there are plugins installed).
I agree that the arrays are usually empty, but if we have to iterate over it for every Akka message, log or block, it is iterated thousands of times per day, isn't it?

**Comment by erikzhang** [comment]
Let's test it with the normal case that installed 10 plugins. And see how much milliseconds it will save for each block.

**Comment by shargon** [comment]
> Let's test it with the normal case that installed 10 plugins. And see how much milliseconds it will save for each block.

Less than 0.01 ms

**Comment by erikzhang** [comment]
It's not worth optimizing it at the expense of code readability.

**Pull request closed without merging**
