### PR TITLE
[neox-2.x] Snapshot in plugin

### PR DESCRIPTION
**Pull request by KickSeason**
To fix 
* #1683 
* [neo-modules #258](https://github.com/neo-project/neo-modules/issues/258)

We shouldn't use `snapshot` directly in plugin, instead, we can use a snapshot clone.
Currently `IPersistencePlugin` has no choice but commit their changes, intentionally or not. 
We should let plugin to choose `commit` the changes they make.

### CODE REVIEW

**Comment by shargon** [comment]
> We shouldn't use snapshot directly in plugin, instead, we can use a snapshot clone.

Why? the plugin should not write if they don't need it, but maybe the problem it's in the plugin and not here, It's not better to use a different storage for `RpcNep5Tracker ` ?

**Comment by KickSeason** [comment]
> > We shouldn't use snapshot directly in plugin, instead, we can use a snapshot clone.
> 
> Why? the plugin should not write if they don't need it, but maybe the problem it's in the plugin and not here, It's not better to use a different storage for `RpcNep5Tracker ` ?

The plugin can't tell whether it writes storage or not. Take` Nep5Tracker` for example.
`Nep5Tracker` use `ApplicationEngine` with `snapshot` to invoke `balanceOf` of some contracts.
But we don't know what the contract will do in `balanceOf`, some contracts may write storages.
Of course, we can use `snapshot.Clone()` in plugin. But I think it's better in neo.

Two choice in plugin:
**Solution1**. if you want to persist , use `snapshot.Commit()`, if you don't, not use.
**Solution2**. if you want to persist, use `snapshot`, if you don't, use `snapshot.Clone()` and you need to know precisely what you are doing.

Which one do you prefer.

**Comment by vncoelho** [comment]
I prefer Solution1.

**Comment by shargon** [comment]
@KickSeason you've convinced me

**Comment by superboyiii** [comment]
@shargon Seems workflow broke down again. Could you rerun it?

**Pull request merged**
