### PR TITLE
Update vm

### PR DESCRIPTION
**Pull request by shargon**
Required for https://github.com/neo-project/neo-devpack-dotnet/pull/420

### CODE REVIEW

**Review by erikzhang — APPROVED** [review]

**Comment by erikzhang** [comment]
Merge?

**Comment by cloud8little** [comment]
> Merge?

wait for testing.

**Comment by Tommo-L** [comment]
Conflict

**Review by erikzhang — APPROVED** [review]

**Comment by ProDog** [comment]
Tested OK, I have tried various calling contracts, no problem.

**Comment by cloud8little** [comment]
ContractManagement getContract/update/destroy, and Oracle contract all works well.

**Pull request merged**
