### PR TITLE
Regex: try a light weight regex

### PR DESCRIPTION
**Pull request by Liaojinghui**
@shargon How about having a light regex that only support 100 characters?

I think breaking down into those few string methods does not really solve the regex issue.

all 20 test cases complete within 150 ms on my mac with M1 pro.

### CODE REVIEW

**Comment by shargon** [comment]
I don't like it, and also it could be language dependent

**Comment by cschuchardt88** [comment]
@Liaojinghui i really appreciate it, you looking into it.

@shargon would if be better to have service? like we do for oracles, but for regex.

**Comment by Liaojinghui** [comment]
I'll keep this open anyway, just in case we need it someday.

**Comment by Liaojinghui** [comment]
> @Liaojinghui i really appreciate it, you looking into it.
> 

Answring the need of the community is our job. Will figure out a way that makes everyone happy.

**Comment by shargon** [comment]
Closed because https://github.com/neo-project/neo-devpack-dotnet/pull/796

**Pull request closed without merging**
