### PR TITLE
Add `vmState` field in rpc getrawtransaction result

### PR DESCRIPTION
**Pull request by Tommo-L**
close issue [1114](https://github.com/neo-project/neo/issues/1114)

### CODE REVIEW

**Comment by lock9** [comment]
@shargon  it is ok, but shouldn't we have waited 24 hours?

**Comment by vncoelho** [comment]
@lock9, we need a bot for that. It could be even an external one.

**Comment by shargon** [comment]
was approved for 3 core devs, is not enough?

**Comment by lock9** [comment]
@shargon  I think it should be enough, I'm just saying this because the rules say something like this: "Wait for 24 hours so other devs can review it".
Maybe this rule should be applied for complex issues only?

**Comment by vncoelho** [comment]
We need a bot.

**Pull request merged**
