### PR TITLE
Fixes `NeoToken.CalculateBonus()`

### LINKED ISSUE #984: In NEO3, show gas return 100,000,000+
In NEO3, when I send all the neo from the Genesis multisig address, then show gas in the receiver wallet, it will return 100,000,000+, strange...
image

### PR DESCRIPTION
**Pull request by erikzhang**
Fixes #984

### CODE REVIEW

**Comment by erikzhang** [comment]
@nicolegys Please review this patch.

**Review by vncoelho — DISMISSED** [review]

**Comment by vncoelho** [comment]
@erikzhang, this should had been detected in the UTs, yes? I will think about a test for this.

**Comment by nicolegys** [comment]
@erikzhang test pass


image

**Review by nicolegys — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]
@nicolegys, very good to see the automatic claim in your screenshot :)

**Comment by nicolegys** [comment]
@vncoelho hahahaha, I like the automatic claim.

**Pull request merged**
