### PR TITLE
Unit Test for Wallets Module

### PR DESCRIPTION
**Pull request by eryeer**
Hi, here are unit tests for wallets module.
This PR also contains a code fix related to the closed [issue #951](https://github.com/neo-project/neo/issues/951) ,  change in `Neo.Wallets.SQLite.UserWallet`.

### CODE REVIEW

**Comment by shargon** [comment]
On my local machine, `UT_Culture` never ends

**Comment by erikzhang** [comment]
Good fix!

**Comment by eryeer** [comment]
In my local machine, running UT_Culture costs about 11min. The running time is increased due to  some methods in wallets module take a long time to run.

**Comment by shargon** [comment]
Which methods? i want to review it

**Comment by shargon** [comment]
@eryeer Check this https://github.com/eryeer/neoUT/pull/16

If you can change the scrypt values to 0, will be great for the performance

**Comment by eryeer** [comment]
{008ED46C-CF75-4D66-B8B2-8A365C8A4A2D}_20190812161551
Methods that running time larger than 10s  are  ones in red rectangle.

Methods that running time larger than 5s are ones in orange rectangle.

**Comment by eryeer** [comment]
{6144827E-B029-4238-BEC3-F4099A1C86E5}_20190812162831
Methods that running time larger than 10s are ones in red rectangle (TestImportNep2, TestVerifyPassword in UT_NEP6Wallet).
Methods that running time larger than 5s are ones in orange rectangle(TestVerifyPassword in UT_NEP6Account; TestUnlock, TestGetAccounts, TestDecryptKey, TestAddCount in UT_NEP6Wallet).

**Comment by eryeer** [comment]
This time  UT_Culture is shortened to 3min in my local machine.

**Comment by shargon** [comment]
> This time UT_Culture is shortened to 3min in my local machine.

 1 min in my machine now

**Comment by eryeer** [comment]
> Very good tests!
> Do you think we could avoid some things to actually write on disk @eryeer ?

I agree with your opinion and we have tried to avoid writing file to the disk as well. For the NEP6Wallet we have already avoid the writing, but for Sqlite wallet we have no idea to avoid it, because almost every function in `UserWallet` need the disk database file. So we use the `Cleanup` function to remove the wallet file after the test in order to keep the test environment clean. @igormcoelho

**Comment by shargon** [comment]
You can use a memory database with entity framework @eryeer, but it require some changes

**Comment by eryeer** [comment]
That is a way, but I think we‘d better not change the code in neo project for the sake of uint test 😂. @shargon

**Comment by Tommo-L** [comment]
Hi @shargon, could we merge now？😂

**Comment by vncoelho** [comment]
It is great to see that more than contributing to the UT this PR's are also generating promising discussions.

**Pull request merged**
