### PR TITLE
Fix AES256Encrypt Bug in OSX

### PR DESCRIPTION
**Pull request by doubiliu**

### CODE REVIEW

**Review by shargon — DISMISSED** [review]
If it solve the problem and tested in OSX, I think that the code it's ok

**Comment by erikzhang** [comment]
Maybe we should update the workflow to run UTs in OSX.

**Comment by Liaojinghui** [comment]
Test pass on my Mac M1 Pro machine.
Screen Shot 2022-05-19 at 8 16 26 AM

**Review by Liaojinghui — DISMISSED** [review]

**Comment by doubiliu** [comment]
Considering the performance, I will be compatible with the original design because the system native library is faster

**Comment by erikzhang** [comment]
> Maybe we should update the workflow to run UTs in OSX.

Done.

**Review by shargon — DISMISSED** [review]

**Review by erikzhang — CHANGES_REQUESTED** [review]
Wait for native library version.

**Review by Liaojinghui — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
