### PR TITLE
Add regex support for smart contracts

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai Please test the `CpuFee` of the method.

**Comment by roman-khimov** [comment]
.NET has a very particular regex syntax that is hard to reproduce in any other environment. We need some standard for this like POSIX ERE to be interoperable.

**Comment by shargon** [comment]
Agree with @roman-khimov

**Comment by erikzhang** [comment]
I think it's hard to make it interoperable. I will close this pr.

**Pull request closed without merging**
