### PR TITLE
upgrade to .NET Standard 2.0 and .NET Framework 4.7

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by erikzhang** [comment]
@canesin I need you to repair `.travis.yml ` for .NET Standard 2.0

**Comment by canesin** [comment]
sure, this require merging #108 first.

**Comment by erikzhang** [comment]
Now we need at least one approval from core team.

**Comment by AshRolls** [comment]
Using a neo-cli build of this branch I am able to connect to mainnet with no problem. 
However, using that neo-cli build to construct a fresh privatenet and no consensus is found / no new blocks created. 

I will continue to investigate what is causing the consensus to fail with this version, it could be just a problem with my particular build, or perhaps something more fundamental with v2.3.4 to v2.3.4 node communication.

**Comment by AshRolls** [comment]
Privatenet errors were caused by configuration changes needed in the privatenet setup for .net 2.0, so no issue.

Please repackage v2.4.0 with latest changes for nuget as the package there was built & published on November 9th.

**Pull request merged**
