### PR TITLE
Add transaction cache

### LINKED ISSUE #1734: Add cache for recent on-chain transactions to enhance TPS
**Summary or problem description**
Currently when Actor Blockchain receives a transaction it will need to check whether this transaction is already onchain:
https://github.com/neo-project/neo/blob/ae0669639cd806fc8342ae2f75124d58213cdec8/src/neo/Ledger/Blockchain.cs#L357

This piece of code can be severely time-exhausting when height increases & more and more transactions already onchain. This is because levelDB would need to search over the whole DB on disk for the specified transaction.

**Do you have any solution you want to propose?**
A cache for recent transactions' hashes can be added to solve the problem for most cases. Say, we can add a cache to store the hashes of most recent onchain transactions (i.e. transactions within most recent N blocks, where N can be some certain figure like 10 or 20). Thus upon receiving a transaction:
(1) Judge whether ValidUntilBlock - Transaction.MaxValidUntilBlockIncrement >= CurrentSnapshot.Height - N
(2) If satisfied, check whether the the transaction is within MemPool or transaction hash cache. If neither, the transaction is not yet onchain and can be added to MemPool
(3) Otherwise, besides steps in (2), we need to check levelDB whether this transaction is already onchain.

N should be specified so that in most cases new coming transaction suits (2). On the other hand, it should not be too big for the sake of ram-saving. Structure of transaction hash cache should be convinient for updating along with height increasing.

**Neo Version**
- Neo 3

### PR DESCRIPTION
**Pull request by erikzhang**
Close #1734

### CODE REVIEW

**Comment by Qiao-Jin** [comment]
This partially solves the problem (for historry transactions), but for newly created incoming transactions which have not been seen before by the node, a search in the DB is still needed (as it doesn't exist in DB we need to search to the last level)

**Comment by erikzhang** [comment]
`knownhashes` doesn't filter them?

**Comment by Qiao-Jin** [comment]
> `knownhashes` doesn't filter them?

I don't think `knownhashes` can filter such occasion... Furthermore `knownhashes` is not reliable because if node restart the info in `knownhashes` will lose.

**Comment by erikzhang** [comment]
Did you try to use a bloom filter?

**Comment by Qiao-Jin** [comment]
> Did you try to use a bloom filter?

Yes, I have, and the result is [here](https://github.com/neo-project/neo/issues/1734#issuecomment-651035576)

**Comment by erikzhang** [comment]
I think this is exactly the scenario of bloom filter. Maybe there is a problem with the parameter setting?

**Comment by Qiao-Jin** [comment]
> I think this is exactly the scenario of bloom filter. Maybe there is a problem with the parameter setting?

I will try different settings with bloomfilter. But bloomfilter still cannot solve [this](https://github.com/neo-project/neo/pull/1910#issuecomment-688011749) and from current result it seems bloomfilter acts no better than a hashcache.

**Comment by erikzhang** [comment]
We can apply both #1910 and bloom filter.

**Comment by Qiao-Jin** [comment]
> We can apply both #1910 and bloom filter.

Aren't cache and bloomfilter with the same functionality, to judge whether a transaction have seen before..?

**Comment by erikzhang** [comment]
The main purpose of the cache is to quickly obtain existing transactions (GetTransaction). And bloomfilter is used to quickly check non-existent transactions (new transactions). A new transaction cannot be in the cache, so we have to go through the cache and continue to look up in the internal storage. This process must be optimized with bloomfilter.

**Comment by Qiao-Jin** [comment]
> A new transaction cannot be in the cache, so we have to go through the cache and continue to look up in the internal storage

I see. But still a new transaction will give rise to one checking in DB (and to the last level). This can be time consuming when the size of DB grows up. Should we resolve this problem?

**Comment by erikzhang** [comment]
> But still a new transaction will give rise to one checking in DB

We don't need to check db if we have bloomfilter.

**Comment by Qiao-Jin** [comment]
> > But still a new transaction will give rise to one checking in DB
> 
> We don't need to check db if we have bloomfilter.

Got it!

**Comment by shargon** [comment]
The problem with bloom filters is that we can't remove a tx, so in the future becomes useless.

**Comment by erikzhang** [comment]
https://www.eecs.harvard.edu/~michaelm/postscripts/aller2006.pdf

I think this can solve the problem.

**Comment by Qiao-Jin** [comment]
Below is the test result of microseconds used to search a Tx averagely for different `bits_per_key`s (in the char is different X) for levelDB bloom filter (Currently we adopted 15 as the value in [Add BloomFilter to levelDB](https://github.com/neo-project/neo-modules/pull/253)).

image

Also, the time used when no bloom filter used is around 40 microseconds per tx... From the result it seems bloom filter doesn't save time. This is sonehow weird & I'm researching it.

**Pull request closed without merging**
