### PR TITLE
Fixed Props paths for `*.csproj` builds

### LINKED ISSUE #3345: Wrong debug/release path of plugins
**Describe the bug**
An issue from https://github.com/neo-project/neo/pull/3306
I think it doesn't make sense. In currently solution, it generates all dependency dll in /bin but not ./bin
```
Microsoft Windows [Version 10.0.19045.4529]
(c) Microsoft Corporation. All rights reserved.

E:\PR-test\neo-pR#3311\neo\src\Plugins\ApplicationLogs>dotnet publish
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Neo.VM -> E:\bin\Neo.VM\Release\net8.0\Neo.VM.dll
  Neo.Cryptography.BLS12_381 -> E:\bin\Neo.Cryptography.BLS12_381\Release\net8.0\Neo.Cryptography.BLS12_381.dll
  Neo.ConsoleService -> E:\bin\Neo.ConsoleService\Release\net8.0\Neo.ConsoleService.dll
  Neo.Extensions -> E:\bin\Neo.Extensions\Release\net8.0\Neo.Extensions.dll
  Neo.IO -> E:\bin\Neo.IO\Release\net8.0\Neo.IO.dll
  Neo.Json -> E:\bin\Neo.Json\Release\net8.0\Neo.Json.dll
  Neo -> E:\bin\Neo\Release\net8.0\Neo.dll
  Neo.Extensions -> E:\bin\Neo.Extensions\Release\net8.0\Neo.Extensions.dll
  Neo.Cryptography.BLS12_381 -> E:\bin\Neo.Cryptography.BLS12_381\Release\net8.0\Neo.Cryptography.BLS12_381.dll
  Neo.Json -> E:\bin\Neo.Json\Release\net8.0\Neo.Json.dll
  Neo.VM -> E:\bin\Neo.VM\Release\net8.0\Neo.VM.dll
  Neo.IO -> E:\bin\Neo.IO\Release\net8.0\Neo.IO.dll
  Neo -> E:\bin\Neo\Release\net8.0\Neo.dll
  RpcServer -> E:\bin\Neo.Plugins.RpcServer\Release\net8.0\RpcServer.dll
  ApplicationLogs -> E:\bin\Neo.Plugins.ApplicationLogs\Release\net8.0\ApplicationLogs.dll
  ApplicationLogs -> E:\bin\Neo.Plugins.ApplicationLogs\Release\net8.0\publish\

E:\PR-test\neo-pR#3311\neo\src\Plugins\ApplicationLogs>dotnet build
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Neo.Json -> E:\bin\Neo.Json\Debug\net8.0\Neo.Json.dll
  Neo.ConsoleService -> E:\bin\Neo.ConsoleService\Debug\net8.0\Neo.ConsoleService.dll
  Neo.Cryptography.BLS12_381 -> E:\bin\Neo.Cryptography.BLS12_381\Debug\net8.0\Neo.Cryptography.BLS12_381.dll
  Neo.VM -> E:\bin\Neo.VM\Debug\net8.0\Neo.VM.dll
  Neo.Extensions -> E:\bin\Neo.Extensions\Debug\net8.0\Neo.Extensions.dll
  Neo.IO -> E:\bin\Neo.IO\Debug\net8.0\Neo.IO.dll
  Neo -> E:\bin\Neo\Debug\net8.0\Neo.dll
  Neo.Cryptography.BLS12_381 -> E:\bin\Neo.Cryptography.BLS12_381\Debug\net8.0\Neo.Cryptography.BLS12_381.dll
  Neo.Extensions -> E:\bin\Neo.Extensions\Debug\net8.0\Neo.Extensions.dll
  Neo.Json -> E:\bin\Neo.Json\Debug\net8.0\Neo.Json.dll
  Neo.IO -> E:\bin\Neo.IO\Debug\net8.0\Neo.IO.dll
  Neo.VM -> E:\bin\Neo.VM\Debug\net8.0\Neo.VM.dll
  Neo -> E:\bin\Neo\Debug\net8.0\Neo.dll
  RpcServer -> E:\bin\Neo.Plugins.RpcServer\Debug\net8.0\RpcServer.dll
  ApplicationLogs -> E:\bin\Neo.Plugins.ApplicationLogs\Debug\net8.0\ApplicationLogs.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.87
```

**To Reproduce**
1. Got to any plugin folder path
2. Run `dotnet build` or `dotnet publish`

**Expected behavior**
Generate all dependency in ./bin

**Screenshots**
image

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Change Log
- Changed from `$(SolutionDir)` to `../../`
 
_NOTE: for `github` actions and building from `*.csproj` files._

Fixes #3345

## Type of change

- [ ] Optimization (the change is only an optimization)
- [x] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jim8y** [comment]
What is the problem of the original code?

**Comment by cschuchardt88** [comment]
If you don't use a solution file. It will have wrong pathing.

#### Example
```
dotnet pack ./srv/neo/neo.csproj
```

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
> If you don't use a solution file. It will have wrong pathing.
> 
> #### Example (linux)
> ```
> dotnet pack ./srv/neo/neo.csproj
> ```

May be post a few pic of before this pr and after this pr.

**Comment by cschuchardt88** [comment]
Same issue as that PR #3306 fixes

**Comment by shargon** [comment]
But this doesn't work before, I remember

**Review by vncoelho — APPROVED** [review]

**Comment by cschuchardt88** [comment]
> But this doesn't work before, I remember

msbuild reads upwares to the working directory for `*.props`, In solution file or not. 

This PR fixes the problems when using a `*.csproj` file, _NOT_ a solution file (`*.sln`) for `github` workflows and `linux` uses like @vncoelho

**Comment by vncoelho** [comment]
> > But this doesn't work before, I remember
> 
> msbuild reads upwares to the working directory for `*.props`, In solution file or not. 
> 
> This PR fixes the problems when using a `*.csproj` file, _NOT_ a solution file (`*.sln`) for `github` workflows and `linux/vscode` users like @vncoelho 
> 
> Didn't work before, because not enough `../../../../../` or too many last time.

Users like me are the same as devcontainer, everything I have is docker base.

**Review by shargon — APPROVED** [review]
This previously failed, but it works, is good for me

**Comment by superboyiii** [comment]
This works for me.

**Review by superboyiii — APPROVED** [review]

**Pull request merged**
