### PR TITLE
add Enumerator APIs

### PR DESCRIPTION
**Pull request by erikzhang**
The NEP [Non-fungible Token Standard](https://github.com/neo-project/proposals/pull/41) needs Enumerator APIs.

- Neo.Enumerator.Create
- Neo.Enumerator.Next
- Neo.Enumerator.Value
- Neo.Enumerator.Concat
- Neo.Iterator.Keys
- Neo.Iterator.Values

### CODE REVIEW

**Comment by dicarlo2** [comment]
Can we also get an `Enumerator` or (`Enumerator`-like) interface for iterating over the key value pairs of a `Map`? Similar to `ArrayWrapper`.

**Comment by erikzhang** [comment]
> Can we also get an Enumerator or (Enumerator-like) interface for iterating over the key value pairs of a Map? Similar to ArrayWrapper.

Good idea! See #251

**Comment by dicarlo2** [comment]
Awesome, thanks @erikzhang!

**Comment by localhuman** [comment]
This is great!  Does anyone have a test `.avm` I can use as I'm implementing?

**Pull request merged**
