### PR TITLE
Link with neo-vm

### PR DESCRIPTION
**Pull request by shargon**
@lock9 this branch is prepared for use neo, liked to neo-vm project

### CODE REVIEW

**Comment by shargon** [comment]
I am not sure if "development-debug" is the best name, feel free to change it

**Comment by shargon** [comment]
neo-cli will have the same branch with this submodule

**Comment by lock9** [comment]
@shargon  but doesn't make sense for us to work in this repository, instead of the neo-cli? Because this is where we do all the changes, right?

**Comment by shargon** [comment]
maybe we should only have this on neo-cli?

**Comment by vncoelho** [comment]
For the Neo-vm it should be here (as you are proposing) and the neo-cli should get this branch, right?

**Comment by shargon** [comment]
this was my first thought, but require double maintaining, and we will use it only for neo-cli, right?

**Comment by vncoelho** [comment]
The maintaining is the hard part, an eternal open PR would help this...ahueahueaea
On the other hand, we could have this as an external service. I do not know, @shargon.

But I like this idea. We could debug everything and leave something like Travis providing us the report!

But as an external service we could do even more, we could take any branch and merge with our debug and see the result. That would be great!

**Comment by lock9** [comment]
We should only use one, but please, let's make it here, here is where "the problem begins" (where we must update and will break everything else). The person who is updating the code must know what it breaks.
The last changes I saw in neo-cli were very 'easy to fix', it was like using a different constructor,or equivalent. I think it would be easier for the developer to see the whole picture.

**Comment by shargon** [comment]
If we need neo-cli, the branch should be there, not here

**Comment by lock9** [comment]
@shargon  but why? Why can't we have it here? I don't understand 🤔 

#330

**Comment by shargon** [comment]
https://github.com/neo-project/neo/issues/330#issuecomment-513530811 still without answer xD

**Comment by shargon** [comment]
This project is a dependency of neo-cli, so is very weird to have a branch with neo-cli here, i prefer to have this branch in neo-cli, for me, here have no sense...

**Comment by lock9** [comment]
@shargon  Can we close this? I would like to push for the single repository change. I have a list of 10 items WHY we should have a single repository and another 5 items WHY we should NOT have multiple repositories.

**Pull request closed without merging**
