### PR TITLE
Add Copyright and License declaration

### PR DESCRIPTION
**Pull request by Liaojinghui**
#2574

### CODE REVIEW

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/a48e79a6b9ffbc51d3725bb7520b89b7b5370bdb/src/neo/neo.csproj#L4

I think it should be consistent with the information in `.csproj`.

**Comment by Liaojinghui** [comment]
> https://github.com/neo-project/neo/blob/a48e79a6b9ffbc51d3725bb7520b89b7b5370bdb/src/neo/neo.csproj#L4
> 
> 
> 
> I think it should be consistent with the information in `.csproj`.

Understood.

**Review by Qiao-Jin — DISMISSED** [review]

**Review by erikzhang — APPROVED** [review]

**Comment by Liaojinghui** [comment]
@shargon

**Review by shargon — APPROVED** [review]

**Comment by Liaojinghui** [comment]
@superboyiii

**Comment by diskooooo** [comment]
"The neo"? That sounds like really broken English to me...

**Comment by Liaojinghui** [comment]
> "The neo"? That sounds like really broken English to me...

I know, but that is the name of this project, LOL. What else am I supposed to call it? the neo library? is it a library? I am not sure about that.

**Comment by diskooooo** [comment]
> I know, but that is the name of this project, LOL. What else am I supposed to call it? the neo library? is it a library? I am not sure about that.

- `The Neo project` 
- `The NEO project` 

or just `NEO` / `Neo` (without `The`).

**Comment by Liaojinghui** [comment]
> * `The Neo project`
> * `The NEO project`
> 
> or just `NEO` / `Neo` (without `The`).

that is the tricky part, it is not about `the`, but the name of this software is exactly the name of the project. "Neo" or "The neo" makes no difference here.

**Comment by erikzhang** [comment]
Merge?

**Review by superboyiii — APPROVED** [review]

**Pull request merged**
