### PR TITLE
Pay per json deserialized item

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/2533

### CODE REVIEW

**Comment by roman-khimov** [comment]
It hardcodes so many values... I'd rather have some simple length/cost formula (maybe tied to ExecFeeFactor).

**Comment by shargon** [comment]
@roman-khimov First (ExecFeeFactor * Length) and then ExecFeeFactor per entry?

**Comment by roman-khimov** [comment]
Just length without messing with entries. I don't think it's possible to calculate execution overhead precisely here (byte string item can be 10 bytes and can be 1000), so some simple length-based approximation should be enough.

**Comment by shargon** [comment]
> so some simple length-based approximation should be enough.

I am not sure, what do you think @erikzhang ?

**Comment by erikzhang** [comment]
If the cost of syscall is not deterministic, it will be difficult to estimate the fees.

**Pull request closed without merging**
