### PR TITLE
Add Benchmark

### PR DESCRIPTION
**Pull request by Liaojinghui**

### CODE REVIEW

**Comment by nicolegys** [comment]
`this pr`
|            Method |     Mean |    Error |   StdDev |
|------------------ |---------:|---------:|---------:|
| VerifySignatureR1 | 296.2 us |  5.83 us |  8.18 us |
|   VerifySignature | 526.4 us | 10.38 us | 18.46 us |

`rc3`
|            Method |     Mean |   Error |   StdDev |
|------------------ |---------:|--------:|---------:|
| VerifySignatureR1 | 291.1 us | 5.75 us |  8.05 us |
|   VerifySignature | 517.0 us | 9.75 us | 11.98 us |

**Comment by Liaojinghui** [comment]
`this pr`
Intel Core i7-9750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=5.0.301
  [Host]     : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT


|            Method |      Mean |     Error |    StdDev |
|------------------ |----------:|----------:|----------:|
| VerifySignatureR1 | 10.987 ms | 0.0885 ms | 0.0784 ms |
|   VerifySignature |  1.618 ms | 0.0154 ms | 0.0144 ms |

**Review by shargon — CHANGES_REQUESTED** [review]
We can have other repository for benchmarks

**Comment by Liaojinghui** [comment]
> We can have other repository for benchmarks

I create this pr for @nicolegys to run the benchmark. Will close once your OSX pr is merged.

**Pull request closed without merging**
