### PR TITLE
Remove unnecessary default seedlist

### PR DESCRIPTION
**Pull request by satoshichou**
Close https://github.com/neo-project/neo/issues/2772

### CODE REVIEW

**Review by Liaojinghui — APPROVED** [review]

**Review by shargon — CHANGES_REQUESTED** [review]
Why they should be removed?

**Comment by Liaojinghui** [comment]
To be honest, i have no idea what the point of these settings since we already have everything in the `config.json`.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/issues/2772#issuecomment-1162616415

**Comment by superboyiii** [comment]
> [#2772 (comment)](https://github.com/neo-project/neo/issues/2772#issuecomment-1162616415)

But not worked as this behaviour. https://github.com/neo-project/neo/issues/2772#issuecomment-1162706000

**Comment by shargon** [comment]
https://github.com/neo-project/neo/issues/2772#issuecomment-1163554219

**Comment by ixje** [comment]
> But make `seedlist[]` empty is an ordinary behaviour in single consensus privatenet, it shouldn't connect mainnet seeds.

This ☝️ 


> [#2772 (comment)](https://github.com/neo-project/neo/issues/2772#issuecomment-1163554219)

@shargon can you explain what are you're trying to say with this comment? We can read that the behaviour is "by design" according to the dotnet team, but I don't think the current behaviour in NEO core is the intention by the NEO team. At least the way I read Erik's [comment](https://github.com/neo-project/neo/issues/2772#issuecomment-1162616415) is "when the whole `seedlist` key is missing from the config it should take the default seed list, "but" an empty array should give an empty seedlist". Empty seedlist to me means, do not connect to any seed nodes and that's not what it is doing as show in my [screen recording](https://github.com/neo-project/neo/issues/2772#issuecomment-1162706000)

**Comment by satoshichou** [comment]
I think it's necessary to make default seedlist empty, please move on. @erikzhang @shargon

**Comment by shargon** [comment]
What's the sense of remove the seedlist but not the `StandbyCommittee`? I think that we should remove all and ensure that it's configured by the json

**Comment by satoshichou** [comment]
> What's the sense of remove the seedlist but not the `StandbyCommittee`? I think that we should remove all and ensure that it's configured by the json

Actually I don't care about any other parameters because in no sense I need to make it empty on my config.json for privatenet, but seedlist has this sense. When I start a single consensus and a seed node or you call it operation node/debug node/terminal node, I input command, deploy contract on it and it doesn't need to connect any peers. However, it connects to mainnet seeds finally.

**Comment by superboyiii** [comment]
@ixje Maybe we can temporarily set seedlist like `"SeedList": [""]` to avoid this issue.

**Comment by ixje** [comment]
> @ixje Maybe we can temporarily set seedlist like `"SeedList": [""]` to avoid this issue.

That's a workaround similar to using a non-existent ip address, that is not a solution in my opinion. `SeedList: []` meaning do not connect to anything is what I call developer friendly and I thought that's what NEO is trying to be.

**Comment by superboyiii** [comment]
> > @ixje Maybe we can temporarily set seedlist like `"SeedList": [""]` to avoid this issue.
> 
> That's a workaround similar to using a non-existent ip address, that is not a solution in my opinion. `SeedList: []` meaning do not connect to anything is what I call developer friendly and I thought that's what NEO is trying to be.

I think we need to restrict that in Neo.Json to re-deserialize settings for all empty array.

**Comment by roman-khimov** [comment]
Let's handle this one for 3.7.0, either we fix it or not. It's a relatively simple thing, but some people find the default behavior annoying. And we have this PR for a long long time without any decision which is bad.

My take on it is that it should be merged, please vote :+1: or :-1: below and we either merge it (well, it needs a rebase now) or close it next week.

**Comment by AnnaShaleva** [comment]
I agree to merge this PR, but at the same time I agree with https://github.com/neo-project/neo/pull/2773#issuecomment-1173634283. If we're removing the default SeedList (mainnet's one) and suppose that the default configuration can be used for any network (testnet, privnet), then other mainnet-related fields also should be removed (mainnet standby committee, magic, etc.). Otherwise we have kind of "mixed" configuration that includes both mainnet-related things and truly "default" things.

But it's a nitpicking and not critical.

**Comment by ixje** [comment]
Are we really asking somebody to update his/her PR after almost 1.5 years? Looking at the persons profile shows no GitHub activity since creating this PR. I say just merge this and deal with Anna's suggestions in a new PR.

**Comment by shargon** [comment]
Closed by inactivity and moved to https://github.com/neo-project/neo/pull/2980

**Comment by satoshichou** [comment]
I'm always there, the shadow 👻 . Really good to see this moving forward. Neo is awesome! @roman-khimov @ixje @shargon @vncoelho

**Comment by RichardBelsum** [comment]
laugh one's ass off

**Comment by satoshichou** [comment]
> laugh one's ass off

You never know when I will be back. May the force be with you. 😏

**Comment by Liaojinghui** [comment]
> I'm always there, the shadow 👻 . Really good to see this moving forward. Neo is awesome! @roman-khimov @ixje @shargon @vncoelho 

@satoshichou please check https://github.com/neo-project/neo/pull/2980

**Comment by satoshichou** [comment]
> > I'm always there, the shadow 👻 . Really good to see this moving forward. Neo is awesome! @roman-khimov @ixje @shargon @vncoelho
> 
> @satoshichou please check #2980

Yeah, already saw this. Good moving.

**Comment by shargon** [comment]
@satoshichou feel free to open again the pull request!

**Comment by satoshichou** [comment]
> @satoshichou feel free to open again the pull request!

Yours is enough!

**Pull request closed without merging**
