### PR TITLE
Remove Travis and use Github Actions

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by erikzhang** [comment]
Wait for #1178

**Comment by erikzhang** [comment]
Wait for #1269

**Comment by erikzhang** [comment]
Ready to merge.

**Comment by vncoelho** [comment]
@erikzhang, will the reports also be send to the PR's or leave it for when we click on the Details?

image

**Comment by erikzhang** [comment]
@vncoelho It won't be sent as a comment, but will be sent as a check.

image

If you need to see the details, you have to click the link.

**Comment by vncoelho** [comment]
it looks good to me, just to know if there was something else to be done.
In fact, that comments were not also very easy to see.

**Pull request merged**
