### PR TITLE
Neo-node Migration

### PR DESCRIPTION
**Pull request by lock9**
Migrating neo-node project into the Neo repository.

Observations:
- The project names weren't following naming conventions.
  - neo-cli renamed to Neo.CLI 
  - neo-gui renamed to Neo.GUI
  - Executable names remain the same
- .editorconfig from neo-node was discarded in favor of the current one (more complete)
- Docker file moved into the Neo.CLI project folder
  - It is used to build neo-cli
  - Passing framework parameter to the dotnet build command
  - The docker build was updated to match the new structure, but the image itself is broken 
    - Tested on OSX. Maybe it's working on other platforms.
- Neo-node doesn't have a Directory.Build. props file.
- Neo-cli has a changelog file. This file wasn't migrated. Should it?
- ConsoleService has its own version (currently 1.2.0)
- The current `neo` workflow wasn't updated to distribute neo-cli
- Neo-node has a codeql workflow that is not present on Neo and wasn't migrated.
- There is a workflow that builds docker images but doesn't test it.
  - I didn't migrate this workflow since the Docker image doesn't seem to work, and running Docker may be resource-consuming.
- I didn't test Neo GUI

Question:
Should I update the workflow to generate and test neo-cli?

### CODE REVIEW

**Comment by chenzhitong** [comment]
Should we remove Neo-GUI?

**Comment by RichardBelsum** [comment]
Does anyone use the neo-gui project, Should we remove it?

**Comment by Liaojinghui** [comment]
@lock9 

# Directory Comparison Script

This script is designed to compare C# files between two directories (referred to as the original and merge directories), including their subdirectories. It ensures that not only the contents of the C# files are identical, but also that the directory structures and the number of files are the same.

## Features

- **Recursive Comparison**: The script recursively searches through all subdirectories in both the original and merge directories for C# files.
- **Content Verification**: It compares each C# file in the original directory with its counterpart in the merge directory to ensure they are identical in content.
- **Structure Verification**: The script checks that each C# file in the original directory has a corresponding file at the same relative path in the merge directory.
- **Difference Reporting**: If any differences in content or structure are found, the script outputs the details of these differences.

## Usage

1. **Provide Directories**: Run the script with two arguments - the paths to the original and merge directories.
2. **Execute the Script**: Save the script as `compare_directories.sh`, make it executable with `chmod +x compare_directories.sh`, and then run it as `./compare_directories.sh /path/to/original/dir /path/to/merge/dir`.

```shell
#!/bin/bash

# Check if two arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <original_directory> <merge_directory>"
    exit 1
fi

original_dir=$1
merge_dir=$2

# Function to compare two directories
compare_directories() {
    local dir1=$1
    local dir2=$2

    # Get relative paths of all C# files in the first directory
    local files_dir1=($(cd "$dir1" && find . -type f -name "*.cs"))
    
    # Loop through each file in the first directory
    for file1 in "${files_dir1[@]}"; do
        local file2="${dir2}/${file1#./}"

        if [ ! -f "$file2" ]; then
            echo "File missing in $dir2: $file1"
            continue
        fi

        # Compare the contents of the two files
        if ! cmp -s "${dir1}/${file1}" "$file2"; then
            echo "Difference found in file: $file1"
            echo "----"
            diff "${dir1}/${file1}" "$file2"
            echo "----"
        fi
    done
}

# Compare original to merge
compare_directories "$original_dir" "$merge_dir"

# Compare merge to original (to catch any extra files in merge)
compare_directories "$merge_dir" "$original_dir"

```

**Comment by Liaojinghui** [comment]
name: Compare Codebases

on:
  pull_request:
    branches: [ master ]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Checkout Target Repository
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/neo-project/neo-node.git'
        ref: 'https://github.com/neo-project/neo-node/commit/da786195cfb6d70236bb37611c37d7016bbc3aae'
        path: 'neo-cli'

    - name: Compare Directories
      run: |
        chmod +x ./compare_directories.sh
        ./compare_directories.sh ./ ${{ github.workspace }}/Neo.CLI > difference.log || true

    - name: Upload differences if any
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: differences
        path: difference.log

**Comment by roman-khimov** [comment]
> this script

I think I trust `diff -puraN` a bit more.

**Comment by Liaojinghui** [comment]
> > this script
> 
> 
> 
> I think I trust `diff -puraN` a bit more.

As long as it can convince you to move monorepo faster.

**Review by shargon — COMMENTED** [review]
I think that we should wait for the pending PR, at least:

- https://github.com/neo-project/neo-node/pull/908
- https://github.com/neo-project/neo-node/pull/905

**Comment by shargon** [comment]
@lock9 could you update the code?

**Review by shargon — COMMENTED** [review]
~Dockerfile was removed?~ (found)

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
@lock9 we need to update the main README

**Comment by lock9** [comment]
```

coverage/coveralls — Coverage remained the same at 66.505%
```
What happened? I just updated the readme...?

**Review by shargon — APPROVED** [review]

**Pull request merged**
