### PR TITLE
CryptoLib: Adding keccak256

### PR DESCRIPTION
**Pull request by Liaojinghui**
Adding Keccak256 hash algorithm for the ease of processing ethereum-like message.

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Just wondering, who comes up with the fees?

**Comment by Liaojinghui** [comment]
> Just wondering, who comes up with the fees?

Luckily we have @superboyiii

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
@Liaojinghui Why this was closed?

**Comment by Liaojinghui** [comment]
> @Liaojinghui Why this was closed?

I polluted my local master branch, mistakenly deleted all branches while i was trying to remove the extra commit in my local master branch.

**Pull request closed without merging**
