### PR TITLE
Add comments for CheckItemForNotification

### LINKED ISSUE #1669: Can we support Runtime.Notify (Enumerator)?
False returned while use `Runtime.Notify(InteropInterface)`, so contract's invoke result is `FAULT`.

Can we support `Runtime.Notify (InteropInterface)` like `Runtime.Notify (Map)`?

### PR DESCRIPTION
**Pull request by Tommo-L**
Closes #1669 

1. Add comments

### CODE REVIEW

**Comment by erikzhang** [comment]
Why do you think it is an optimization?

**Comment by Tommo-L** [comment]
`While(true)` isn't friendly for static analysis tools.

**Comment by erikzhang** [comment]
But if `state` is not an `array` or `map`, then we don't need to push or pop anything. It makes the code worse.

**Comment by Tommo-L** [comment]
For me, it's acceptable and readable.

**Comment by shargon** [comment]
> But if state is not an array or map, then we don't need to push or pop anything. It makes the code worse.

@erikzhang it's right, it's more readable, but it could be slower.

**Pull request closed without merging**
