### PR TITLE
Adding last update Block Height to Storage Item

### PR DESCRIPTION
**Pull request by igormcoelho**
This feature intends to inform when each key/value was last updated. It's important for much faster sequential storage dumps.

### CODE REVIEW

**Comment by erikzhang** [comment]
When will it be used?

**Comment by vncoelho** [comment]
```cs
                case "blockstorage":
                    DumpInBlock(args.Length >= 3
                        ? Blockchain.Singleton.Store.GetStorages().Find(UInt160.Parse(args[2]).ToArray())
                        : Blockchain.Singleton.Store.GetStorages().Find());
                    return true;

        private static void DumpInBlock<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>> states)
            where TKey : ISerializable
            where TValue : ISerializable
        {
            string path = $"dump-block-{Blockchain.Singleton.Height.ToString()}.json";
            //JArray array = new JArray(states.Where(p => toStorageItem(p).Height == Blockchain.Singleton.Height).Select(p =>

            IEnumerable<JObject> items = states.Select(p =>
            {
                JObject state = new JObject();
                state["key"] = p.Key.ToArray().ToHexString();
                byte[] src = p.Value.ToArray();
                StorageItem si = new StorageItem();
                using (MemoryStream stream = new MemoryStream(src)) {
                  using (BinaryReader reader = new BinaryReader(stream)) {
                    si.Deserialize(reader);
                  }
                }
                uint h = si.Height;
                if(h != Blockchain.Singleton.Height)
                  return null;
                state["value"] = p.Value.ToArray().ToHexString();
                return state;
            });
            IEnumerable<JObject> itemsFilter = items.Where(p => p != null);
            JArray array = new JArray(itemsFilter);
            File.WriteAllText(path, array.ToString());
            Console.WriteLine($"DumpInBlock States have been dumped into file {path}");
}
```

**Comment by vncoelho** [comment]
I do not believe, Igor.
You did tests....and passed. aheuahuea 

image

**Comment by igormcoelho** [comment]
> You did tests....and passed. aheuahuea
Sometimes things work xD

**Comment by vncoelho** [comment]
https://github.com/NeoResearch/neo-storage-audit

Currently around Blocks 1.5M

**Comment by igormcoelho** [comment]
> https://github.com/NeoResearch/neo-storage-audit

This is our usage @erikzhang @PeterLinX . We are now able to publish all changes made to Neo Storage in its past history. Using this, it's straightforward to reproduce notifications in any past moment too ;)

**Comment by igormcoelho** [comment]
@erikzhang please consider adding this feature, let me explain why:
(1) it will make auditing specific storage keys a very easy task, and by knowing the last update time, it will be possible to easily go back and replay transactions on that specific block (through proposed RPC call getblockstorage).
(2) it will make it possible to implement future features such as volatile storages (that expire automatically after a given number of blocks), which could be useful in many scenarios such as utxo implementation over storage, and on scichain / other dapps, that need temporary storage only.

**Comment by vncoelho** [comment]
@igormcoelho,

Now that we are almost done in getting the storage directing from cache, let's consider other applications of this PR.

@erikzhang,
I believe it is important for exchanges to query storage, that is why we also included this PR https://github.com/neo-project/neo/pull/424:

**Comment by erikzhang** [comment]
This pr will cause the block to be resynchronized after the update. So I won't merge this pr until there are other more important features that need to resynchronize the block.

**Comment by vncoelho** [comment]
You are right, @erikzhang. I agree with you.
It is minor point for a slightly big impact.
Let's keep it aside for now.

**Comment by igormcoelho** [comment]
Don't worry @erikzhang , we are also evolving towards solving StateRoot issue https://github.com/neo-project/neo/issues/385. @rodoufu implemented and is already testing a MerklePatricia tree for Neo, and we could use it in conjunction with this feature very soon (https://github.com/rodoufu/neohelp).

**Comment by rodoufu** [comment]
Done, waiting for the pull request review at  https://github.com/neo-project/neo/pull/528

**Comment by igormcoelho** [comment]
We can change this proposal to include Storage Expiration Time (for Volatile Storage): https://github.com/neo-project/neo/issues/332

**Comment by vncoelho** [comment]
@igormcoelho, do you still believe that the inclusion of last height is important, even with the merkle trie or other form of representing storage?

I believe it is because it will be a quite direct manner to access this information with a minor overhead.

**Comment by igormcoelho** [comment]
Brother, the only application I see now for this is Volatile Storages: #332 So we can mark when each key would expire automatically. However, we don't have much feedback from community regarding this... I think it's a nice feature. Let's keep it open.

**Comment by vncoelho** [comment]
We believe that this issue and feature can now be handled in a different manner and covering other aspects.

**Pull request closed without merging**
