### PR TITLE
IDisposable on levelDB classes

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by erikzhang** [comment]
I don't think this is a good idea. We use destructors to free resources.

**Comment by shargon** [comment]
But with `using`, we have more control of when it will be destroyed

**Comment by erikzhang** [comment]
Why we use C#? Because we have GC. 😂

The `Handler`s are just some pointers. They only take up very little resources.

**Comment by shargon** [comment]
We should follow this https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by erikzhang** [comment]
The recommended pattern is:

```c#
using System;

class DerivedClass : BaseClass
{
   // Flag: Has Dispose already been called?
   bool disposed = false;
   
   // Protected implementation of Dispose pattern.
   protected override void Dispose(bool disposing)
   {
      if (disposed)
         return; 
      
      if (disposing) {
         // Free any other managed objects here.
         //
      }
      
      // Free any unmanaged objects here.
      //
      disposed = true;
      
      // Call the base class implementation.
      base.Dispose(disposing);
   }

   ~DerivedClass()
   {
      Dispose(false);
   }
}
```

But it's too complicated. So we just use the destructor.

**Pull request closed without merging**
