### PR TITLE
Check null in native contracts

### LINKED ISSUE #2609: native fungible:  NEP17 standard mismatch
**Describe the bug**
Native fungible tokens implementation allows to invoke `Transfer` method with null `from` and `to` arguments (see https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Native/FungibleToken.cs#L153). However, the NEP17 standard requires `from` and `to` to be 20-bytes addresses (see https://github.com/neo-project/proposals/blob/master/nep-17.mediawiki#transfer):
```
The parameters from and to MUST be 20-byte addresses. If not, this method SHOULD throw an exception. 
```
That's the reason for states diff between C# and NeoGo nodes at N3 testnet, block 289067 (NeoGo node disallow null `from` and `to` arguments).

**To Reproduce**
See the application log of C# and NeoGo nodes for transaction `0x3d7d6135a033b594cf700c3e86818bf8bfac9884b42319c13b39997cee01cf38`:

C#'s:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getapplicationlog", "params": ["0x3d7d6135a033b594cf700c3e86818bf8bfac9884b42319c13b39997cee01cf38"] }' seed2t4.neo.org:20332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1111    0   969  100   142    521     76  0:00:01  0:00:01 --:--:--   597
{
   "jsonrpc" : "2.0",
   "result" : {
      "executions" : [
         {
            "trigger" : "Application",
            "vmstate" : "HALT",
            "exception" : null,
            "stack" : [
               {
                  "type" : "Any"
               }
            ],
            "notifications" : [
               {
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "value" : "LE7t5cxY0v4gzrFwyp1EjV1A2bo=",
                           "type" : "ByteString"
                        },
                        {
                           "value" : "1",
                           "type" : "Integer"
                        }
                     ]
                  },
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf"
               },
               {
                  "eventname" : "Transfer",
                  "state" : {
                     "value" : [
                        {
                           "value" : "LE7t5cxY0v4gzrFwyp1EjV1A2bo=",
                           "type" : "ByteString"
                        },
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "Integer",
                           "value" : "0"
                        }
                     ],
                     "type" : "Array"
                  },
                  "contract" : "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5"
               },
               {
                  "state" : {
                     "value" : [
                        {
                           "value" : "LE7t5cxY0v4gzrFwyp1EjV1A2bo=",
                           "type" : "ByteString"
                        },
                        {
                           "value" : "KF5rGkaMsHJCgx1V4mpxbD6d2Bo=",
                           "type" : "ByteString"
                        },
                        {
                           "value" : "1",
                           "type" : "Integer"
                        }
                     ],
                     "type" : "Array"
                  },
                  "contract" : "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
                  "eventname" : "Transfer"
               }
            ],
            "gasconsumed" : "12375770"
         }
      ],
      "txid" : "0x3d7d6135a033b594cf700c3e86818bf8bfac9884b42319c13b39997cee01cf38"
   },
   "id" : 1
}
```

NeoGo's:
```
neospcc@neospcc-ThinkPad-T590:~/Documents/GitProjects/nspcc-dev/neo-go$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getapplicationlog", "params": ["0x3d7d6135a033b594cf700c3e86818bf8bfac9884b42319c13b39997cee01cf38"] }' rpc01.testnet.n3.nspcc.ru:21332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   718  100   576  100   142   1750    431 --:--:-- --:--:-- --:--:--  2175
{
   "jsonrpc" : "2.0",
   "result" : {
      "txid" : "0x3d7d6135a033b594cf700c3e86818bf8bfac9884b42319c13b39997cee01cf38",
      "executions" : [
         {
            "vmstate" : "FAULT",
            "exception" : "at instruction 92 (SYSCALL): failed native call: at instruction 92 (SYSCALL): invalid conversion: Null/ByteString",
            "gasconsumed" : "12375710",
            "stack" : [],
            "trigger" : "Application",
            "notifications" : [
               {
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "LE7t5cxY0v4gzrFwyp1EjV1A2bo="
                        },
                        {
                           "type" : "Integer",
                           "value" : "1"
                        }
                     ]
                  },
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf"
               }
            ]
         }
      ]
   },
   "id" : 1
}
```

The second transfer has `Null` as `to` address (see the second notification from the applog), and this transfer is handled by C# node but faulted by NeoGo node (as the standard requires).

**Expected behavior**
Native fungible tokens implementation must follow the NEP17 standard.

**Platform:**
 - Version: Neo v3.0.2

### PR DESCRIPTION
**Pull request by erikzhang**
Fix #2609

### CODE REVIEW

**Comment by Liaojinghui** [comment]
shall we also check all other similar APIs?

**Review by Liaojinghui — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]
From null was really bad...aehauhea

**Review by shargon — DISMISSED** [review]

**Comment by AnnaShaleva** [comment]
> shall we also check all other similar APIs?

It would be nice.

**Review by steven1227 — APPROVED** [review]

**Comment by erikzhang** [comment]
> shall we also check all other similar APIs?

Done.

**Review by shargon — APPROVED** [review]

**Review by superboyiii — APPROVED** [review]

**Review by Liaojinghui — APPROVED** [review]

**Pull request merged**
