### PR TITLE
Allowing new compatible Dotnet versions to restore, build and publish

### PR DESCRIPTION
**Pull request by vncoelho**
close https://github.com/neo-project/neo/issues/3188

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Review by AnnaShaleva — APPROVED** [review]
I had this change locally to build with fresh dotnet :D

**Comment by cschuchardt88** [comment]
This shouldn't of been changed. This has nothing to do with #3188. Your lucky they added support for `8.0.204` in Visual Studio or else this wouldn't of worked. You didn't event update `github` workflows.

I don't know why I didn't see this 👀 

I nominate myself to be project/repo maintenance person; since I'm always cleaning up.... 🦺

**Comment by vncoelho** [comment]
> This shouldn't of been changed. This has nothing to do with #3188. Your lucky they added support for `8.0.204` in Visual Studio or else this wouldn't of worked. You didn't event update `github` workflows.
> 
> I don't know why I didn't see this 👀 
> 
> I nominate myself to be project/repo maintenance person; since I'm always cleaning up.... 🦺 

No Cris, this was causing problems.

Next time, please be more careful and keep compatibility for all devs. 

Read the PR discussions. This was forcing devs to change this config locally.

**Comment by cschuchardt88** [comment]
You know the reason it was like that before? Lets not forget #3183

**Pull request merged**
