### PR TITLE
Oracle: Version as flag

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by Tommo-L** [comment]
If we want to adjust the transaction structure in future, how do we use `transaction.version`?

Will it be better to rename `TransactionVersion` to `TransactionTag` , `TransactionType` or `TransactionFlag`?

**Comment by erikzhang** [comment]
The original idea was to reuse the version as a flag. If you must keep it, then I would rather use TransactionAttribute.

**Comment by Tommo-L** [comment]
> If you must keep it, then I would rather use TransactionAttribute.

I think it's not too bad, if we use TransactionAttribute, maybe only one TransactionAttribute is enough.

**Comment by shargon** [comment]
Then, shall I move it to `OracleAttribute`?

**Comment by shargon** [comment]
Please review https://github.com/neo-project/neo/pull/1618 if it's better. I also prefer it as an attribute.

**Comment by shargon** [comment]
If we decide that it's better with attributes, we can close this

**Comment by Tommo-L** [comment]
> If we decide that it's better with attributes, we can close this

It's ok for me to close this pr.

**Pull request closed without merging**
