### PR TITLE
`[Tests]` Add blame logging - `main.yml`

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Description
Added blame logging for `dotnet test`. To see what is crashing `Windows` `github` test action; what keeps making it exit process, sometimes.

image

# Change Log
 - Added `--blame-hang --blame-crash` to `dotnet test` command in  `main.yml`

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cschuchardt88** [comment]
> How you will recover the xml files?

No, But it will display error in the console window in the `github` action step.

**Comment by shargon** [comment]
> > How you will recover the xml files?
> 
> No, But it will display error in the console window in the `github` action step.

Are you sure? I never used this command, but the documentation only mention that it produce a file dump.

**Comment by cschuchardt88** [comment]
> > > How you will recover the xml files?
> > 
> > 
> > No, But it will display error in the console window in the `github` action step.
> 
> Are you sure? I never used this command, but the documentation only mention that it produce a file dump.

Yes I'm sure.

### Message Outputs
#### Successful
image

#### Failure
image

**Review by shargon — APPROVED** [review]

**Comment by Jim8y** [comment]
nice, we need this

**Review by Jim8y — APPROVED** [review]

**Pull request merged**
