### PR TITLE
Revert "Refuel (#2444)"

### PR DESCRIPTION
**Pull request by erikzhang**
This reverts commit 4d45a796e9bb0e3427ddee56a626b4b8f27f3e16.

### CODE REVIEW

**Comment by shargon** [comment]
Check balance before refuel?

**Comment by roman-khimov** [comment]
I don't see how it could be fixed, so we need to drop it.

At the same time it's an exported method, it's declared in the manifest, saved in the ContractManagement, and we have stateroot computed including it. Therefore to properly remove it now we need to update GAS contract using `NativeUpdateHistory`.

**Comment by shargon** [comment]
@roman-khimov Limit to 1 of gas? Or a small value?

**Comment by roman-khimov** [comment]
> @roman-khimov Limit to 1 of gas? Or a small value?

`ABORT`

**Comment by shargon** [comment]
Or if you used refuel with an address, you can't make a transfer with this address during the same invocation.

**Comment by superboyiii** [comment]
> I don't see how it could be fixed, so we need to drop it.
> 
> At the same time it's an exported method, it's declared in the manifest, saved in the ContractManagement, and we have stateroot computed including it. Therefore to properly remove it now we need to update GAS contract using `NativeUpdateHistory`.

How about resync?

**Comment by superboyiii** [comment]
> Or if you used refuel with an address, you can't make a transfer with this address during the same invocation.

It's better to revert at this time and find a better way later.

**Comment by roman-khimov** [comment]
> How about resync?

How about Poly?

**Comment by superboyiii** [comment]
> > How about resync?
> 
> How about Poly?

It only verified the latest state root sent by relayer.

**Comment by shargon** [comment]
> It's better to revert at this time and find a better way later.

I think that `ABORT` it's easier, and we can try to find a solution later

**Comment by ZhangTao1596** [comment]
> > @roman-khimov Limit to 1 of gas? Or a small value?
> 
> `ABORT`

May I ask what `ABORT` mean ? delete the method ?

**Comment by shargon** [comment]
> May I ask what ABORT means ? delete the method ?

throw and exception during the calling

**Comment by superboyiii** [comment]
> > May I ask what ABORT means ? delete the method ?
> 
> throw an exception during the calling

Then we have to tell user invoking `Refuel` retrun `ABORT`, it's odd. Delete it makes more sense.

**Comment by erikzhang** [comment]
Merge?

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
