### PR TITLE
Prevent abi changes without update the script

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo/pull/1572#issuecomment-615071810

### CODE REVIEW

**Comment by erikzhang** [comment]
You can secretly modify anything without changing the scripthash, just by using dynamic calls. This has been discussed in #1481.

**Comment by shargon** [comment]
Better to have only one way, and not two 👼

**Comment by erikzhang** [comment]
If someone updates the ABI without updating the script, there may be a mistake in the original ABI and he wants to fix it. We shouldn't stop him.

**Comment by shargon** [comment]
Then we should emit a notification when a abi or a contract it's created/updated/destroyed

**Pull request closed without merging**
