### PR TITLE
Avoid processing own hashes (3x)

### PR DESCRIPTION
**Pull request by vncoelho**
```cs
            UInt256[] hashes = payload.Hashes.Where(p => knownHashes.Add(p)).ToArray();
            bool sentByMe = payload.Hashes.Any(p => sentHashes.HasItem(p));
            Console.WriteLine($"OnInvMessageReceived(PH): hashes={hashes.Length} sentByMe={sentByMe}");
            if (hashes.Length == 0 || sentByMe) return;
```

```cs
OnInventoryReceived - Task Completed will be called (PH): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnInvMessageReceived (PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-1704695485-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
      printingHashesFiltered(PH)-1704695485-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
TM-IHP: Consensus I AM...
OnNewTasks(TM)-BGN-1520415900-1565296030
OnNewTasks(TM)-BKS-1520415900-1565296030:
       NewTaskHashesOnTM(TM)-1520415900-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnNewTasks(TM)-AKS-1520415900-1565296030-count: 0
OnNewTasks(TM)-AGT-1520415900-1565296030-count: 0
OnInvMessageReceived (PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-1891482569-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
      printingHashesFiltered(PH)-1891482569-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
TM-IHP: Consensus I AM...
OnNewTasks(TM)-BGN-594383941-1565296030
OnNewTasks(TM)-BKS-594383941-1565296030:
       NewTaskHashesOnTM(TM)-594383941-1565296030: 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnNewTasks(TM)-AKS-594383941-1565296030-count: 0
OnNewTasks(TM)-AGT-594383941-1565296030-count: 0
OnInventoryReceived - Local Node Relay will be called (PH): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnRelay(LN): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnRelay(RN): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnRelay(RN): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnRelay(RN): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnRelay(RN): 0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
[20:27:10.958] OnConsensusPayload hash=0xfc2c8ec7e1b21bec1fd0f60797d60a725257d34bcf8d3104554ebce13d160271
OnInvMessageReceived (PH): hashes=1 sentByMe=True
OnInvMessageReceived (PH): hashes=1 sentByMe=False
```

### CODE REVIEW

**Comment by vncoelho** [comment]
@erikzhang and @shargon, should this go to master2x? I think so, it is a bug fix in my opinion.

**Comment by vncoelho** [comment]
@shargon, merged your suggestions here as well.

**Comment by shargon** [comment]
The code looks well, i will test the behavior around this day

**Comment by shargon** [comment]
Good catch!

**Pull request merged**
