### PR TITLE
dotnet format

### PR DESCRIPTION
**Pull request by igormcoelho**
cosmetic change, related to base formatting issue: https://github.com/neo-project/neo/issues/982

### CODE REVIEW

**Comment by vncoelho** [comment]
@erikzhang, I think that we need a guidelines for formatting, this is causing some "critical" problems to us, in which normal PR are changing lines and providing a misundertood interpretation both to us and also to others that follow the repo.

**Comment by shargon** [comment]
https://github.com/neo-project/neo/pull/1016#issuecomment-520172252

> What did we discuss about waiting for review?

**Comment by vncoelho** [comment]
@lock9, "With Great Power Comes Great Responsibility"...aehuahuea
I think it would have been wiser to wait...aehuaheua 

Anyway, let's wait for more comments on this to see if we need to proceed with any adjustment.

**Comment by vncoelho** [comment]
@igormcoelho, can you provide us with the guidelines of commands that you used for that?

**Comment by lock9** [comment]
Sorry, I didn't notice the PR was created 5 hours ago, I thought it was 5 days old, sorry.
In any case, it does not change any logic, any chance this can cause problems?

**Comment by igormcoelho** [comment]
best thing is lock on a github bot.

**Comment by erikzhang** [comment]
What the hell was this??

**Comment by igormcoelho** [comment]
Sorry @erikzhang, it was necessary to finally fix all file encodings. It was breaking diffs everywhere. Now it should be fine :+1:

**Pull request merged**
