### PR TITLE
Change GetScriptContainer returns

### PR DESCRIPTION
**Pull request by shargon**
Now there is no way for create a SHA256 of the current Tx

### CODE REVIEW

**Comment by erikzhang** [comment]
Do we need `System_Runtime_GetScriptContainer` anymore?

**Comment by shargon** [comment]
Maybe we want to get the current transaction hash

**Comment by shargon** [comment]
Maybe we can detect the Interop in certains syscalls and call GetHashData if it's a `IVerificable` object?

**Comment by erikzhang** [comment]
> Maybe we want to get the current transaction hash

https://github.com/neo-project/neo/blob/9fe018c6617887534eb9f9573bde1a8509055b6e/src/neo/Network/P2P/Payloads/Transaction.cs#L336-L352

Maybe we can return this?

**Review by erikzhang — DISMISSED** [review]

**Comment by erikzhang** [comment]
Please fix the UT.

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
