### PR TITLE
[VM ADD] add debug info

### PR DESCRIPTION
**Pull request by Jim8y**
# Description
Since the new test engine in the devpack is using the default execution engine now, it is hard to debug the vm execution.
thus i add this code to print the execution opcodes.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
This does not change any existing UT.

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Even if it is only for debugging, it seems excessive to me, starting a node with debug will mean not being able to write to the console

**Comment by Jim8y** [comment]
Screenshot 2024-04-10 at 16 18 12

I need this, this pr addresses it for me. As long as you have another solution to it, i accept.

**Comment by Jim8y** [comment]
I just need it to be debuggable, tracable, fixable.

**Comment by Jim8y** [comment]
@shargon something is wrong with the ut, oom

**Comment by superboyiii** [comment]
cd547263ed91ac91e8aa965cd35fca0
I think nothing wrong with UT, all passed on the local. Something may incorrect on workflow environment?

**Review by shargon — COMMENTED** [review]
Maybe add a command line for execute script with dump is better

**Comment by Jim8y** [comment]
Man, I am debugging compiler, that won't work for me.

**Comment by shargon** [comment]
> Man, I am debugging compiler via unit test, that won't work for me.

We need to find a different way, if you try to run a node with this pr, the node will be unusable, maybe add this in unit tests engine?

**Review by shargon — APPROVED** [review]

**Pull request merged**
