### PR TITLE
NEO: clear LastGasPerVote when voting for NULL, fix #2894

### LINKED ISSUE #2894: Voting to NULL ("unvoting") in NEO doesn't clear LastGasPerVote
**Describe the bug**
When some NEO owner removes his previously casted vote completely (that is he calls `vote(acc, null)`) the old `LastGasPerVote` value is kept in the account state. It won't be used in any way since `VoteTo` is `null`, but it still takes up some storage space.

Not critical, but would be nice to fix in 3.7.

**Expected behavior**
Clear `LastGasPerVote` when voting for `null`.

**Current behavior**
https://github.com/neo-project/neo/blob/4e9314d6b33fb8158e4f2527f889a9cbe7377a73/src/Neo/SmartContract/Native/NeoToken.cs#L409-L416

**(Optional) Additional context**
Discovered accidentally with the master version of NeoGo, it had a state diff relative to released 3.6:
```
block 41660: value mismatch for key +////xTrvgat3qG/w8hQoD/I4MgUz6rygA==: QQQhAS8hA7yiAAAhAA== vs QQQhAS8hA7yiAAAhB+POSWfBCAE=
```
NeoGo tried to save an account state of
```
00000000  41 04 21 01 2f 21 03 bc  a2 00 00 21 00           |A.!./!.....!.|
```
while C# node has
```
00000000  41 04 21 01 2f 21 03 bc  a2 00 00 21 07 e3 ce 49  |A.!./!.....!...I|
00000010  67 c1 08 01                                       |g...|
```
(notice zero `21 00` vs value stored in `21 07 ...` in the end)

But it's not because NeoGo has the "proper" behavior described above, it's just that it loses `LastGasPerVote` accidentally during deserialization of non-voting account (see nspcc-dev/neo-go#3122 fix). So both nodes can be improved.

Related to #2841.

### PR DESCRIPTION
**Pull request by roman-khimov**
It's a rather trivial fix, but it needs some substantial testing wrt account balances (just comparing the state won't be enough). @superboyiii.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [X] Unit tests

### CODE REVIEW

**Review by vncoelho — COMMENTED** [review]
I remember this discussion some time ago. It seems to be ok.

**Comment by superboyiii** [comment]
I will

**Review by shargon — APPROVED** [review]
Seems good to me, just wait for @superboyiii

**Comment by superboyiii** [comment]
Although it will surely make some storage changes, but checked NEO and GAS balance on all mainnet existed account, no problem. So it should be safe.

**Review by superboyiii — APPROVED** [review]

**Review by Jim8y — APPROVED** [review]

**Comment by shargon** [comment]
> Although it will surely make some storage changes, but checked NEO and GAS balance on all mainnet existed account, no problem. So it should be safe.

Did you checked?

**Comment by superboyiii** [comment]
> > Although it will surely make some storage changes, but checked NEO and GAS balance on all mainnet existed account, no problem. So it should be safe.
> 
> Did you checked?

Yes, I checked. Many storage changes there. But the same event log(checked some of these) and the same NEO and GAS balance(all existed addresses).
For example, in a tx: `0x38091b803f794e50dcc10a9091becaf4f65d35d3ef9e71cfa90c7936af50757e` on block `39632` of mainnet,
Original Storage Changes:
```
{
    "block": 39632,
    "size": 7,
    "storage": [
        {
            "state": "Changed",
            "key": "\u002Bv///xQXVU6kNdnigqZEh4tAVHW\u002BNwA2AQ==",
            "value": "QQEhBCg32Dw="
        },
        {
            "state": "Changed",
            "key": "\u002Bv///ws=",
            "value": "68Z3AaV6Eg=="
        },
        {
            "state": "Changed",
            "key": "\u002Bv///xSPX4PVGdD5t8CX0nYRsTB3r0935Q==",
            "value": "QQEhBbkBXAAW"
        },
        {
            "state": "Changed",
            "key": "\u002B////xQXVU6kNdnigqZEh4tAVHW\u002BNwA2AQ==",
            "value": "QQQhAlEEIQPQmgAAIQfI7lv90/cA"
        },
        {
            "state": "Changed",
            "key": "\u002B////wE=",
            "value": "Riw0AQ=="
        },
        {
            "state": "Changed",
            "key": "\u002B////yED/QTemD9OBMlimrPPyD9BvnQxuWv4UqkYc8OMqPc37iw=",
            "value": "QQIgASEDKV8C"
        },
        {
            "state": "Changed",
            "key": "\u002Bv///xRjslsjaXYnEvQP2GT6JumaYZgBIw==",
            "value": "QQEhBeYy2gAW"
        }
    ]
}
```
In this PR:
```
{
    "block": 39632,
    "size": 7,
    "storage": [
        {
            "state": "Changed",
            "key": "\u002Bv///xQXVU6kNdnigqZEh4tAVHW\u002BNwA2AQ==",
            "value": "QQEhBCg32Dw="
        },
        {
            "state": "Changed",
            "key": "\u002Bv///ws=",
            "value": "68Z3AaV6Eg=="
        },
        {
            "state": "Changed",
            "key": "\u002Bv///xSPX4PVGdD5t8CX0nYRsTB3r0935Q==",
            "value": "QQEhBbkBXAAW"
        },
        {
            "state": "Changed",
            "key": "\u002B////xQXVU6kNdnigqZEh4tAVHW\u002BNwA2AQ==",
            "value": "QQQhAlEEIQPQmgAAIQA="
        },
        {
            "state": "Changed",
            "key": "\u002B////wE=",
            "value": "Riw0AQ=="
        },
        {
            "state": "Changed",
            "key": "\u002B////yED/QTemD9OBMlimrPPyD9BvnQxuWv4UqkYc8OMqPc37iw=",
            "value": "QQIgASEDKV8C"
        },
        {
            "state": "Changed",
            "key": "\u002Bv///xRjslsjaXYnEvQP2GT6JumaYZgBIw==",
            "value": "QQEhBeYy2gAW"
        }
    ]
}
```
So the differ is between the storage of key `\u002B////xQXVU6kNdnigqZEh4tAVHW\u002BNwA2AQ==`
Original: `QQQhAlEEIQPQmgAAIQfI7lv90/cA`
VS
this PR: `QQQhAlEEIQPQmgAAIQA=`

But not sure what's stored in this key.

**Comment by roman-khimov** [comment]
Exactly as expected, it's `LastGasPerVote` that's not going to be used (because account doesn't vote). So we store 0 (short) instead of something (more bytes).

**Pull request merged**
