### PR TITLE
fix: always throw `DivideByZeroException ` when `BloomFilter` is empty

### PR DESCRIPTION
**Pull request by nan01ab**
# Description

`new BloomFilter` allow to create a bloom filter that length is 0(i.e. `m` allow set to `0`), but if it's length is 0, this `BloomFilter` will always throw `DivideByZeroException` when call `Add` or `Check`.

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
It was created wrong, it should throw an exception, maybe during the constructor

**Comment by Jim8y** [comment]
> It was created wrong, it should throw an exception, maybe during the constructor

you think it should be fixed the other way?

**Comment by shargon** [comment]
> > It was created wrong, it should throw an exception, maybe during the constructor
> 
> you think it should be fixed the other way?

Throw during creation?

**Comment by Jim8y** [comment]
@nan01ab please update accordingly

**Comment by nan01ab** [comment]
> @nan01ab please update accordingly

updated

**Review by Jim8y — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by vncoelho — COMMENTED** [review]
Good fix as well

**Pull request merged**
