### PR TITLE
Fix too many open files error

### LINKED ISSUE #413: Too many open files error
The following are the environment details:

OS: Ubuntu 16.04
NEO: 2.9.0.0
Exception:
```
[ERROR][10/16/2018 09:32:13][Thread 0013][akka://NeoSystem/system/IO-TCP/$DDk] Error while creating actor instance of type Akka.IO.TcpOutgoingConnection with 3 args: (Akka.IO.TcpExt,[akka://NeoSystem/user/$b#1109912809],Connect(remote: 47.105.64.71:10333, local: , timeout: , pullMode: False))
Cause: [akka://NeoSystem/system/IO-TCP/$DDk#1048653710]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.IO.TcpOutgoingConnection with 3 args: (Akka.IO.TcpExt,[akka://NeoSystem/user/$b#1109912809],Connect(remote: 47.105.64.71:10333, local: , timeout: , pullMode: False)) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at Akka.IO.TcpOutgoingConnection..ctor(TcpExt tcp, IActorRef commander, Connect connect)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

### PR DESCRIPTION
**Pull request by yongjiema**
Fix #413 

Tasks:
- [x] Release resources when they are no longer needed
- [x] Avoid too many connections are connecting to a peer at a time
- [x] Upgrade Akka.NET to 1.3.10 which includes the fix akkadotnet/akka.net#3630

### CODE REVIEW

**Comment by erikzhang** [comment]
I will merge this PR after the release of Akka.NET 1.3.10.

**Comment by Aaronontheweb** [comment]
@erikzhang FYI, we will be releasing Akka.NET 1.3.10 tomorrow. Signed off on it in our contributor's meeting this afternoon.

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/akka.net/pull/3643 - Akka.NET v1.3.10 is now live on NuGet.

**Comment by jsolman** [comment]
Working great👍

**Pull request merged**
