### PR TITLE
protected CreateDummyBlock

### PR DESCRIPTION
**Pull request by devhawk**
for neo debugger use

### CODE REVIEW

**Comment by erikzhang** [comment]
Can you copy the code?

**Comment by devhawk** [comment]
> Can you copy the code?

Please stop asking me to duplicate code. Every time we do this, it adds maintenance effort to ensure the duplicated code stays in sync with the original code.

**Comment by erikzhang** [comment]
We do not need to reuse all the code. A lot of code is actually irrelevant and can be implemented by yourself. And these methods may be deleted in the future because they are no longer needed by core. I don't want these methods to become public APIs.

**Comment by devhawk** [comment]
> We do not need to reuse all the code. A lot of code is actually irrelevant and can be implemented by yourself. And these methods may be deleted in the future because they are no longer needed by core. I don't want these methods to become public APIs.

I fail to see how having multiple copies of code that may be deleted in the future is an improvement.

**Pull request closed without merging**
