### PR TITLE
fix consensus

### PR DESCRIPTION
**Pull request by erikzhang**
fixes neo-project/neo-cli#168

### CODE REVIEW

**Comment by shargon** [comment]
Why this change only affect to 2.7.5?

**Comment by erikzhang** [comment]
It's not clear yet. The principle of the issue is this:

1. When a block is persisted, it raise the `PersistCompleted` event:
https://github.com/neo-project/neo/blob/b9bb68b94e9231f9533ebbed2ca98ffbda0b938a/neo/Core/Blockchain.cs#L525-L532

2. The `LocalNode` handles the event, and empties the `mempool`:
https://github.com/neo-project/neo/blob/b9bb68b94e9231f9533ebbed2ca98ffbda0b938a/neo/Network/LocalNode.cs#L204-L223

3. At the same time, `ConsensusService` began a new round of consensus process:
https://github.com/neo-project/neo/blob/b9bb68b94e9231f9533ebbed2ca98ffbda0b938a/neo/Consensus/ConsensusService.cs#L64-L69

4. It invokes the method `InitializeConsensus` and then goes into `FillContext`:
https://github.com/neo-project/neo/blob/b9bb68b94e9231f9533ebbed2ca98ffbda0b938a/neo/Consensus/ConsensusService.cs#L122-L126

5. In the method `FillContext`, it tries to get transactions from the memory pool, but the memory pool is empty.

As a result, consensus nodes will always create empty blocks.

**Comment by jsolman** [comment]
To fix this, the Remaining mem_pool transactions could be reverified in Blockchain_PersistCompleted while the mem_pool lock is held instead of moving them into the temp_pool.

**Comment by jsolman** [comment]
The code in this place is the same before my change though, so this problem should have existed before my changes.

**Comment by jsolman** [comment]
The consensus should not actually be running while the pesist lock is held it should happen always after blockchain_PersistCompleted from LocalNode is done.

**Comment by shargon** [comment]
Thanks for the explanation @erikzhang , but i don't understand why only on the last version, maybe this fix don't solve the real problem.

@jsolman Can you refer here to the changes that you think cause these problems?

**Comment by jsolman** [comment]
I’ll take a look at this again within the next 24 hours. I expect the changes @erikzhang made here work around the problem, but I want to take a bit more time to look at it. If the locking is handled correctly it should make things clear and less prone to errors.

**Comment by jsolman** [comment]
Ok, just took the time to look at this. The issue is timing related since after persisting a block the mem_pool transactions get moved to the temp_pool until they can be re-verified. It's probably better to re-verify them immediately while the mem_pool lock is held so the mem_pool is always consistent as I suggested before:

> To fix this, the Remaining mem_pool transactions could be reverified in Blockchain_PersistCompleted while the mem_pool lock is held instead of moving them into the temp_pool.

It seems like moving the call to FillContext() is a reasonable change, and will make the timing issue of the mem_pool being read while empty less likely, but still doesn't remove the chance altogether. I should be able to make the changes I mentioned above in the next day or two.

**Comment by vncoelho** [comment]
Hi, @erikzhang, @shargon and @jsolman.

I am not really contributing, but I will just add some insights.

I noticed that sometimes, the mempool was not empty and the transactions were still not being added to the blocks.
Thus, the temp_pool might be another issue.

image

It was printing the mempool around here.
https://github.com/neo-project/neo/blob/master/neo/Consensus/ConsensusService.cs#L310

Playing with block times, I noticed that part of the problem was in this else here in the InitializeConsensus:
https://github.com/neo-project/neo/blob/master/neo/Consensus/ConsensusService.cs#L196

However, the problem was reduced (solved). The delay in accepting the transactions from the mempool still persisted and the mempool was being kept full for 3-4 blocks.

**Comment by vncoelho** [comment]
I also tested this current version and it seems that it is still failing here:
https://github.com/neo-project/neo/blob/e8bb7ebf81fe91fd0f1a829eaf805c52db587229/neo/Consensus/ConsensusService.cs#L358

It goes to OnTimeout and fails here 

`(context.State.HasFlag(ConsensusState.Primary) && !context.State.HasFlag(ConsensusState.RequestSent))`

But, accomplishes 
`
((context.State.HasFlag(ConsensusState.Primary) && context.State.HasFlag(ConsensusState.RequestSent)) || context.State.HasFlag(ConsensusState.Backup))
{
`

**Comment by jsolman** [comment]
I haven't had time to test my changes yet, so not issuing a pull request yet, but if anyone (maybe @vncoelho) wants to help test it. You can grab this commit and test.

https://github.com/aphtoken/neo/commit/41279e0bf16f69cd09225c45a6644f2607b2530e

I'll see if I can test it myself sometime in the next 24 hours or so.

**Comment by vncoelho** [comment]
Hey, @jsolman .

I took a brief look on #265.
I am not confident yet because one of my executions failed =/

Anyway, It looks more stable in general now.

One question, at ConsensusServices.cs, is this increase in time necessary (when view backup view is changed):
`
timer.Change(TimeSpan.FromSeconds(Blockchain.SecondsPerBlock << (view_number + 1)), Timeout.InfiniteTimeSpan);
`

Why it does not TimeOut with the Primary?

**Comment by jsolman** [comment]
@shargon Did you take a look at #265 ?

**Comment by shargon** [comment]
Give me one day more please

**Pull request closed without merging**
