### PR TITLE
Adding RPC call getstorageheight

### PR DESCRIPTION
**Pull request by vncoelho**
With a conversation with Peter and Igor we identified that this is an important call also for the exchanges, which will now be able to easily track the last time that a `StorageItem` was updated.

### CODE REVIEW

**Comment by igormcoelho** [comment]
This PR depends on this other one: https://github.com/neo-project/neo/pull/419

**Comment by erikzhang** [comment]
Why do we need this RPC method?

**Comment by shargon** [comment]
I think that maybe MPT could solve this, @igormcoelho what do you think?

**Comment by vncoelho** [comment]
Yes, but this call would be a quick access to the last height that modify that storage.

**Comment by ediopia** [comment]
It would be nicer if we can set a param of the key that we can want to track. This way we can monitor specific changes. I use this way instead browsing applicationlogs.

**Pull request closed without merging**
