### PR TITLE
Allow for programmatic configuration of protocol settings (2.x branch)

### PR DESCRIPTION
**Pull request by devhawk**
This PR is just https://github.com/neo-project/neo/pull/845 cherry picked into the master-2.x branch + a minor change to the test (defaut magic is different between master and master-2.x branch)

### CODE REVIEW

**Comment by vncoelho** [comment]
@devhawk, it sounds good.

In principle, we had discussed to not modify 2.x with additional features.
However, this might be a good exception.

It would be great to also see an example of it working, do we need to modify anything o neo-cli as well?

**Comment by devhawk** [comment]
As per the referenced PR, "This enhancement is needed to enable automatic configuration of the privatenet blockchain". This PR is the same scenario - just a privatenet for neo 2.x instead of 3.0.

**Comment by devhawk** [comment]
Example Usage:

``` csharp

// private function from privatenet run code path.
// PrivateNet.Parse will create Wallet instances that end up accessing ProtocolSettings. 
// The "two-phase" initialization below allows protocol settings to be configured correctly 
// before default initialization is triggered.
PrivateNet LoadChain()
{
    using (var stream = File.OpenRead(input))
    using (var json = JsonDocument.Parse(stream))
    {
        if (!PrivateNet.InitializeProtocolSettings(json, SecondsPerBlock))
        {
            throw new Exception("Couldn't initialize protocol settings");
        }

        return PrivateNet.Parse(json);
    }
}
 
// PrivateNet.InitializeProtocolSettings reads the public key and port info from JSON file directly
// to avoid default initialization of ProtocolSettings.
public static bool InitializeProtocolSettings(JsonElement json, uint secondsPerBlock = 0)
{
    // retrieve each node's public key and tcpPort from the JSON file
    var nodes = json.GetProperty("consensus-nodes")
        .EnumerateArray()
        .Select(DevConsensusNode.ParseProtocolSettings);

    // default to 15 seconds per block
    secondsPerBlock = secondsPerBlock == 0 ? 15 : secondsPerBlock;

    IEnumerable<KeyValuePair<string, string>> settings()
    {
        yield return new KeyValuePair<string, string>(
            "ProtocolConfiguration:Magic", $"{json.GetProperty("magic").GetUInt32()}");
        yield return new KeyValuePair<string, string>(
            "ProtocolConfiguration:AddressVersion", $"{(byte)0x17}");
        yield return new KeyValuePair<string, string>(
            "ProtocolConfiguration:SecondsPerBlock", $"{secondsPerBlock}");

        foreach (var node in nodes.Select((n, i) => (config:n, index:i)))
        {
            yield return new KeyValuePair<string, string>(
                $"ProtocolConfiguration:StandbyValidators:{node.index}", node.config.publicKey.EncodePoint(true).ToHexString());
            yield return new KeyValuePair<string, string>(
                $"ProtocolConfiguration:SeedList:{node.index}", $"{IPAddress.Loopback}:{node.config.tcpPort}");
        }
    }

    var config = new ConfigurationBuilder()
        .AddInMemoryCollection(settings())
        .Build();

    return ProtocolSettings.Initialize(config);
}
```

**Comment by igormcoelho** [comment]
@devhawk can you push this example as another UT ? Just to register... It could be perhaps some sample code just to load and unload a network... and could we somehow isolate this "test" from others?

**Comment by igormcoelho** [comment]
let's see this in details @shargon.. perhaps it helps debugging from ngd shanghai too, on network 2x. ability to test without disk file is important... lets think.

**Comment by lock9** [comment]
@shargon  but this will help, and NEO 3 launch date is December 2019. Are we going to leave this hanging for 6 months? :(
I think this is good, if our code doesn't use it, it is ok. I think that this is a very good feature - It is way better to use a class as a guide than using a json file.

**Comment by devhawk** [comment]
FYI, I had to clean up my NEO fork. I screwed up originally and did this work on directly in my fork's master-2.x branch. I will resubmit once I get clarification on adding features to 2.x branches

**Comment by wanglongfei88** [comment]
> let's see this in details @shargon.. perhaps it helps debugging from ngd shanghai too, on network 2x. ability to test without disk file is important... lets think.
This is a very important pr for NEO2 as well. Without it, it will be a blocker for NEO2 vs code extension as well as improving debugging experience.

**Pull request closed without merging**
