### PR TITLE
Drop `Addr` messages if we didn't send `GetAddr`

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by vncoelho — APPROVED** [review]

**Review by vncoelho — COMMENTED** [review]
Good and simple, this can avoid filling the queue and analyzing unnecessary messages.

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
致谢信息
--------------------
该漏洞发现者是腾讯安全玄武实验室的安全研究员梁明月。

**Comment by ProDog** [comment]
I got a run error:

image

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Neo
  StackTrace:
   at Neo.Network.P2P.RemoteNode.SendMessage(Message message) in D:\neo_code\neo\src\neo\Network\P2P\RemoteNode.cs:line 201
   at Neo.Network.P2P.RemoteNode.CheckMessageQueue() in D:\neo_code\neo\src\neo\Network\P2P\RemoteNode.cs:line 58
   at Neo.Network.P2P.RemoteNode.EnqueueMessage(Message message) in D:\neo_code\neo\src\neo\Network\P2P\RemoteNode.cs:line 103
   at Neo.Network.P2P.RemoteNode.OnReceive(Object message) in D:\neo_code\neo\src\neo\Network\P2P\RemoteNode.cs:line 136
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

```

**Comment by erikzhang** [comment]
Should be fixed by #2105

**Pull request merged**
