### PR TITLE
Some ut for Neo.Iterator.Concat

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by shargon** [comment]
I am trying to proobe that there is no overflow in the implementation, but i was thinking about this and maybe is wrong. If we concat the same object, is returned just one time, and should be returned twice

**Comment by shargon** [comment]
We should have test for `MapWrapper` because i think that we need a `Clone` method in `IIterator`

**Comment by shargon** [comment]
What do you think about the `Clone` method? because now if you concat `MapWrapper` doesn't work

**Comment by erikzhang** [comment]
I don't think `Concat` should support concatenating the same object.

**Comment by shargon** [comment]
Then we should throw an exception?

**Pull request merged**
