### PR TITLE
[Neo CLI FIX] fix https://github.com/neo-project/neo/issues/3357

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

This pr fixes the issue of version explained in https://github.com/neo-project/neo/issues/3357

Fixes # https://github.com/neo-project/neo/issues/3357

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vncoelho — APPROVED** [review]

**Review by cschuchardt88 — CHANGES_REQUESTED** [review]
@vncoelho 
I removed it. We input version in `github` workflow actions. Reason for this is so version is synced and doesnt get mismatched. If you were here you would know what going on. Plus @Jim8y  wants small PR and since there isnt a release coming out right this second. No need jump to undo something Im changing to get repo up to date. And you end up wasting my time try to undo everything every single time. You should review or check-in daily to know and see what going on.

**Review by shargon — APPROVED** [review]

**Comment by cschuchardt88** [comment]
@vncoelho so your saying with 👎 you want to do everything manually? And keep all these issues with the repo? When it comes time to release.

**Comment by vncoelho** [comment]
> @vncoelho so your saying with 👎 you want to do everything manually? And keep all these issues with the repo? When it comes time to release.

no

**Review by cschuchardt88 — APPROVED** [review]
@shargon 
Ill approve this, seeing nothing is wrong with this PR. But I don't think we should have it. PR #3308 resolves this issue for release but not locally development; for maintainable.

**Pull request merged**
