### PR TITLE
Add UTXO Tracking by Account

### PR DESCRIPTION
**Pull request by jsolman**
This change keeps track of unspent UTXOs (for NEO and GAS) by account script hash. Enabling this feature is controlled by a setting that defaults to false. This change also exposes the unspent UTXOs through RPC in the same JSON format that Neoscan returns in its `get_balance` v1 API call.

I measured the storage overhead for this feature for MainNet on Thursday, January 3, 2019. For the version of LevelDB used, the size increase on disk with this feature enabled for MainNet was only around a 6.65% increase: 11760008 KB vs. 11027004 KB.

While this feature could be implemented in a plugin. One reason to put it in the core is that the wallets code could take advantage of it instead of needing to re-index as much when opening a wallet. This change does not yet change the Wallets code to do that (best to ensure this will be able to live in the core first before potentially wasting effort to make those changes).

A major advantage of these changes is that sending NEO or GAS for arbitrary addresses would no longer require talking to another server besides a standard RPC node.

### CODE REVIEW

**Comment by erikzhang** [comment]
We are going to abolish all global assets in NEO 3.0, including neo and gas. So there is no need to improve this in NEO 2.x.

**Comment by jsolman** [comment]
That makes sense for Neo 3.0/3.x, but if Neo 2.x is always going to have the global assets, doesn't that mean it will always need it?

Is there are separate branch / for Neo 3.0? At some point the code base for Neo 2.x and Neo 3.0 will need to diverge. It seems like this feature will be wanted by many on Neo 2.x.

**Comment by vncoelho** [comment]
Great to hear that, @erikzhang. Count with us!
Who is going to open the first PR with the template for the UTXO removal? If you could push the design of a basic template, @erikzhang, we can discuss and brainstorm this transition/evolution (merkle root will probably play the role of the UTXO).

@jsolman, I think that I will probably not use NEO 2.x once nodes of NEO 3.x are released.

**Comment by erikzhang** [comment]
When the NEO 3.0 network is started, the 2.x network will be stopped and the data will be retained and migrated to 3.0.

**Comment by jsolman** [comment]
@erikzhang how will that work for contracts that need NEO or GAS to be a UTXO based asset?

The contract owner will have to write a new contract and do a token swap?

**Comment by shargon** [comment]
@jsolman  All contracts must be recompiled, and re-deployed

**Comment by vncoelho** [comment]
Sounds like a good business for RED4SEC....aegauehauheauhueaea
I am kidding, @shargon.... :package: 
You are a master in security! Always with eagle eyes.

**Comment by jsolman** [comment]
@shargon recompiled is a bit of an understatement. Definitely significant code changes will be needed to some contracts before any recompiling.

**Comment by erikzhang** [comment]
> so I guess Nep-5 will be the only asset model, right?

NEP-5, NFT, STO, ...

**Comment by shargon** [comment]
@jsolman I know, but this move should be required

**Comment by saltyskip** [comment]
Maybe UTXO will be removed in NEO 3.0, but without a time on when this happens I am strongly in support of this being merged in. Centralized UTXO API's can be notoriously unstable, and the failure of one server can lead to widespread wallet outages in the NEO ecosystem

Having this merged into core would be immensely helpful for light wallets.

**Comment by vncoelho** [comment]
If this could be merged as a plugin it would be better for merging now, avoiding future extra work in removing it.

**Comment by jsolman** [comment]
I've had plans since for a bit to make it a plugin. There are a few other high priorities first. I should get to it within a few weeks I suspect.

**Comment by vncoelho** [comment]
Go for it, Jeff. I think that it is interesting to have this working as a plugin for future references.

**Comment by vncoelho** [comment]
@jsolman, could you think about a flag in each UTXO?

- initially it should be set to false
- then, we watch all claimtransactions and set to `true` all UTXO that were claimed.

I think that this would be enough for us to track claimable gas and it will currently benefit several projects.

In a reasonable thinking, UTXO banning will take some more couple of months and this is a very useful PR that you did.

**Comment by jsolman** [comment]
I expect to migrate this to a plugin on Sunday. After that I can look into adding claims support.

**Comment by igormcoelho** [comment]
+1 for plugin. No need for this in core.

**Comment by jsolman** [comment]
I've started to migrate this to a plugin. It will take a little longer still.

**Comment by jsolman** [comment]
Closing, since this was moved to a plugin instead: https://github.com/neo-project/neo-plugins/pull/52

**Pull request closed without merging**
