### PR TITLE
Check errors on WalletIndexer

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by erikzhang** [comment]
It's a background thread that is terminated when the program exits.

**Comment by shargon** [comment]
Yes, but if your are indexing your wallet, this thread throw one exception when main form is closing

**Comment by erikzhang** [comment]
Can we just catch the exception?

**Comment by AshRolls** [comment]
It would be better practice to deal with the root cause of the exception rather than just catch and discard.

**Comment by erikzhang** [comment]
Allowing the GUI to close `WalletIndexer` directly can increase the coupling of the system and may affect other components that depend on it .

**Comment by shargon** [comment]
This is the random exception

image

**Comment by shargon** [comment]
@erikzhang How dow you preffer deal with this? maybe `return false` in TryGet if `handle` is invalid ?

**Comment by erikzhang** [comment]
It throws exception because the leveldb has been disposed when we try to call `GetBlock` in `WalletIndexer.ProcessBlocks`. So we can catch the exception in `WalletIndexer.ProcessBlocks` for `GetBlock`.

**Comment by shargon** [comment]
@erikzhang Please, check this new method

**Comment by erikzhang** [comment]
Please modify the title of this PR before merging.

**Pull request merged**
