### PR TITLE
Role: add NeoFS alphabet node role

### PR DESCRIPTION
**Pull request by roman-khimov**
This is needed to implement NeoFS governance scheme (#2267).

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
InnerRing?

**Comment by roman-khimov** [comment]
They're IR nodes, yes, but at the same time they're not all of IR (a subset of full IR). We do call this particular set of nodes "alphabet" nodes throughout the documentation already, so maybe it's OK to call them the same way here.

**Review by erikzhang — APPROVED** [review]

**Comment by erikzhang** [comment]
How do other IRs come about?

**Comment by roman-khimov** [comment]
As per governance scheme they're added/removed dynamically:

> Inner Ring nodes follow a self regulation process, allowing them to vote for substitution of dead or malfunctioning nodes with new ones from the candidate list. Only Alphabet nodes prepare new InnerRing nodes lists and vote for it, but all nodes listed there must confirm their participation via the samevoting mechanism.

**Pull request merged**
