### PR TITLE
Add Json Serialization

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by superboyiii** [comment]
@erikzhang Can you add some unit tests first. This is a large modification.

**Comment by cschuchardt88** [comment]
Why we keep reinventing the wheel here? We should be using `NewtonSoft.Json` or something similar.

**Comment by Jim8y** [comment]
> Why we keep reinventing the wheel here? We should be using `NewtonSoft.Json` or something similar.

For making the whole process controllable and determinastic.

**Comment by vncoelho** [comment]
As well as performance.
We did some experiments in the past.
Maybe nowadays it is faster but not sure.

**Comment by cschuchardt88** [comment]
But we are using a stone wheel here on a spot car for instance.

@vncoelho we don't use huge `json`. So benchmarks will not show much change. But as for the useability and flexibility it's 1000 times better than what we have, and plus we can tie into other systems easily. It will help fix #3037 out of the box and also has what this PR is reinventing. So all the problems that you will eventually find or run into, are already done with any good `json` library on `nuget` like `NewtonSoft.Json` (_[157,196,338](https://www.nuget.org/stats/packages/newtonsoft.json?groupby=Version)  downloads; that should tell you something)_

**Comment by vncoelho** [comment]
I am not against it. 
Perhaps it is worth give a try.

**Comment by Jim8y** [comment]
Close as inactive

**Pull request closed without merging**
