### PR TITLE
Set max persisted conflicts signers (2/2)

### PR DESCRIPTION
**Pull request by shargon**
Fix memory pool issue related to https://github.com/neo-project/neo/issues/2907

### CODE REVIEW

**Comment by shargon** [comment]
@AnnaShaleva @vang1ong7ang What do you think? if we persist the first 100 entries, the maximum transactions in a block will be 512, the next block all will be invalidated.

We can decrease the 100 entries

**Comment by vang1ong7ang** [comment]
from <https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinct?view=net-7.0>:

> The [Distinct<TSource>(IEnumerable<TSource>, IEqualityComparer<TSource>)](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinct?view=net-7.0#system-linq-enumerable-distinct-1(system-collections-generic-ienumerable((-0))-system-collections-generic-iequalitycomparer((-0)))) method returns an unordered sequence that contains no duplicate values.

maybe the order should be ensured to avoid state conflicts

**Comment by shargon** [comment]
In the worst scenario we will open a door to cancel future transactions from arbitrary accounts (https://github.com/neo-project/neo/pull/2818#issuecomment-1632278255) after this limit is exceeded.

**Comment by AnnaShaleva** [comment]
We can't take *some* of them, because conflicting logic will be broken in this case. We definitely need to persist all conflicting signers. I think that additional mempool check mentioned in https://github.com/neo-project/neo/pull/2908#discussion_r1327332681 will solve the issue, I just need some more time to implement it. And it won't cost much, because we already have `_conflicts` dictionary stored in the mempool. All we need is to extend the dictionary value to a structure that stores not only transactions hashes, but also signers hashes.

**Comment by vang1ong7ang** [comment]
@shargon I think it is a good and useful PR and we should seriously consider.

it's risky to allow `ConflictingSigners` keep growing though there is a writing limitation in binary serialization. (`1024*1024` IIRC)

**Pull request closed without merging**
