### PR TITLE
Fixing wrong size on ConsensusPayload

### PR DESCRIPTION
**Pull request by vncoelho**
Can you take a look if that proceeds? If yes, let's port to master2.x

### CODE REVIEW

**Comment by vncoelho** [comment]
I just double checked here and `master2x` looks safe, https://github.com/neo-project/neo/blob/425eaa7a6fabb568a50f5647ad58ae7a4431d0f3/neo/Network/P2P/Payloads/ConsensusPayload.cs#L20

This minor size error was just here.

**Comment by igormcoelho** [comment]
Brother, this is supposed to be tested. Let me see if it passes.

**Comment by igormcoelho** [comment]
I couldn't push into this branch.. strange...
This is the test we need to add here:
```cs
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Neo.IO.Json;
using Neo.IO;
using Neo.Network.P2P.Payloads;
using System.IO;
using System.Text;

namespace Neo.UnitTests
{
    [TestClass]
    public class UT_ConsensusPayload
    {
        ConsensusPayload uut;

        [TestInitialize]
        public void TestSetup()
        {
            uut = new ConsensusPayload();
            uut.Witness = new Witness();
            uut.Witness.InvocationScript = new byte[0];
            uut.Witness.VerificationScript = new byte[0];
            uut.PrevHash = new UInt256();
            uut.Data = new byte[0];
        }

        [TestMethod]
        public void Test_Size()
        {
            uut.PrevHash.Size.Should().Be(32);
            uut.Data.GetVarSize().Should().Be(1);
            uut.Witness.Size.Should().Be(2); // +1 (implicit array)

            uut.Size.Should().Be(4 + 32 + 4 + 2 + 1 + (1+2));
        }
    }
}
```

**Comment by shargon** [comment]
@vncoelho good eyes!

**Pull request merged**
