### PR TITLE
Clean unused code

### PR DESCRIPTION
**Pull request by shargon**
Clean code

### CODE REVIEW

**Comment by shargon** [comment]
Why we need two classes one for keys and other for values? these classes have the same logic

**Comment by erikzhang** [comment]
One returns `Key()` and another returns `Value()`. They are different.

**Comment by shargon** [comment]
Ups xD thanks for your review :)

**Comment by erikzhang** [comment]
`AssetDescriptor` is used in neo-cli and neo-gui.

**Pull request merged**
