### PR TITLE
fix null values while checking ChangeViewReason

### PR DESCRIPTION
**Pull request by belane**
Consensus is crashing here because **TransactionHashes** and **Transactions** are not yet initialized in the first timeout/changeview.
https://github.com/neo-project/neo/blob/2bbcb1448dc01345dfd102cdfccb8f216a72f648/neo/Consensus/ConsensusService.cs#L554 

```
[17:54:11.093] OnStart
[17:54:11.126] initialize: height=1 view=0 index=0 role=Backup
[17:54:14.140] timeout: height=1 view=0
[17:54:14.160] OnStop
[ERROR][08/09/2019 17:54:14][Thread 0008][akka://NeoSystem/user/$d] Value cannot be null.
Parameter name: source
Cause: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Neo.Consensus.ConsensusService.OnTimer(Timer timer) in /src/neo/neo/Consensus/ConsensusService.cs:line 554
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by vncoelho** [comment]
What did we discuss about waiting for review?

I know it is critical but this was not the last agreement, @erikzhang.

**Comment by vncoelho** [comment]
"Hi @everyone, Erik suggests make some adjustment to Github's process so that we can work better: 
1. Open an issue and close it on PR. After a proposal has been submitted, it must be fully discussed. A complete plan should be reached before implementation.
2. Add a ready-for-implementation tag to know which proposals can be implemented.
3. The implementer should ask others' opinion before starting implementation. The proposer may have a priority to implement it if he wants. 
4. Even if the code has been approved, you should leave at least 24 hours for others to review it. 
5. The code should be tested before it is approved.
6. Those tagged trivial will not be included in the reward.

Feel free to share your comments. "

**Comment by shargon** [comment]
You are right @vncoelho, my bad

**Comment by shargon** [comment]
In order to prevent future issues, we should require at least two reviews for merge. @lock9

**Comment by vncoelho** [comment]
no worries, @shargon.


I just said that because this is, particularly, a part of the code that I like...jajajaja
Anyway...
But i think that 2 reviews is good for master and 3 for master2x.

**Pull request merged**
