### PR TITLE
Remove `UT_Culture.cs`

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by igormcoelho** [comment]
Why is it so slow? Couldnt we improve speed without losing coverage?

**Comment by shargon** [comment]
it produce some problems with multiple iterations, but i think is a problem of the unit test. I think that this test is good for testing the unit tests

**Comment by igormcoelho** [comment]
Erik, I have a better idea, lets not remove this. Lets create another benchmark project, neo.benchmarks, and put heavy stuff not run on every build. We can put extensive tests there.

**Comment by igormcoelho** [comment]
Please, let's consider https://github.com/neo-project/neo/pull/866

**Pull request closed without merging**
