### PR TITLE
Add NameService UT

### PR DESCRIPTION
**Pull request by cloud8little**

### CODE REVIEW

**Comment by cloud8little** [comment]
@erikzhang do we allow these data to be stored as IPv4 name service? I do not think they are valid ipv4 address.  but currently they are valid values from testing result.
```cs
            setRecord_ret = Check_SetRecord(snapshot, domain, RecordType.A, "0.0.256", from, persistingBlock);
            setRecord_ret.Should().BeFalse();

            setRecord_ret = Check_SetRecord(snapshot, domain, RecordType.A, "0.257", from, persistingBlock);
            setRecord_ret.Should().BeFalse();

            setRecord_ret = Check_SetRecord(snapshot, domain, RecordType.A, "257", from, persistingBlock);
            setRecord_ret.Should().BeFalse();
```

**Comment by erikzhang** [comment]
Please check #2262

**Comment by cloud8little** [comment]
wait for #2262

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
@cloud8little Merge?

**Comment by cloud8little** [comment]
good to merge

**Review by vncoelho — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
