### PR TITLE
fix blockchain on transaction array logic

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close https://github.com/neo-project/neo/pull/2116#discussion_r541565902

### CODE REVIEW

**Review by shargon — DISMISSED** [review]

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/eb63d30f4c326f18926243dd727e3c3d3e36c48e/src/neo/Ledger/MemoryPool.cs#L109-L118

I think there is no need to return `policyChanged` now.

**Comment by Qiao-Jin** [comment]
> And also we don't need to send the transactions from `MemoryPool` to `Blockchain`.

If there are more transactions in mempool than MaxTransactionPerBlock I think this logic will be executed?

**Comment by erikzhang** [comment]
Let's remove `policyChanged` first.

**Comment by Qiao-Jin** [comment]
@erikzhang Please have a look

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
