### PR TITLE
Downgrade Sqlite to 2.1.4

### PR DESCRIPTION
**Pull request by vncoelho**
```
/opt/neoLib/neo/neo.csproj : error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.  [/opt/neoCli/neo-cli/neo-cli.csproj]
/opt/neoLib/neo/neo.csproj : error NU1605:  Neo -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.unix.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)  [/opt/neoCli/neo-cli/neo-cli.csproj]
/opt/neoLib/neo/neo.csproj : error NU1605:  Neo -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1) [/opt/neoCli/neo-cli/neo-cli.csproj]
```

### CODE REVIEW

**Comment by vncoelho** [comment]
Hi @erikzhang, what do you think?

We do not have the Visual Studio environment and we use everything on Linux base machine.
Our environment mostly uses Dotnet and Mono-Complete with MSBuild.
We are having the aforementioned error, then, we downgrade the package.

Another possibility would be to include those additional mentioned dependencies. I do not have experience in handling these NuGets.

**Comment by vncoelho** [comment]
https://cdn.discordapp.com/attachments/410872892197175296/532328474174816269/IMG-20190108-WA0050.jpg

Doing the best to stay on top. ajauaha

The only 2.9.4 full node.

**Comment by jsolman** [comment]
I’ve been running a couple nodes on 2.9.4 since about 24 hours ago.

**Comment by vncoelho** [comment]
Happy nodes syncs version and discover once a day I think.

@Jeff, did you have any problem with this NuGet version? maybe it is only a problem for dotnet

**Comment by igormcoelho** [comment]
fast guys !! Did you.notice any dependency problem on sqlite @jsolman ? Or could it be somehow related to our dotnet docker image? (not very likely in my opinion, but possible...)

**Comment by vncoelho** [comment]
Broooda, what a syncronism....ahauaja

**Comment by igormcoelho** [comment]
Reading minds brother :)

**Comment by vncoelho** [comment]
Again....kkkkkk ahauaha

**Comment by erikzhang** [comment]
I have no issue with Sqlite 2.2.0 on my environment. Can you try to upgrade to Sqlite 2.2.1 and see if the problem is solved?

**Comment by jsolman** [comment]
I tried 2.2.1 and the problem isn't solved:
```
error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
 error NU1605:  Neo -> Microsoft.EntityFrameworkCore.Sqlite 2.2.1 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.1 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.unix.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
```

**Comment by jsolman** [comment]
@erikzhang if you want to see the problem in your environment do something like:
```
dotnet publish -r linux-x64 --self-contained
```
I suspect building with `--self-contained` will cause the problem with other runtimes also.
For whatever reason it doesn't complain about the downgrade though if I do `dotnet build` or `dotnet publish`

**Pull request merged**
