### PR TITLE
Fix invocation counter

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo-devpack-dotnet/pull/391#issuecomment-739755706

### CODE REVIEW

**Comment by ProDog** [comment]
It's still 2 😦.

**Comment by cloud8little** [comment]
> It's still 2 😦.

Maybe it is because it called onPayment  and then call mint.

**Comment by shargon** [comment]
In the template it doesn't call `Mint` during `onPayment`

**Comment by cloud8little** [comment]
> In the template it doesn't call `Mint` during `onPayment`

It need to make a transfer notification first(for Mint to work), which needs to transfer neo/gas to the contract address, that will call onPayment.

**Comment by shargon** [comment]
Yes, then should be two 😂

**Comment by erikzhang** [comment]
Close?

**Pull request closed without merging**
