### PR TITLE
Devhawk/getAddressVersion2

### PR DESCRIPTION
**Pull request by devhawk**
Replacement PR for #2684 that was closed by mistake

### CODE REVIEW

**Comment by erikzhang** [comment]
Since we already have `System.Contract.CreateStandardAccount` and `System.Contract.CreateMultisigAccount`, do we need this one anymore? What is the use case?

**Comment by devhawk** [comment]
UInt

> Since we already have `System.Contract.CreateStandardAccount` and `System.Contract.CreateMultisigAccount`, do we need this one anymore? What is the use case?

UInt160.ToAddress needs the Address Version.

**Comment by erikzhang** [comment]
But why do we need to convert script hash to address in a contract? I think it should be done in the frontend.

**Comment by devhawk** [comment]
> But why do we need to convert script hash to address in a contract? I think it should be done in the frontend.

`UInt160.ToAddress` exists today. I would argue the design is poor since it requires the caller to provide an address version parameter. If there are scenarios for converting a script hash to an address *with a different address version than the current chain* I can't think of them.

**Review by erikzhang — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Pull request merged**
