### PR TITLE
Oracle: Unify relay cache

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by shargon** [comment]
I am not sure about this change @erikzhang because a flood in oracle messages can alter the consensus flow

**Comment by erikzhang** [comment]
Is OraclePayload used for communication between oracle nodes?

**Comment by shargon** [comment]
> Is OraclePayload used for communication between oracle nodes?

Yes, it's used for share his signatures.

**Comment by erikzhang** [comment]
If we can verify the signature of Oracle node, then it won't be a spam.

**Pull request merged**
