### PR TITLE
Add support to automated smart contract

### PR DESCRIPTION
**Pull request by Liaojinghui**
This PR implements the automated smart contract. Check more detail in issue #2473.

### CODE REVIEW

**Comment by shargon** [comment]
Could you split automated smart contract and VRF?

**Comment by Liaojinghui** [comment]
This is ugly, it requires too many modifications to the existing system. Any help to improve the compatibility is more than welcome.

**Comment by shargon** [comment]
@Liaojinghui please wait for approval, in the past something similar was not

**Comment by Liaojinghui** [comment]
> @Liaojinghui please wait for approval, in the past something similar was not

that is ok, i dont like this vrrsion anyway, trying to use existing request to implement it.

**Pull request closed without merging**
