### PR TITLE
Optimize IInventory serialization

### PR DESCRIPTION
**Pull request by shargon**
According to https://github.com/neo-project/neo/pull/1766#issuecomment-658515198

This changes trying to avoid the re-serialization of `IInventories` when we send the same block or transaction that we receive previously.

### CODE REVIEW

**Comment by erikzhang** [comment]
Is it worth optimizing?

**Comment by shargon** [comment]
@Tommo-L do you have any stadistic of how much can improve this PR? 

I think that the cpu should be improved, because it reduce the serialization and compression close to 0, you will increase the memory, but I think that cpu it's more important in order to improve the tps.

**Comment by Tommo-L** [comment]
We'll do a benchmark for this pr.

**Comment by shargon** [comment]
@Tommo-L any update?

**Comment by Tommo-L** [comment]
We have done a test, but it wasn't much improvement. It is not recommended to add it. 😂

**Pull request closed without merging**
