### PR TITLE
Change Initialize GAS to 52000000 * Factor

### PR DESCRIPTION
**Pull request by superboyiii**
5200W is the total generated GAS amount on blockheight of 800W on Neo Legacy.

### CODE REVIEW

**Review by erikzhang — DISMISSED** [review]

**Review by shargon — DISMISSED** [review]

**Comment by erikzhang** [comment]
Move it to settings? I think some private chains may modify it.

**Review by shargon — APPROVED** [review]

**Review by erikzhang — DISMISSED** [review]

**Comment by superboyiii** [comment]
Merge？

**Comment by superboyiii** [comment]
I implement `InitialGasDistribution` to config.json and set value to it, it throw: "Object reference not set to an instance of an object". 
However, when I change it to `long`, everything is OK.
image
image

```
section.GetValue("InitialGasDistribution", Default.InitialGasDistribution)
'section.GetValue("InitialGasDistribution", Default.InitialGasDistribution)' threw an exception of type 'System.NullReferenceException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147467261
    HelpLink: null
    InnerException: null
    Message: "Object reference not set to an instance of an object."
    Source: "System.Private.CoreLib"
    StackTrace: "   at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)\r\n   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue[T](IConfiguration configuration, String key, T defaultValue)"
    TargetSite: {Byte& Unbox(Void*, System.Object)}
section.ToString()
```

**Comment by erikzhang** [comment]
@superboyiii Can you test it again?

**Review by shargon — APPROVED** [review]

**Comment by superboyiii** [comment]
> @superboyiii Can you test it again?

Test OK

**Comment by superboyiii** [comment]
Merge?

**Pull request merged**
