### PR TITLE
Deserialize limit (2x)

### PR DESCRIPTION
**Pull request by shargon**
Port of https://github.com/neo-project/neo/pull/870 to master-2x

### CODE REVIEW

**Comment by shargon** [comment]
@superboyiii could your team test the backward compatibility?

**Comment by superboyiii** [comment]
> @superboyiii could your team test the backward compatibility?

Sure.

**Comment by superboyiii** [comment]
@shargon  @nicolegys is making test on this PR now, need two days for chain sync on both mainnet and testnet.

**Comment by shargon** [comment]
Good!

**Comment by nicolegys** [comment]
Compatibility test passed, both on mainnet and testnet.

**Pull request merged**
