### PR TITLE
Check dotnet format and utf8 non-boom files with travis

### PR DESCRIPTION
**Pull request by shargon**
This will prevent to push any format error

Related to https://github.com/neo-project/neo/issues/982

### CODE REVIEW

**Comment by shargon** [comment]
I think that it's done, any pr without a good format won't pass

**Comment by shargon** [comment]
No, is not finished, is checking the unit test folder only

**Comment by shargon** [comment]
CRLF is not checked in dotnet format?

**Comment by igormcoelho** [comment]
> CRLF is not checked in dotnet format?

Nope.. only language structure formatting... that's why it was hard to fix this. This is deeper level stuff, as dotnet format seems to respect original line break format. We need to explicitly check it.

**Comment by vncoelho** [comment]
I agree, @igormcoelho, I tried to search for a solution for some couple of days check that `dos2unix` commands...aehuahea
It is great that you solved that.

Furthermore, this travis automatic check is going to be quite useful.

**Comment by igormcoelho** [comment]
Too bad: Ubuntu bionic 18.04 is too old now... repo `dos2unix` points to version 6, but we need version 7+.
`2014-10-06: Version 7.1. New option -i, --info, display file information.`
I'll what we can do... pehaps compile it, or evolve ubuntu image.

**Comment by igormcoelho** [comment]
Managed to install `dos2unix 7.4.0` :muscle: 
Just performing final tests.

**Comment by shargon** [comment]
It's prepared for non-boom files?

**Comment by igormcoelho** [comment]
> It's prepared for non-boom utf8 files?

It's ignoring bom format right now... but I'll put another test here, to enforce no_bom situation. This will make us more careful.

**Comment by igormcoelho** [comment]
> dos2unix could say which file is wrong?

It could, but the current test will just fail on counting... it checks the count of existing files against no_bom prefix count. If it fails, we would need to inspect all files manually, so perhaps I'll add another verbose part on travis, just to inform us, when needed.

**Comment by shargon** [comment]
Will be great if in the future we can check all together, i opened a issue in `dotnet format` for this https://github.com/dotnet/format/issues/347

**Comment by erikzhang** [comment]
I think we should merge this with #1057

**Pull request closed without merging**
