### PR TITLE
Neo.CLI: enable hardforks for NeoFS mainnet

### PR DESCRIPTION
**Pull request by AnnaShaleva**
# Description

Otherwise this configuration file is broken. Port changes from https://github.com/nspcc-dev/neo-go/pull/3446.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
Just asking, why cont fs use the mainnet hf setting?

**Review by vncoelho — APPROVED** [review]

**Comment by vncoelho** [comment]
> Just asking, why cont fs use the mainnet hf setting?

Agreed, better to unify this settings into a class later and then just extract the info where we need it.

**Comment by AnnaShaleva** [comment]
> Just asking, why cont fs use the mainnet hf setting?

It's a separate chain with its own settings and block heights, so it needs its own settings.

**Comment by roman-khimov** [comment]
> It's a separate chain with its own settings

And the fun thing is that it's longer than the "main" mainnet itself:
```
$ ./bin/neo-go query height -r https://rpc7.morph.fs.neo.org:40341
Latest block: 5701933
Validated state: 0
$ ./bin/neo-go query height -r https://rpc10.n3.nspcc.ru:10331
Latest block: 5396462
Validated state: 5396462
```

**Review by roman-khimov — APPROVED** [review]

**Comment by Jim8y** [comment]
@NGDAdmin merge

**Review by shargon — APPROVED** [review]

**Pull request merged**
