### PR TITLE
3.2.1

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by superboyiii — DISMISSED** [review]

**Comment by superboyiii** [comment]
@shargon approve?

**Comment by superboyiii** [comment]
Please check all copyright from `2016-2021` to `2016-2022`

**Comment by Liaojinghui** [comment]
@superboyiii you dont have to change the copyright at all. What really matters is to tell others this file is under  MIT license.

**Comment by superboyiii** [comment]
> @superboyiii you dont have to change the copyright at all. What really matters is to tell others this file is under MIT license.

Can do both.

**Comment by Liaojinghui** [comment]
> Can do both.

Just saying. Wont hurt.

**Review by shargon — DISMISSED** [review]

**Pull request merged**
