### PR TITLE
allow CheckWitness to work when using invokescript

### PR DESCRIPTION
**Pull request by trueinsider**
This change will allow execution of smart contracts with `CheckWitness` call inside them by passing script hash (as optional parameter) for which `CheckWitness` should be successful to `invokescript`.

This change was made with this issue in mind: https://github.com/nos/client/issues/133 but I hope it will make life of smart contract devs easier.

cc @deanpress @mhuggins @jeroenptrs

### CODE REVIEW

**Comment by trueinsider** [comment]
@erikzhang could you please take a look?

**Comment by erikzhang** [comment]
Perhaps creating a real `InvocationTransaction` would be better than creating a `CheckWitnessHashes`.

**Comment by trueinsider** [comment]
@erikzhang That is the way I tried it at first, but unsuccessfully. To spoof witness with `InvocationTransaction` I need to spoof `Inputs` of that transaction. And transaction verification would fail without real signature generated with real private key. That makes it impossible to spoof random address for `CheckWitness()`

**Comment by erikzhang** [comment]
You can attach a `TransactionAttribute` to the `InvocationTransaction` for `CheckWitness()`.

https://github.com/neo-project/neo/blob/master/neo/Core/TransactionAttributeUsage.cs#L25

**Comment by dicarlo2** [comment]
FWIW: neo-one has an additional rpc method `testinvocation` that accepts an `InvocationTransaction` and executes it.

**Comment by igormcoelho** [comment]
I'm trying to develop an AVM execution Simulator for Neo on JavaScript, that will serve for these situations when you want the exact execution, without the actual execution. 
https://github.com/NeoResearch/NeoSim.js
This project will basically be the NeoVM.js (neo-vm on javascript) together with some external storage service that could provide storage access on any desired block, without needing to be a heavy node (so it will work on any browser). I believe this is safer than having RPC nodes to simulate invocations.

**Comment by dicarlo2** [comment]
@igormcoelho fyi: we've already implemented a full javascript (well, typescript) vm in neo-one that we've been using in production for over a year now.

**Comment by igormcoelho** [comment]
Good to hear that! I never found some vm codes on js, even recently looked at neo-one ,so I just assumed it has never been fully implemented. Im also reproducing application engine on js too... but I imagine you may also have that too. In this case, I reinforce that price calculation should be done on interfaces, not rpc nodes.

**Comment by shargon** [comment]
I like it, is the same behavior that i use in unit testing. We should be able to do that

**Comment by shargon** [comment]
Conflicts with SVM

**Comment by wowoyinwei** [comment]
I think it's very meaningful to be able to use CheckWitness in invokescript. This way we can get the specific gas to be consumed before sending the transaction and add the system fee accordingly.
There is a testMode parameter in ApplicationEngine.Run, but no actual effect is found. The parameter passed in and used defaults to be false. Have you considered using testmode for some methods in invoke, so that you can successfully execute the contract when you invoke it.

**Comment by vncoelho** [comment]
I will set this as a goal for NEO 3.0 because for 2.x it will surely not be merged.

In this sense, we can keep this discussion thinking in the new design for NEO 3.

**Comment by igormcoelho** [comment]
Very good idea @wowoyinwei . In fact, I always thought that was already the current behavior... hahahah it's always possible to improve things indeed :)  We are in another discussion for Neo 3, regarding what should be accepted for verification, and how to charge for it. But I believe it will be compatible with this proposal as well.

**Comment by lock9** [comment]
@wowoyinwei, do you need help with this? If you could rebase / fix conflicts, I think it is ready to merge.
This is very important, thanks!

**Comment by lock9** [comment]
@shargon we have to checkout to the branch and fix some issues. Is it possible for us to do that without having to wait for him? We made @trueinsider wait too much, it is understandable that he may have lost interest in it 😢

**Comment by shargon** [comment]
I will fix it soon

**Comment by shargon** [comment]
@lock9 you know my opinion, neo2 just for fix bugs

**Comment by gsmachado** [comment]
@lock9, @vncoelho, @igormcoelho, @shargon, guys:
I urge to have this on NEO2... 😃 
Ok, jokes aside, this is important for [neow3j](https://github.com/neow3j/neow3j/issues/69), other libraries, and maybe other apps. Given the timeline for NEO3, I would really do this for NEO2.

**Comment by lock9** [comment]
Well, you just used the words "user" and "complaining" in the same phrase, for me this is enough arguments why this should be implemented 😂 
@neo-project/core  I understand we don't want to make more releases, because (today) it is quite painful, however,  this code is quite short and does not introduce breaking changes.

**Comment by shargon** [comment]
We can do that

**Comment by gsmachado** [comment]
Any news on when this will be released on NEO2?

**Comment by shargon** [comment]
@gsmachado Please, could you create an issue?

**Comment by gsmachado** [comment]
@shargon: yes, I create [this](https://github.com/neo-project/neo/issues/1113) issue. Feel free to change the label or to ask further questions. 👍 😄

**Pull request merged**
