### PR TITLE
Change json fields to all lower case for consistency

### PR DESCRIPTION
**Pull request by joeqian10**
Close [#261](https://github.com/neo-project/neo-modules/issues/261).

### CODE REVIEW

**Comment by erikzhang** [comment]
We don't need the underlines `_`.

**Comment by shargon** [comment]
> We don't need the underlines _.

You don't like it in `camelCase`?

**Comment by erikzhang** [comment]
> You don't like it in camelCase?

In fact, I think some words look good in camelCase, some are not. Maybe we don't have to keep all json keys in a consistent style.

**Comment by roman-khimov** [comment]
> Maybe we don't have to keep all json keys in a consistent style.

Whatever that would be, please, let's keep it consistent across Neo.

I don't have any particular preference and I don't think there is any better or worse choice here, so it'd be quite natural for us to just minimize the amount of changes and mostly stick to the style already set by Neo 2 RPC. But be consistent. Code vs. documentation and various Neo subsystems against each other.

**Comment by Tommo-L** [comment]
Merge? It good for me, sine our NEP#ABI and NEP#Manifest all use lower case style.

**Comment by vncoelho** [comment]
@shargon, I prefer camelcase too and I share the same vision of not being against.

**Comment by Tommo-L** [comment]
😂 Okay, since most people like camelcase, could @joeqian10 help adjust them?

**Comment by joeqian10** [comment]
Personally I like all lower case too! I think PascalCase is even better than camelCase from the aesthetics view. @erikzhang @shargon @roman-khimov @vncoelho @Tommo-L If you are all ok with lower case (maybe it's not your favorite), then let's keep it and make other sub systems consistent, because I'm tired of discussing and changing this one more time. We have more meaningful issues to fix.

**Comment by vncoelho** [comment]
Ahahahahahaha this is already approved,lets merge this. In the future we do a complete change if necessary.

**Pull request merged**
