### PR TITLE
Add IWalletProvider

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by ZhangTao1596** [comment]
Nice wallet as a service.

**Comment by Qiao-Jin** [comment]
Will this plugin replace current wallet logic in neo-core, similiar to consensus plugin?

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
> Will this plugin replace current wallet logic in neo-core, similiar to consensus plugin?

I understand that it will be registered in `neo-node` in order to be consumed by neo-plugins

**Comment by Qiao-Jin** [comment]
Should this also be applied in RPCServer?

**Comment by erikzhang** [comment]
I don't think so. Rpc can only use the wallet that opened by rpc itself.

**Comment by vncoelho** [comment]
> I don't think so. Rpc can only use the wallet that opened by rpc itself.
Perhaps it is good to leave this note there for future explanation and discussions

**Pull request merged**
