### PR TITLE
[Minnor] SaveHeaderHashList after commit

### PR DESCRIPTION
**Pull request by vncoelho**
@erikzhang,
    I am not sure if this reversion makes sense. 
    It was proposed based on flow at OnPersist.

### CODE REVIEW

**Comment by vncoelho** [comment]
Maybe we should also call `UpdateCurrentSnapshot()`; after

```cs
                foreach (Block blockToPersist in blocksToPersistList)
                {
                    block_cache_unverified.Remove(blockToPersist.Index);
                    Persist(blockToPersist);

                    if (blocksPersisted++ < blocksToPersistList.Count - 2) continue;
                    // Relay most recent 2 blocks persisted

                    if (blockToPersist.Index + 100 >= header_index.Count)
                        system.LocalNode.Tell(new LocalNode.RelayDirectly { Inventory = block });
                }
                SaveHeaderHashList();
```

**Comment by vncoelho** [comment]
Can it be moved inside OnPersist?

**Comment by erikzhang** [comment]
I didn't see what the problem was solved by this modification, but it might cause some errors.

**Comment by vncoelho** [comment]
kkkkkkk, I agree.
It was created with the idea of following the same standard from `OnPersist` to the other cases where Headers are modified.

**Pull request closed without merging**
