### PR TITLE
Clean p2p plugin

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo-modules/pull/453#discussion_r554998802

### CODE REVIEW

**Comment by erikzhang** [comment]
Why?

**Comment by shargon** [comment]
It's not used in the plugin https://github.com/neo-project/neo-modules/pull/453/files#diff-6b717fd6b2562298139db22888a9992166602991e057e7f5c80c0f5be83619e7

**Comment by erikzhang** [comment]
But it could be used in other plugins. If we remove it, plugins have to reverify the inventories.

**Comment by shargon** [comment]
> But it could be used in other plugins. If we remove it, plugins have to reverify the inventories.

If they use the same mechanism they won't need to verify the inventories, only check the sender. I think that the logic should be the same.

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
