### PR TITLE
added "getpeers" RPC service

### PR DESCRIPTION
**Pull request by coranos**
updated code to Vistual Studio 2017.

added netcoreapp1.1; so that neo-cli can see the nuget package.

added a  "listpeers" RPC service that allows the neo-cli RPC service to return the list of connected, unconnected, and bad peers. This is useful in plotting the NEO network on a map, see:

https://coranos.github.io/neo/network/

### CODE REVIEW

**Comment by erikzhang** [comment]
The code is for vs2017 already, do we need to update it again?

**Comment by coranos** [comment]
It does not appear to be VS2017.
Format Version 12.00 is Visual Studio 2013, Format Version 15 is VS2017.

if the file isn't version 15, nuget package fails, and it mangles the target versions.

**Comment by erikzhang** [comment]
image

It's good for me to open it in vs2017 without modifying the .sln file.

**Comment by erikzhang** [comment]
Wait......Why should we separate leveldb implementation from Blockchain helper?

**Comment by coranos** [comment]
these commits should not be in the push request, i meant to only push them to my repo not push upstream to your repo.

leveldb doesn't work on OSX sierra. I've tried for three weeks to figure it out, it just saved the genesis block and nothing else.

The intention is to be able to use LiteDB instead of LevelDB on OSX (or some other pure .net framework), but that's well in the future.

**Comment by coranos** [comment]
The intention is to use leveldb on everything that possibly can, but since leveldb support on sierra is basically "compile from source, no we will not accept patches, just ignore the warnings" it's frustrating enough I'd like an alternative available.

I've completed the code changes, but want to test them first before pushing.

**Comment by coranos** [comment]
I've reverted to last good version before the push pollution.

if I open it in vs2017 without updating the .sln to vs2017, the target frameworks in neo.csproj get corrupted and I have to revert the file every time I build..

the line
    <TargetFrameworks>net461;netcoreapp1.1;netstandard1.6</TargetFrameworks>
changes to
    <TargetFrameworks>net20;netcoreapp1.1;netstandard1.6</TargetFrameworks>

**Comment by coranos** [comment]
btw, if you accept the main addition, I'll be willing to concede the point about upgrading to vs2017.

**Comment by erikzhang** [comment]
I will test it on macOS

**Comment by coranos** [comment]
I've backed out the OSX leveldb commits. Can you accept the "listpeers" RPC merge?

I'd prefer to treat the OSX leveldb as a separate push request.

**Comment by erikzhang** [comment]
I will accept it after you revert all other changes.

**Comment by coranos** [comment]
What changes have not been reverted?

**Comment by erikzhang** [comment]
Nothing is reverted in fact....

**Comment by coranos** [comment]
What do you mean "nothing is reverted"?
I see only 6 files changed.
neo.UnitTests.csproj, neo.sln, neo.csproj, updated to VS2017 so the code compiles in VS2017 on OSX.

LevelDBBlockchain.cs, LocalNode.cs, RpcServer.cs updated to add listpeers to RPC service.

So the only changes I have, and the changes to make the code compile and affs listpeers to the RPC service.

Can you be specific as to what you are seeing that you don't like?

I can't do much if all you say is 'nothing changed', as that's half a sentence. You need to say 'nothing changed, I expected file X to change'. Or better 'If you revert the changes in files X and Y I will accept the merge'.

I'm trying to be polite, as you are the code owner, but it's becoming very hard to communicate.

**Comment by coranos** [comment]
awesome :)
I have reverted the other changes.

**Comment by erikzhang** [comment]
That's better!
I have noticed that you got the connecting port from L244, but I think perhaps you need to get the listening port instead.
If this is true, you can make it by following the code at here:
https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L617

**Comment by jonatanblockchain** [comment]
What about "getlistpeers"? to follow APIs name

**Comment by coranos** [comment]
I'm listing the port and address of the remote.
RemoteEndpoint.Address
RemoteEndpoint.Port

The line you linked is:
Console.WriteLine($"{nodes[i].RemoteEndpoint.Address} port:{nodes[i].RemoteEndpoint.Port} listen:{nodes[i].ListenerEndpoint?.Port ?? 0} [{i + 1}/{nodes.Length}]");

So ListenerEndpoint.Port would just be 127.0.0.1 and 10333, right?

**Comment by erikzhang** [comment]
RemoteEndpoint.Port is the port which is used by remote for communicating with you.
ListenerEndpoint.Port is the port which is listened by remote for being connected.

**Comment by coranos** [comment]
ok, made the change.

**Comment by coranos** [comment]
sure, done.

**Pull request merged**
