### PR TITLE
[Core Plugin]  PR 3414 part 4. thread safe snapshot

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

Credits goes to chris. This is 4th part of pr 3414, it focus on providing a thread safe snapshot.

Fixes # #3414 

## Type of change

- [x] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jim8y** [comment]
This pr tries to be align with pr 3414, thus minor changes to the variable name that does not affect any functionality is applied to this pr as well.

**Review by shargon — COMMENTED** [review]
I think we should use the same pock for read

**Comment by cschuchardt88** [comment]
> I think we should use the same lock for read

Why do we need a lock on read? it's a snapshot.

**Review by cschuchardt88 — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by r41oliveira — COMMENTED** [review]
https://www.4betweb.com/?id=21593784&currency=BRL&type=4

**Pull request merged**
