### PR TITLE
allow client certificate to be checked on the RPC server

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by shargon** [comment]
The name could be easy spoofed, i think that should be the thumbprint or the publicKey

**Comment by erikzhang** [comment]
> The name could be easy spoofed, i think that should be the thumbprint or the publicKey

How to spoof?

**Comment by shargon** [comment]
When you create a new cert, you choose this information (autogenerated certs)

**Comment by erikzhang** [comment]
A self-signed certificate will fail at the time of certificate verification unless a trusted certificate authority is installed on the RPC server.

**Comment by shargon** [comment]
But this don't allow to regular user to use his own certificates, why don't use the signature and allow both, self-signed and trusted?

If is a whitelist i think should be better

**Comment by erikzhang** [comment]
I updated the code. Now it will verify the thumbprint of the authority, instead of the subject name of the client certificate.

**Pull request merged**
