### PR TITLE
Change fees to uint

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1459

### CODE REVIEW

**Comment by roman-khimov** [comment]
> I'm not so sure about system part

Or maybe it's even simpler than looking at birds, we have Neo 3 testnet and there are things like this there: https://scan.nel.group/neo3/transaction/0x59c6322bf2c8b6495b57c58583aef55ead98e63fb9f4321af964d72dd1724919

What it does is
```
0        PUSHDATA2    7b2267726f7.....
1224     PUSHDATA2    57020211240278....
7504     SYSCALL      System.Contract.Create (ce352c85)                                                                                                                                                                                                                                                                                                                                      
```
And given our current pricing 20 GAS for system fee is easily reached with 20K script + manifest to deploy.

**Comment by shargon** [comment]
with `uint` we have a maximum of 42 Gas

**Comment by Qiao-Jin** [comment]
If we want to import dynamic fee strategy maybe tx fee would exceed this limit.

**Comment by shargon** [comment]
> If we want to import dynamic fee strategy maybe tx fee would exceed this limit.

Agree

**Comment by erikzhang** [comment]
I don't think we will adjust the fee to be more expensive.

**Comment by shargon** [comment]
But if gas it's cheap, if we want to pay the same price we will need more gas to send the TX

**Pull request closed without merging**
