### PR TITLE
Optimize the wallet UT

### LINKED ISSUE #1485: Need to optimize wallet's UT for speeding up on github
**Summary or problem description**

Currently our UT takes a lot of time when running on github, we need to optimize the UT.

image

Here is [an example](https://github.com/neo-project/neo/pull/1483/checks?check_run_id=513102853)

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- UT

### PR DESCRIPTION
**Pull request by erikzhang**
Closes #1485

### CODE REVIEW

**Comment by vncoelho** [comment]
@erikzhang, perhaps it will not close #1485, but it looks better anyway.

image

**Comment by shargon** [comment]
Maybe we can remove culture UT, i am not sure if it's required...

**Comment by Tommo-L** [comment]
Could waiting for @Qiao-Jin , he also create a PR for optimizing the wallet UT.

**Comment by erikzhang** [comment]
> Maybe we can remove culture UT, i am not sure if it's required...

Agree.

**Comment by Tommo-L** [comment]
The execution order of culture UT is different from `donet test`. We need it, one more way to test.

**Comment by Qiao-Jin** [comment]
@erikzhang I pushed a pr to this branch which should optimize wallet tests furthermore. Main idea is to reuse created wallet data for the sake of time saving. But this PR acquire #1490 to be merged beforehand, as there are some problem in changing password currently.

**Comment by erikzhang** [comment]
We can merge this first.

**Comment by Qiao-Jin** [comment]
> We can merge this first.

Have consolved conflicits:)

**Pull request merged**
