### PR TITLE
add reset to iterator

### PR DESCRIPTION
**Pull request by Liaojinghui**
This pr implements https://github.com/neo-project/neo/issues/2644 the `reset` method for the iterator.

`reset` is supposed to be used to reset the iterator to its initial position.

### CODE REVIEW

**Comment by roman-khimov** [comment]
How this is better than just repeating the `Storage.Find` call from the contract?

To me, adding some interop is a significant change, so it better be done in two cases:
 * allowing to do something that couldn't be done before (an example from VM: neo-project/neo-vm#399)
 * providing substantially more effective way of doing the same thing (like neo-project/neo-vm#443)

I doubt this or #2637 are from either of these categories, they're easily done by the contract with existing interops, they have about the same GAS cost and execution overhead. Do we _really_ need it?

**Comment by Liaojinghui** [comment]
honest i have no idea, but i think it would be something of position setting instead of looping or looking. thank you for your comment, i will check the c# implementation for more detail.

**Comment by Liaojinghui** [comment]
Just checked the C# implementation, `reset` sets the index to -1

>Do we really need it?

I cant say we need it urgently, but apparently, we need it here https://github.com/neo-project/neo/pull/2637 to reset the iterator position.

**Comment by shargon** [comment]
It was tested in all engines? an enumerator doesn't need to retain in memory all the fetched items in order to allow the reset.

**Comment by Qiao-Jin** [comment]
> we need it here #2637 to reset the iterator position.

I suppose reseting to original position doesn't necessarily means reseting position to -1?

**Comment by Liaojinghui** [comment]
> I suppose reseting to original position doesn't necessarily means reseting position to -1?

I agree, it depends what shargon wants to achieve with count, I'll keep this pr open for now just in case.

**Comment by shargon** [comment]
Maybe better than `Count` we can create `ToArray` and return the result as an array?

**Pull request closed without merging**
