### PR TITLE
Add oracle InsufficientFunds code

### PR DESCRIPTION
**Pull request by Tommo-L**
it's used by https://github.com/neo-project/neo-modules/pull/326

### CODE REVIEW

**Comment by erikzhang** [comment]
If the fund is insufficient, the contract will fail to execute, right?

**Comment by Tommo-L** [comment]
> If the fund is insufficient, the contract will fail to execute, right?

Yes, but it'll still be packaged in  block.

**Comment by erikzhang** [comment]
If the request transaction failed to execute, there is no request be stored. Then this `OracleResponseCode` will never be used.

**Comment by Tommo-L** [comment]
The response transaction maybe be insufficientfund, like the data returned exceeds the size limit.
https://github.com/neo-project/neo-modules/pull/326/files#diff-37804ea315e32b33105846c7a13e577d4c35c56f10ce122db763c2b5a248581dR333-R337

**Comment by erikzhang** [comment]
> like the data returned exceeds the size limit.

That should be `ResponseTooLarge`.

**Comment by Tommo-L** [comment]
I think we need both, as the data may also exceed the current fee limit.

**Review by shargon — APPROVED** [review]

**Comment by superboyiii** [comment]
Ready to merge?

**Comment by erikzhang** [comment]
Should we add `ConsensusUnreachable`?

```
https://www.example.com/getrandom
```

**Comment by Tommo-L** [comment]
> Should we add `ConsensusUnreachable`?
> 
> ```
> https://www.example.com/getrandom
> ```

Yes, it should be added.

**Review by shargon — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
