### PR TITLE
Allow the committee to block a member from the committee

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by erikzhang** [comment]
@neo-project/core

**Comment by roman-khimov** [comment]
Seems somewhat weird, but blocked account is blocked account. If we have blocking/unblocking capability the policy should be enforced by all of the components.

**Review by shargon — APPROVED** [review]
I'm a little concern about how much time it could expend with a lot of registered accounts 

@superboyiii could you test it?

**Comment by ProDog** [comment]
When the committee block a consensus address, the next candidate will be added to become the next validators, but an error  after past 5 blocks, and no new blocks will be generated.

Before block member:
```
Candidates:
02eaf215286a48c2748bf74a49d204aedb3b8cf2e84aaea0a0c019d8c98a3ca3a7      5000000
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea      15000000
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0      30000000
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6      20000000
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1      10000000
```

```
Next validators:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1
```

After block member `03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6`:
```
Next validators:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1
02eaf215286a48c2748bf74a49d204aedb3b8cf2e84aaea0a0c019d8c98a3ca3a7
```

After 5 blocks, an error occurred:

0ca2878a982b83ba8feda44c4775c0d

**Comment by ProDog** [comment]
This is out of range. committees count was 5, it became 4 after block one.

868fa2eb7b3b0790cec18eae1e9c75d

**Comment by ProDog** [comment]
If the newly registered consensus address is blocked, everything is normal, the next committee becomes consensus, and the number of committees will not change.

Before block:
```
Candidates:
02c93fda004baccb675652854aae4543ccb5bb246714078bff48de2ac5368ff788      20000000
02eaf215286a48c2748bf74a49d204aedb3b8cf2e84aaea0a0c019d8c98a3ca3a7      5000000
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea      15000000
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0      30000000
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6      20000000
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1      10000000
```

```
Committee:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
02c93fda004baccb675652854aae4543ccb5bb246714078bff48de2ac5368ff788
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1
```

```
Next validators:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6
02c93fda004baccb675652854aae4543ccb5bb246714078bff48de2ac5368ff788
```


After block `02c93fda004baccb675652854aae4543ccb5bb246714078bff48de2ac5368ff788`:

```
Candidates:
02c93fda004baccb675652854aae4543ccb5bb246714078bff48de2ac5368ff788      20000000
02eaf215286a48c2748bf74a49d204aedb3b8cf2e84aaea0a0c019d8c98a3ca3a7      5000000
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea      15000000
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0      30000000
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6      20000000
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1      10000000
```

```
Committee:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1
02eaf215286a48c2748bf74a49d204aedb3b8cf2e84aaea0a0c019d8c98a3ca3a7
```

```
Next validators:
0357f0a6b00a17fea94f2205928c1ad745f6d6d013ad7b23ea2617b83e96e361ea
03950dcace27cf4093b16a5c7a23d5bbfcd3e6ac5a0d5c0204a219c232a6bd54a0
03e7565a5e9c20a638ac0f734f616ca05b6b35eb5e0a5e6f658dbb1832348ca4b6
03e95734dbea832081b60d92dd17d404ee1296bf53f9cd853eb309ee78c84476f1
```

**Pull request merged**
