### PR TITLE
Fix BinaryDeserialize

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/2530

### CODE REVIEW

**Review by erikzhang — APPROVED** [review]

**Comment by superboyiii** [comment]
@dusmart Is it OK for you?

**Comment by vang1ong7ang** [comment]
@superboyiii seems it works

**Comment by dusmart** [comment]
> @dusmart Is it OK for you?

Although I don't like too many limits, it fixed this issue effectively.

**Comment by superboyiii** [comment]
@erikzhang Merge?

**Pull request merged**
