### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by shargon** [comment]
> I remember I saw this some couple of days ago

I don't understand you @vncoelho. If you see an error, why we should wait other PR (not related to this) for include this changes?

I remember this PR from you https://github.com/neo-project/neo/pull/1167#issuecomment-544114558

image

You said that two PR, related to the same issue (renaming or comment) can not be joined because it comes from different ideas, and now this PR must be merged with other because it's small. I don't understand this ...

**Comment by erikzhang** [comment]
@shargon If you see the changes, you will understand it.

**Comment by shargon** [comment]
I don't, but it's ok for me, we can close it

**Comment by erikzhang** [comment]
image

**Comment by erikzhang** [comment]
image

**Pull request merged**
