### PR TITLE
Renaming RestartTasks to ConsensusTxsTask

### PR DESCRIPTION
**Pull request by vncoelho**
This also helps for understanding #1148 

@erikzhang, please consider this renaming. `RestartTasks` was a name hard to understand.
In fact, that class was just used at `ConsensusService`, which forces a restart of `global` and `knowhashes`

I believe that comprehension will improve with this.

### CODE REVIEW

**Comment by erikzhang** [comment]
t is not related to consensus.

**Comment by shargon** [comment]
Why you don't group it with https://github.com/neo-project/neo/pull/1162, two PR for renaming seems weird to me

**Comment by vncoelho** [comment]
They came separate idea, can be merged, but @erikzhang is saying it is not related to consensus. However, it is just used there nowadays.

I prefer to rename and if, in the future, we have other applications we create the tasks for them.

**Comment by vncoelho** [comment]
merged on #1162

**Comment by vncoelho** [comment]
@erikzhang, can you please check this again. I think that this is a good renaming. I closed the other PR because the recent PR https://github.com/neo-project/neo/pull/1183 will rename and improve its use.

**Comment by vncoelho** [comment]
@shargon, maybe I will reopen this branch in another PR.

**Pull request merged**
