### PR TITLE
VM - Jump table

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/2987

### CODE REVIEW

**Comment by shargon** [comment]
@Jim8y could you help me to fill the rest of the opcodes, with this change we can versioning the vm in `ApplicationEngine`, also the methods will me in different files, and I think that it will be faster than a big switch

**Comment by Jim8y** [comment]
Already in https://github.com/neo-project/neo/pull/3100

**Comment by shargon** [comment]
> Already being done in #3100

Is not the same, this is upgradeable, we can have one jumpTable per fork

**Comment by Jim8y** [comment]
then a bref explaination of how it work please, kinda weird for me.

**Comment by shargon** [comment]
> then a bref explaination of how it work please, kinda weird to me.

Ethereum works like that, basically, you have an array of 255 functions, each method is the logic of the opcode, this is stored in a class for example `JmpVM_Cockatrice`, if you have a different logic because you find a bug in the opcode PUSH1, the, you create a new object exactly like the previous one, but in this position `JmpTable[Opcode.PUSH1]` you set the new logic.

Then during the VM creation, you send the jump table that you want to use, so is easy to versioning each opcode, also, you avoid a big switch, because with the opcode, you know exactly the method that you must execute.

Reference: https://github.com/ethereum/go-ethereum/blob/master/core/vm/jump_table.go

**Comment by Jim8y** [comment]
how do we know when to use the new method when to use the old one? VM can not get access to the height

**Comment by shargon** [comment]
> how do we know when to use the new method when to use the old one? VM can not get access to the height

This is handle by `ApplicationEngine`

**Comment by shargon** [comment]
> how do we know when to use the new method when to use the old one? VM can not get access to the height

Let me refactor, because currently we need to do it without a new class

**Comment by Jim8y** [comment]
@AnnaShaleva please join the dicussion here

**Comment by shargon** [comment]
Follow in https://github.com/neo-project/neo/pull/3120 (@Jim8y you should have rights there)

**Pull request closed without merging**
