### PR TITLE
Fix plugin configuration falure

### LINKED ISSUE #1531: Failed to add json file when calling GetConfiguration()
**Describe the bug**
I tried to update the config file of `RpcServer` while neo-cli was running, but sometimes the neo-cli would throw exception and crash.
image

**To Reproduce**
1. start neo-cli.
2. change some settings in the config file of `RpcServer`, such as `DisabledMethods`, then save it.
3. most of the time, neo-cli will throw the exception and crash.

**Platform:**
 - OS: [e.g. Windows 10 x64]
 - Version
    neo-cli:               5a46401b3635b0f2f6a6b09141c20ea5ab361623
    neo:                    6eba2ee12d12b70d27181ff88f4ebf81550fe3ca 
    neo-vm:              f292fed3e9add32a2746e2c4cbb569d8dce6f25a
    neo-modules:     bbcfa56171a931c1c6f2b50f9289350dd7c052c0

**(Optional) Additional context**
It seems that the json file wasn't added successfully.
image
When debugging, if I set a breakpoint, then continue, the file can be added successfully and not throw an excepiton.
image

The issue was found when testing https://github.com/neo-project/neo-modules/pull/206

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #1531
Logs are added to show whether plugin config is loaded successfully or not.
@erikzhang @shargon

### CODE REVIEW

**Comment by erikzhang** [comment]
If we catch the exception here, we don't need to log, I think. Because it only ignore the exceptions that caused by the filesystem events.

**Comment by Qiao-Jin** [comment]
> If we catch the exception here, we don't need to log, I think. Because it only ignores the exceptions that caused by the filesystem events.

Have removed the log

**Comment by Tommo-L** [comment]
Coul we use [slf4j-NetCommonLogging](https://www.nuget.org/packages/slf4j-NetCommonLogging/) to log, which unified logging facade for .NET.  In java, most jar libraries use slf4j to log, which can be configed in user projects.

**Comment by cloud8little** [comment]
Test Passed.
Test Steps:
1. install neo-cli
2. install RpcServer; SystemLog; LevelDB
3. start neo-cli.
4. modify the config.json of Plugins/RpcServer, such as "Port": "10332", to "Port": "10333"
5. save the file.
No exception message print on the console, and neo-cli work as expected. Besides, the new changed port didn't work which thought it is reasonable.

**Pull request merged**
