### PR TITLE
fix wrong path

### LINKED ISSUE #1570: Plugin.Log will crash CLI
Plugin.Log will crash CLI if SystemLog plugin installed, as creating illegal file path will lead to system error:
98c5df3da85ec1d3bce3fd56d7804d3

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #1570

### CODE REVIEW

**Comment by erikzhang** [comment]
What's this?

**Comment by erikzhang** [comment]
I think the bug is in SystemLogs.

**Comment by shargon** [comment]
Maybe is not expected to be a path

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-modules/pull/222

**Pull request closed without merging**
