### PR TITLE
Include verification offset inside ScriptHash

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by shargon** [comment]
I will fix the UT after the review

**Comment by roman-khimov** [comment]
But why this or #1964? What's wrong with `verify` method having any kind of offset without affecting script hash?

**Comment by erikzhang** [comment]
We can extend NefFile to include the manifest, and then use the hash of the NefFile as the deployed contract hash.

**Comment by shargon** [comment]
Do you want a different hash for the same script?

**Comment by shargon** [comment]
We can create set the hash of the smart contract acording to the id

**Comment by erikzhang** [comment]
If the ABI changes, the function of the contract changes too. And you can get a different hash of a script by adding a `NOP` at the end.

**Comment by shargon** [comment]
and what happens if the user update the manifest only, it should migrate the hash?

**Comment by erikzhang** [comment]
> and what happens if the user update the manifest only,

He must upload a new nef file.

**Comment by shargon** [comment]
ok, I will create a new pr according to this

**Comment by erikzhang** [comment]
We can create multiple PRs. The first is to modifying NefFile to include the manifest.

**Comment by shargon** [comment]
Closed because there are a better solutions

**Pull request closed without merging**
