### PR TITLE
[**Part-1**] Added `ApplicationLogs` Unit Tests

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Change Log
 - Adding `Part-1` `ApplicationLogs` unit tests project template scaffold with a couple tests.
 - Added to `github` testing workflow

image

## Type of change

- [x] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jim8y** [comment]
xunit is better?

**Comment by cschuchardt88** [comment]
> xunit is better?

Millions times better, even Microsoft recommends you to use it over `NUnit` and `MsTest`

**Comment by Jim8y** [comment]
> > xunit is better?
> 
> Millions times better, even Microsoft recommends you to use it over `NUnit` and `MsTest`



> > xunit is better?
> 
> Millions times better, even Microsoft recommends you to use it over `NUnit` and `MsTest`

should we replace existing unit tests with it?

**Comment by shargon** [comment]
I think we should use the same, if we decide migrate it, its ok, but a mix is worse

**Comment by Jim8y** [comment]
For me i think it is OK to use either test engine. as long as it works. We dont have such rule of using same test engine before.

**Review by Jim8y — DISMISSED** [review]

**Review by vncoelho — COMMENTED** [review]
@cschuchardt88 

I am agree with the PR because it is PART - I, but there is almost no coverage at all...aehuahea

Could you try to use some command like "OnGetBlockCommand"? I think that by running such command in the UT we will be sure that the template is correctly designed for covering all tests later.

**Comment by cschuchardt88** [comment]
@vncoelho can we wait until part-2, found a bug I need to fix 1st.

**Comment by vncoelho** [comment]
I think there is too much little coverage and not a certain that the design will cover the tests in the future. Thus, it can be a pain to later remove your to change the model.

I would like to see at least a test that covers an used functionality as I mentioned above.

**Review by vncoelho — DISMISSED** [review]
Read my comments above.

As I mentioned, more tests are needed in my opinion in order to ensure that the design can attend the need.

**Comment by shargon** [comment]
> For me i think it is OK to use either test engine. as long as it works. We dont have such rule of using same test engine before.

We had only one, and now we are migrating it

**Comment by Jim8y** [comment]
> > For me i think it is OK to use either test engine. as long as it works. We dont have such rule of using same test engine before.
> 
> We had only one, and now we are migrating it

I dont like bother on non-functional problems, unless it can cause any real trouble.  test is test, as long as it works, its a solid test. what we should care about test is if it covers edge cases, instead of if it uses some specific framework.

**Comment by cschuchardt88** [comment]
@shargon 
otherwise I'll close.

@vncoelho This relates to what jimmy said https://github.com/neo-project/neo/pull/3346#issuecomment-2185373257

**Comment by vncoelho** [comment]
I think part 2 is needed, merge part 2 Into this branch and we add both together.

**Comment by cschuchardt88** [comment]
> I think part 2 is needed, merge part 2 Into this branch and we add both together.

I will start `part-2` ASPA

**Comment by cschuchardt88** [comment]
@vncoelho check to see if it suits you.

**Review by shargon — COMMENTED** [review]
Coverage decrease??

**Review by Jim8y — DISMISSED** [review]

**Review by shargon — DISMISSED** [review]

**Comment by superboyiii** [comment]
@cschuchardt88 Please resolve conflicts

**Comment by cschuchardt88** [comment]
@shargon @Jim8y need to re-approve

**Review by Jim8y — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by shargon — COMMENTED** [review]
Maybe we need to specify a new coveralls exclusion?

image

**Pull request merged**
