### PR TITLE
Fix extend consensus [2x]

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1799

### CODE REVIEW

**Comment by KickSeason** [comment]
Can you have a look my fix #1803

**Comment by shargon** [comment]
@KickSeason could you link the line of the fix?

**Comment by shargon** [comment]
@KickSeason I think that you say #1802 ?

**Comment by KickSeason** [comment]
> @KickSeason I think that you say #1802 ?

Yes #1802, sorry.

**Pull request closed without merging**
