### PR TITLE
Allow to create a Network map using private seeds

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1041

- A private seed cannot be retrive by RPC or by P2P message
- This allow to create a netowork topology

### CODE REVIEW

**Comment by shargon** [comment]
@neo-project/core any review?

**Comment by erikzhang** [comment]
I don't understand what it is for.

**Comment by shargon** [comment]
If we need to test some network scenarios for example
```
C1 connected to CN2 and CN3
and 
C4 only connected to C3
```
How can we do it?

**Comment by erikzhang** [comment]
Why we need this scenario? I don't understand.

**Comment by shargon** [comment]
Use cases:
- For testing purpose (when we had the fork problem, we need this and we had to work more because the lack of this feature).
- For testing some scenarios of distribution. for example in #1088, I know that it could be only beneficial if the backup CNs haven't got the TX that the primary is proposing, and they will ask for these transactions, how can i test this scenario without a network map?)
- For speed up CN without assume security risks (it could be possible to connect CN between them without expose this information to the network) usefull for private networks.

**Comment by cloud8little** [comment]
@shargon could you give more detail of user scenarios for this PR? I have a test on this, one single consensus node(P2P- 10003) and three external node(P2P - 40003, 30003, 10053), following show the configuration. 
When I set consensus node as the PrivateSeedList, I can't see the ip showing on command line, while others can still have a connection with this one.
I just don't understand how this apply to neo network.

屏幕快照 2019-12-10 下午3 31 04

**Comment by shargon** [comment]
maybe we should show the node in the list

**Comment by lock9** [comment]
Hi @shargon, can you solve the conflicts?

**Comment by shargon** [comment]
@lock9  If it will be implemented yes, but I think that is not decided.

**Comment by lock9** [comment]
No problem. I think we need to allow private seeds too. It is very common to receive a node IP address and it is not possible to connect to it.

**Comment by shargon** [comment]
If all are agree yes, I can do it.

**Comment by vncoelho** [comment]
I believe it is better to vote, because it is a feature that is not only focused on MainNet.
This kind of things are important for keeping NEO Ecosystem with top quality feature for Hybrid Chains.

**Pull request closed without merging**
