### PR TITLE
RPC call to get timestamp of last blocks

### PR DESCRIPTION
**Pull request by vncoelho**
With this call we gonna be able to get an array with the timestamps of the last `X` blocks, limited to 24 hours.

We believe it is an useful api call that can reduce load on RPCs and also be an easy way to get such information.

@shargon, can you give us a help in the security of this call?

### CODE REVIEW

**Comment by vncoelho** [comment]
Should we do an UT for this, @erikzhang?

**Comment by vncoelho** [comment]
@jsolman just suggested that we improve the getheaders for multiple blocks and a filter for specific fields. I think it would be better.

**Comment by jsolman** [comment]
It would be nice if you could use something like GraphQL to say what fields you want back; then for something like getting block headers you can say which fields you want. Then could request getting block headers for `x` blocks and specify you only want the timestamp returned for each.

**Comment by vncoelho** [comment]
Nice suggestion, @jsolman, it sounds like a good direction to go.

I think that for now it would be better to improve getheaders and a filter for timestamp, it would solve the necessity and open a path for these future generic queries.

**Comment by vncoelho** [comment]
@jsolman, I do not know if adapt `GetBlockHeader` will be a good choice now, it current supports `height` or `hash`.
Maybe a new RPC call is better for compatibility and simplicity.

**Comment by jsolman** [comment]
> @jsolman, I do not know if adapt GetBlockHeader will be a good choice now, it current supports height or hash.

Why would that matter, the height or hash would be of the first block to return. Then an additional optional parameter of number of  blocks to return after that height, and an optional parameter after that with an array of fields to return from each block. Probably it should limit to a max of 500 blocks or so.

**Comment by vncoelho** [comment]
That is true, @jsolman.
Do you prefer after the hash? I thought about return those before that hash.

**Comment by jsolman** [comment]
> Do you prefer after the hash? I thought about return those before that hash.

One could imagine a use case where one didn't have the hash of the last block. Probably better that it is the number or hash of the first block to be returned.

**Comment by erikzhang** [comment]
What's the difference between this and `getblockheader`?

**Comment by vncoelho** [comment]
The idea now is to merge this in the `getblockheader` with 2 additional parameter of number of blocks and fields, like this:

`private JObject GetBlockHeader(JObject key, bool verbose, uint nBlocks, JArray fields)`

What do you think?

**Comment by vncoelho** [comment]
we gonna move this to a plugin: `RpcMetrics`

**Pull request closed without merging**
