### PR TITLE
fix consensus 255

### PR DESCRIPTION
**Pull request by igormcoelho**
This is an alternative fix to: https://github.com/neo-project/neo/pull/706

Instead of adding a new field, it considers the view change value as a circular byte... so it allows us to set negative values as byte 255.

### CODE REVIEW

**Comment by vncoelho** [comment]
Veryyy naiiice, broda.

I prefer this one.
Is it better like this or should we make it optional and clean other calls yo makechangeview?

**Comment by igormcoelho** [comment]
@jsolman noticed a problem here... I cannot change values after signing... so ViewNumber must be passed as a parameter to the MakeSignedxx function.

**Comment by vncoelho** [comment]
ahauau, that is true.

**Comment by igormcoelho** [comment]
Just noticed everyone decided to go in this direction, so let's do that!

**Comment by vncoelho** [comment]
@erikzhang, @igormcoelho  and @jsolman,
please, double check this code.
I believe it is much more clean now! I removed any parameter that was being passed and not used.

This solution will be more safe and simpler I think.

@erikzhang, maybe we could open another PR with the changes to the `OnRecoveryRequestReceived` function.

**Pull request closed without merging**
