### PR TITLE
Change CalculateNetworkFee to be public

### PR DESCRIPTION
**Pull request by shargon**
Required for https://github.com/neo-project/neo-modules/issues/311#issuecomment-672779404

### CODE REVIEW

**Comment by erikzhang** [comment]
This looks weird. Why not use a `Wallet` object?

**Comment by shargon** [comment]
> This looks weird. Why not use a Wallet object?

There is no wallet in https://github.com/neo-project/neo-modules/blob/master/src/RpcClient/TransactionManager.cs

**Comment by ProDog** [comment]
RpcClient seem can't get singleton, at https://github.com/neo-project/neo/blob/master/src/neo/Ledger/Blockchain.cs#L81.
It is better to calculate networkfee only use Tx.

**Comment by erikzhang** [comment]
Then I think the best solution is to copy the code. We don't have to reuse all code.

**Comment by Tommo-L** [comment]
More than one place use it in neo-modules.

**Comment by shargon** [comment]
Maybe it's possible to create a dummy wallet and call it?

**Comment by ProDog** [comment]
> Maybe it's possible to create a dummy wallet and call it?

Anyone add that, please.

**Pull request closed without merging**
