### PR TITLE
Update & Consolidate nugets

### PR DESCRIPTION
**Pull request by shargon**
# Description

Updated and consolidated nuget packages.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] Compiling

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Just so you know. the version for microsoft `nuget` packages is based on the version of `dotnet`. So the `8.0.0` mean its `dotnet 8.0`. However when we convert to `netstandard2.1` the `API` may or may not change. Keep that in mind.

**Comment by shargon** [comment]
I receive the following warning:

`Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS9057	The analyzer assembly 'C:\Users\Fernando\.nuget\packages\akka.analyzers\0.2.1\analyzers\dotnet\cs\Akka.Analyzers.dll' references version '4.8.0.0' of the compiler, which is newer than the currently running version '4.7.0.0'.	Neo.Benchmarks	C:\Users\Fernando\.nuget\packages\akka.analyzers\0.2.1\analyzers\dotnet\cs\Akka.Analyzers.dll	1	Active
`

**Comment by cschuchardt88** [comment]
@shargon 

`Microsoft.CodeAnalysis` is a bit too restrictive in terms of the versions of the compiler tooling that it supports. I think the maintainers will want to target a version as low as feasibly possible.

Here's a mapping of the versions to VS versions to give an idea of where best to target:
https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022

**Comment by shargon** [comment]
@cschuchardt88 Thanks! I will update my VS to see if the error dissapear

**Comment by cschuchardt88** [comment]
@shargon but won't on github. `4.8.0.0` is for `Visual Studio 2022 version 17.8 (Preview)`

**Comment by shargon** [comment]
> @shargon but won't on github. `4.8.0.0` is for `Visual Studio 2022 version 17.8 (Preview)`

Then let's wait for update Akka.

**Review by vncoelho — APPROVED** [review]

**Review by vncoelho — COMMENTED** [review]
Here the compilation was fine, perhaps because of the version I used as well.

**Pull request merged**
