### PR TITLE
Allow for programmatic configuration of protocol settings in master-2.x branch

### PR DESCRIPTION
**Pull request by devhawk**
This PR is just #845 cherry-picked into the master-2.x branch + a minor change to the test (default magic is different between master and master-2.x branch). 

Note, this was originally PR #883. I had to do some branch cleanup in my fork which required closing that PR and opening a new one.

### CODE REVIEW

**Comment by lock9** [comment]
@neo-project/core  this is required for NGD Seattle. I know we don't want to update neo 2, but this is required for them to make progress

**Comment by devhawk** [comment]
@vncoelho, whatever tests you do on this PR can you also do on the master branch as well since this change is there already?

**Comment by vncoelho** [comment]
I am not still able to compile master, last time I tried some adjustments on neo-cli were still needed. I would need to check it again.

**Comment by vncoelho** [comment]
Current errors for neo-cli are:
```cs
Shell/MainService.cs(150,32): error CS1061: 'Wallet' does not contain a definition for 'FillTransaction' and no accessible extension method 'FillTransaction' accepting a first argument of type 'Wallet' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(158,42): error CS1061: 'Transaction' does not contain a definition for 'Gas' and no accessible extension method 'Gas' accepting a first argument of type 'Transaction' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Services/ConsoleServiceBase.cs(302,34): warning CS0168: The variable 'ex' is declared but never used [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(182,17): error CS0117: 'Transaction' does not contain a definition for 'Witness' [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(210,32): error CS1061: 'Wallet' does not contain a definition for 'FillTransaction' and no accessible extension method 'FillTransaction' accepting a first argument of type 'Wallet' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(260,20): error CS1061: 'Transaction' does not contain a definition for 'Witness' and no accessible extension method 'Witness' accepting a first argument of type 'Transaction' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(260,38): error CS1061: 'ContractParametersContext' does not contain a definition for 'GetWitness' and no accessible extension method 'GetWitness' accepting a first argument of type 'ContractParametersContext' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(300,20): error CS1061: 'Transaction' does not contain a definition for 'Witness' and no accessible extension method 'Witness' accepting a first argument of type 'Transaction' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(300,38): error CS1061: 'ContractParametersContext' does not contain a definition for 'GetWitness' and no accessible extension method 'GetWitness' accepting a first argument of type 'ContractParametersContext' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(747,41): error CS7036: There is no argument given that corresponds to the required formal parameter 'm' of 'Helper.IsMultiSigContract(byte[], out int, out int)' [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(903,55): error CS1503: Argument 2: cannot convert from 'Neo.Wallets.TransferOutput[]' to 'Neo.UInt160' [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(923,20): error CS1061: 'Transaction' does not contain a definition for 'Witness' and no accessible extension method 'Witness' accepting a first argument of type 'Transaction' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(923,38): error CS1061: 'ContractParametersContext' does not contain a definition for 'GetWitness' and no accessible extension method 'GetWitness' accepting a first argument of type 'ContractParametersContext' could be found (are you missing a using directive or an assembly reference?) [/opt/neoCli/neo-cli/neo-cli.csproj]
The command '/bin/sh -c dotnet publish /opt/neoCli/neo-cli/neo-cli.csproj -o neo-cli -c Release -r ubuntu.16.04-x64' returned a non-zero code: 1
EXITING AND NOT COPYING .ZIP Because last return was 1! Build probably had problems
```

**Comment by devhawk** [comment]
@vncoelho yes, this change was expressly designed to ensure backwards compatible behavior if ProtocolSettings.initialize is not called. Cant_initialize_ProtocolSettings_after_default_settings_used and Cant_initialize_ProtocolSettings_twice validate that protocol settings can't be changed after they've been initialized - regardless if they've been initialized by default or Initialize has been called.

**Comment by shargon** [comment]
@devhawk could you copy the optimizations in the neo3?  (if is not there)

**Comment by devhawk** [comment]
@shargon this change is already in master #845

**Pull request merged**
