### PR TITLE
Increase OracleResponse.MaxResultSize

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1981

### CODE REVIEW

**Review by Tommo-L — DISMISSED** [review]

**Comment by shargon** [comment]
Ready to merge?

**Comment by Tommo-L** [comment]
Ping

**Comment by Tommo-L** [comment]
related to https://github.com/neo-project/neo/pull/2048

**Comment by roman-khimov** [comment]
Yeah, it's quite trivial, let's merge it.

**Pull request merged**
