### PR TITLE
Fix LoadContract

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by ixje** [comment]
Can you describe the problem so other implementations can check if they have the same issue? Thanks

**Comment by erikzhang** [comment]
When a contract is upgraded, the running contract should keep the old version.

**Comment by ixje** [comment]
Thanks

**Comment by erikzhang** [comment]
For example:

```c#
public void upgrade(ByteString nef, string manifest)
{
    ContractManagement.Upgrade(nef, manifest);
    //Do something that requires CALLT.
}
```

**Pull request merged**
