### PR TITLE
Fixed `GetString` method on VM Types

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Description

The `Integer`, `Boolean`  type in the VM would use the default binary bytes of the `BigInteger` to output the string. My guess is they forgot to `override` the method in `Integer.cs` and `Boolean.cs`.

Now outputs the value of the integer. _For example_ if `Integer` is `1` then it outputs `1` as a `string`.

## Change Log

- Fixed `GetString` method on VM `Integer` and `Boolean` type

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
- [x] Locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cschuchardt88** [comment]
@shargon @Jim8y @AnnaShaleva  would this need to be a `hardfork`?

**Comment by Jim8y** [comment]
do we need it?

**Comment by shargon** [comment]
> do we need it?

It require a hardfork, and we have syscall for the conversion, we don't need it in my opinion

**Comment by cschuchardt88** [comment]
> > do we need it?
> 
> It require a hardfork, and we have syscall for the conversion, we don't need it in my opinion

But currently its returning invalid `string` as `ByteString` instead. Why not fix it. Because if we do `value.GetString()` it will return right value for `BigInteger`

**Comment by AnnaShaleva** [comment]
> Why not fix it.

If it causes a hardfork, then we can live without this fix, to me it just doesn't worth the hardfork.

**Comment by cschuchardt88** [comment]
What's the big deal with it being in the next hardfork? You want to keep invalid or bugged data on chain, than be my guess. Just ask yourself why is `neo` a ghostown. So I guess i should stop fixing the vm, since I can't get anywhere?

**Comment by shargon** [comment]
It can be fixed in the compiler

**Comment by cschuchardt88** [comment]
What about a plugins? or core itself. Compiler can't help there.

**Comment by shargon** [comment]
If GetString returns binary data with an Integer, compiler can fix it

**Comment by cschuchardt88** [comment]
But doesn't the vm use `StackItem.GetString()` for that syscall? This broken for boolean too.

**Comment by roman-khimov** [comment]
> invalid or bugged data on chain

It's not invalid. It's not bugged. It's just that this behavior doesn't meet your expectations. But this behavior is known and it exists for 3+ years of N3, there is a lot of code that is written relying on this behavior. This change will just break it. For what purpose? Does this change solve any problem that can't be solved in another way? No, int/string conversion can be handled otherwise. Can we live without it? Yes, easily. So why making this change?

**Comment by cschuchardt88** [comment]
Everyone wants to keep the behavior of not allowing data types to be converted to `string` properly for the vm. Instead they insist on users using the with native contract to convert to integers to `base2`.

**Pull request closed without merging**
