### PR TITLE
Remove StatesDumper - Minor Refactor on StorageDumper

### PR DESCRIPTION
**Pull request by vncoelho**
close https://github.com/neo-project/neo/issues/3271

### CODE REVIEW

**Comment by vncoelho** [comment]
@superboyiii @roman-khimov, I suspect that you are the ones that use this plugin.
I have been using StateDumper, but as I verified, StorageDumper was updated by @Ashuaidehao and it looks like you both are using StorageDumper.

In this case, I deleted StateDumper.

**Comment by Jim8y** [comment]
> @superboyiii @roman-khimov, I suspect that you are the ones that use this plugin. I have been using StateDumper, but as I verified, StorageDumper was updated by @Ashuaidehao and it looks like you both are using StorageDumper.
> 
> In this case, I deleted StateDumper.

My suggestion is DO NOT DELETE IT DIRECTLT, but mark it as [Obsolete]

**Comment by vncoelho** [comment]
> > @superboyiii @roman-khimov, I suspect that you are the ones that use this plugin. I have been using StateDumper, but as I verified, StorageDumper was updated by @Ashuaidehao and it looks like you both are using StorageDumper.
> > In this case, I deleted StateDumper.
> 
> My suggestion is DO NOT DELETE IT DIRECTLT, but mark it as [Obsolete], no matter there is someone using it or not, we should not just delete an existing thing without telling the eco-system and warn them.

Both plugins are the same @superboyiii.

There is no sense the leave DUPLICATED code here in the core.

As you will remember, perhaps you and @Ashuaidehao pushed the PR for `StorageDumper`

**Comment by Jim8y** [comment]
> I updated my last comment because I thought the message was from @superboyiii...aehuahea
> 
> There is no sense in what you said @Jim8y, you should check the code first. As I said above.

I am not saying you should keep duplicate code, what I mean is you should not delete existing thing directly. Its duplicated, but its also a neo product, a product should not be removed all of a sudden, but give a warning first, then remove later.

**Comment by Jim8y** [comment]
You can still do the same, i just suggest to do it latter, after one release. But i am ok if other coredevs think its fine.

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
I would suggest you write a readme to introduce the plugin.

**Comment by vncoelho** [comment]
> I would suggest you write a readme to introduce the plugin.

That a good idea. I will check how current Readme is.

**Comment by roman-khimov** [comment]
If they have the same functionally and one can be replaced with another then deletion is fine and it'd just be a release note --- "if you're using X, please use Y now". And it's not a very popular plugin, not RpcServer for sure.

We have a `SaveStorageBatch` setting in NeoGo (https://github.com/nspcc-dev/neo-go/blob/master/docs/node-configuration.md) that exports the same data and then we have https://github.com/nspcc-dev/neo-go/blob/master/scripts/compare-dumps/compare-dumps.go to compare dumps which we do from time to time (I hope we'll be doing it less often after #1526). From what I see here, the dump format stays the same, so it's perfectly fine for us.

**Review by shargon — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
