### PR TITLE
CheckWitness on invokescript (2.x)

### PR DESCRIPTION
**Pull request by meevee98**
Port of #1122 to 2.x

### CODE REVIEW

**Comment by melanke** [comment]
I made some quick review with meevee98, FYI the relevant changes are on RpcServer file, the other changes are only to prettify the code

**Comment by superboyiii** [comment]
Here's my test result:
I deployed an Nep5 contract, and set Checkwitness() in Transfer(). It works well on my neo-cli(command line) & RPC(sendfrom, sendtoaddress). Then I take out the script of tx into `Invokescript` and input my address scripthash.
image
```
{
  "jsonrpc": "2.0",
  "method": "invokescript",
  "params": ["0500e876481714ef29abc9496c14a9e93ea0d284bf712a197a849a14498c884f128f1c9ae705ff9b20ab17e6cb539c4c53c1087472616e7366657267a9db10bce155f113746be9f079f0906c64754c64f166", "4c9c53cbe617ab209bff05e79a1c8f124f888c49"],
  "id": 3
}
```
I find `checkWitnessHashes` hasn't been transferred into `GetInvokeResult()`.
image
image
image
Test result: [Fail]
@meevee98 You must modify your code.

**Comment by superboyiii** [comment]
You should make it like this:
```
case "invoke":
                    {
                        UInt160 script_hash = UInt160.Parse(_params[0].AsString());
                        CheckWitnessHashes checkWitnessHashes = null;
                        ContractParameter[] parameters = ((JArray)_params[1]).Select(p => ContractParameter.FromJson(p)).ToArray();
                        if (_params.Count > 2)
                        {
                            UInt160[] scriptHashesForVerifying = _params.Skip(2).Select(u => UInt160.Parse(u.AsString())).ToArray();
                            checkWitnessHashes = new CheckWitnessHashes(scriptHashesForVerifying);
                        }
                        return Invoke(script_hash, parameters, checkWitnessHashes);
                    }
                case "invokefunction":
                    {
                        UInt160 script_hash = UInt160.Parse(_params[0].AsString());
                        string operation = _params[1].AsString();
                        ContractParameter[] args = _params.Count >= 3 ? ((JArray)_params[2]).Select(p => ContractParameter.FromJson(p)).ToArray() : new ContractParameter[0];
                        CheckWitnessHashes checkWitnessHashes = null;
                        if (_params.Count > 3)
                        {
                            UInt160[] scriptHashesForVerifying = _params.Skip(3).Select(u => UInt160.Parse(u.AsString())).ToArray();
                            checkWitnessHashes = new CheckWitnessHashes(scriptHashesForVerifying);
                        }
                        return InvokeFunction(script_hash, operation, args, checkWitnessHashes);
                    }
                case "invokescript":
                    {
                        byte[] script = _params[0].AsString().HexToBytes();
                        CheckWitnessHashes checkWitnessHashes = null;
                        if (_params.Count > 1)
                        {
                            UInt160[] scriptHashesForVerifying = _params.Skip(1).Select(u => UInt160.Parse(u.AsString())).ToArray();
                            checkWitnessHashes = new CheckWitnessHashes(scriptHashesForVerifying);
                        }
                        return InvokeScript(script, checkWitnessHashes);
                    }
```
```
private JObject Invoke(UInt160 script_hash, ContractParameter[] parameters, CheckWitnessHashes checkWitness)
        {
            byte[] script;
            using (ScriptBuilder sb = new ScriptBuilder())
            {
                script = sb.EmitAppCall(script_hash, parameters).ToArray();
            }
            return GetInvokeResult(script, checkWitness);
        }

        private JObject InvokeFunction(UInt160 script_hash, string operation, ContractParameter[] args, CheckWitnessHashes checkWitness)
        {
            byte[] script;
            using (ScriptBuilder sb = new ScriptBuilder())
            {
                script = sb.EmitAppCall(script_hash, operation, args).ToArray();
            }
            return GetInvokeResult(script, checkWitness);
        }

        private JObject InvokeScript(byte[] script, CheckWitnessHashes checkWitness)
        {
            return GetInvokeResult(script, checkWitness);
        }
```

**Comment by meevee98** [comment]
I've updated the code 
@superboyiii could you test it again?

**Comment by devhawk** [comment]
In the future, can we avoid making unrelated formatting improvements in PRs like this? As far as I can tell, only one of the 26 files updated by this PR is related to the behaviour change. The other 25 appear to be whitespace formatting updates. That makes it much harder to review the PR.

**Comment by meevee98** [comment]
I've rebased this branch into the latest changes of master-2.x.
Could anyone review it, please?

**Comment by shargon** [comment]
Because in 2x there are no travis anymore, could you remove the format changes in order to make the review easier?

**Comment by meevee98** [comment]
Sure, no problem

**Comment by superboyiii** [comment]
@meevee98 @shargon  Compared the code with my last test version, no difference here. It's OK.
image

**Pull request merged**
