### PR TITLE
Plugin System

### PR DESCRIPTION
**Pull request by shargon**
This Pull Request allow to create a plugin library like that (related to https://github.com/neo-project/neo/issues/164)

* Log Plugin sample

```using Neo.Plugins;
using System;
using System.IO;
using System.Runtime.ExceptionServices;

namespace NeoFileLog
{
    public class NeoFileLogger : NeoLogPlugin
    {
        /// <summary>
        /// File path
        /// </summary>
        public string LogFilePath { get; set; }

        public override bool Load()
        {
            LogFilePath = Path.Combine(".", "log.txt");

            AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

            return base.Load();
        }
        public override void Unload()
        {
            AppDomain.CurrentDomain.FirstChanceException -= CurrentDomain_FirstChanceException;
            AppDomain.CurrentDomain.UnhandledException -= CurrentDomain_UnhandledException;

            base.Unload();
        }

        void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Log((Exception)e.ExceptionObject);
        }

        void CurrentDomain_FirstChanceException(object sender, FirstChanceExceptionEventArgs e)
        {
            Log(e.Exception);
        }

        public override void Log(Exception error)
        {
            if (error == null) return;

            Log(error.ToString());
        }

        public override void Log(string message)
        {
            try
            {
                lock (this)
                {
                    File.AppendAllText(LogFilePath, DateTime.Now.ToString() + " - " + message + Environment.NewLine);
                }
            }
            catch { }
        }
    }
}
```

> With this plugins is possible to log any action like that: ```NeoPlugin.BroadcastLog("Start " + string.Join(" ", args));```

* RPC Plugin sample

```using Neo.IO.Json;
using Neo.Plugins;

namespace NeoFileLog
{
    public class NeoRpcSample : NeoRpcPlugin
    {
        public override JObject RpcCall(NeoRpcPluginArgs args)
        {
            if (string.Compare(args.Method, "dummy") == 0)
            {
                args.Handle = true;

                JObject ret = new JObject();
                ret["dummyResult"] = true;
                return ret;
            }

            return null;
        }
    }
}
```

### CODE REVIEW

**Comment by AshRolls** [comment]
This code seems fine @shargon (though I haven't built and run it). We should move the actual plugin code into a new repo at CoZ and be careful to make sure .dll's are always built from source rather than distributed pre-compiled.

**Comment by fabwa** [comment]
https://github.com/CityOfZion/Neo-Plugins

**Comment by shargon** [comment]
I need a Readme magician @revett ^.^

**Comment by erikzhang** [comment]
Please give me a chance to review before it is merged.

**Comment by shargon** [comment]
I added the `UnloadAll` method

**Pull request closed without merging**
