### PR TITLE
Fix first contract id

### PR DESCRIPTION
**Pull request by shargon**
Now the fist Id it's 0, it should be 1

### CODE REVIEW

**Review by vncoelho — DISMISSED** [review]

**Comment by erikzhang** [comment]
I think maybe 0 should be the first.

**Comment by vncoelho** [comment]
I think that 1 sounds good because native starts with -1.

**Comment by vncoelho** [comment]
But either are good to me.

**Comment by shargon** [comment]
As @vncoelho said, we have <0 for native >0 for non native, 0 could be a default value to know that it's not stored.

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
