### PR TITLE
`[Typo]` Unit Tests - UT_ProtocolSettings.CreateHKSettings

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Description
Fixed a typo, in `UT_ProtocolSettings.cs`

## Type of change

- [ ] Optimization (the change is only an optimization)
- [x] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Unit Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by shargon — DISMISSED** [review]

**Review by AnnaShaleva — DISMISSED** [review]

**Review by Jim8y — APPROVED** [review]

**Comment by superboyiii** [comment]
@cschuchardt88 UT failed.

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
@cschuchardt88 again the ut fails

**Comment by cschuchardt88** [comment]
Looks like someone or something canceled it.

**Comment by superboyiii** [comment]
I just rerun the action. Seems when they run together, may have some influence on results.

**Review by shargon — APPROVED** [review]

**Review by Jim8y — APPROVED** [review]

**Pull request merged**
