### PR TITLE
Oracle: Transaction Version

### PR DESCRIPTION
**Pull request by belane**
Adds `TransactionVersion` for Oracles

### CODE REVIEW

**Comment by erikzhang** [comment]
#1515

**Comment by belane** [comment]
> #1515

This is only to be able to discrete different Oracle transactions and move forward.
The decision/implementation that is finally made in master will overwrite oracles branch.

**Comment by shargon** [comment]
The idea is:

- Normal Tx (Version.Normal)
- OracleRequest (Version.OracleRequest)
- OracleResponse (Version.OracleResponse and Attribute.DependOn)

@erikzhang Do you prefer to diference only with the attributes?

**Comment by erikzhang** [comment]
Either version or attributes, but not both. I prefer the version.

**Comment by shargon** [comment]
Understood, but if we use only the version, how can we attach the hash of the UserTx in the Oracle Response?

**Comment by erikzhang** [comment]
```c#
void Deserialize()
{
    if (Version.HasFlag())
    {
        //xxx
    }
}
```

**Comment by shargon** [comment]
Then... we will follow this pattern and Attributes will not be needed for oracles use cases.

**Pull request merged**
