### PR TITLE
Add features to manifest

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by roman-khimov** [comment]
Doesn't it duplicate `supportedstandards` field in some way? We no longer have "core" features like `Payable` or `HasStorage` and any new ones will probably be described in some new NEPs so if contracts are to support them they would also have some NEP-X in `supportedstandards`.

**Comment by erikzhang** [comment]
For example, I will allow `OnPersist` and `PostPersist` for non-native contracts.

**Comment by shargon** [comment]
> For example, I will allow OnPersist and PostPersist for non-native contracts.

We will need it?

**Comment by erikzhang** [comment]
> We will need it?

Maybe in the future? We need to reserve some extension space.

**Review by shargon — APPROVED** [review]

**Pull request merged**
