### PR TITLE
Neo-Core: fallback

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

This pr adds a fallback feature to the core. Such that when issues happen to the ledger, or we need to debug a certain block, we can fallback the ledger to that block.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Test Configuration**:
Build the core with condition #FALLBACK, then resync the whole ledger.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Maybe we should call the command `rewind blocks`?

**Review by roman-khimov — COMMENTED** [review]
Why do we need this in core? In an option that requires special compile flag? Likely a plugin can do the same, you can reuse `StatesDumper` (it's even possible to do this with the data set stored there as is, no extensions). And the best option of course is reusing MPT from `StateService`.

Notice also that this leaves plugin (token trackers, app logs) states as is.

**Comment by Jim8y** [comment]
> Why do we need this in core? In an option that requires special compile flag? Likely a plugin can do the same, you can reuse `StatesDumper` (it's even possible to do this with the data set stored there as is, no extensions). And the best option of course is reusing MPT from `StateService`.
> 
> Notice also that this leaves plugin (token trackers, app logs) states as is.

We can do this, we can do that, we can do with xxxxx, but how? Why do we need this? like as long as you dont debug a certain transaction or block in a certain state, you dont want to figure out why sync blocks in a certain height, why a transaction execution takes very long, you dont need to go back and forth among blocks, then you will never need it. But, thank you, i will try to figure out how to make it work with plugins.

**Comment by Jim8y** [comment]
No, plugins won't work. Still need to be in the core and cli.

**Pull request closed without merging**
