### PR TITLE
Optimize gas storage

### PR DESCRIPTION
**Pull request by shargon**
We can save bytes and serialization time with this optimization of Gas storage.

### CODE REVIEW

**Comment by erikzhang** [comment]
We need to make all NEP-5 tokens use the same storage structure, so that some programs do not need to start the virtual machine when reading the balance.

**Comment by roman-khimov** [comment]
> We need to make all NEP-5 tokens use the same storage structure

It probably should then be a part of the standard (and since NEP-5 couldn't really be changed, a new standard).

> some programs do not need to start the virtual machine when reading the balance.

I think it's especially relevant for MPT proofs, it's nice to have key-value pair presence confirmation, but if you can't reliably interpret the contents of value (and the meaning of the key), then it's not that useful. Standardized value format solves that.

Still, I like the patch, this wrapper does affect the performance and removing it would be nice. At the same time, if there really to be any standard for value format it should be prioritized over local optimizations.

**Comment by shargon** [comment]
Agree with @roman-khimov If we don't have a standard, any token will store the balance in the easier way, as bigInteger, maybe we should use two keys for neo, and store the balance like gas.

**Comment by erikzhang** [comment]
We need a standard.

**Comment by Tommo-L** [comment]
I think this is not to expand the NEP5 standard, but to expand the basic type of neo-VM. Define some specific variable types in neo-core, such as UInt160, UInt256, Balance, etc.

**Pull request closed without merging**
