### PR TITLE
Rename DBFT Settings

### PR DESCRIPTION
**Pull request by vncoelho**
Renaming in the same way as other plugins, such as `RpcServerSettings`

### CODE REVIEW

**Review by igormcoelho — APPROVED** [review]
Ok, better naming.

**Review by cschuchardt88 — APPROVED** [review]
This may break 3rd-party apps like `neo-express`. But good job. Changes like this for the better.

**Review by igormcoelho — CHANGES_REQUESTED** [review]
It seems all other call "Settings".... so maybe keep that way.

**Comment by vncoelho** [comment]
We are not sure if the change if fully correct, @cschuchardt88.

We just noticed that maybe we need to set a `Record` to be more compatible.

**Comment by cschuchardt88** [comment]
Just make a dupe `class` with `DBFTPluginSettings` that inherits `Settings`. Than mark `Settings` as obsolete. Keeping all parameters with `Settings`. Than any `public` properties or places with `DBFTPluginSettings`.

I think the `class` constructor is the only place for `Settings` class. So do above. but just create another constructor like 

```csharp
[Obsolete("use DBFTPluginSettings class")]
public ConsensusContext(NeoSystem neoSystem, Settings settings, Wallet wallet) { }

// new way
public ConsensusContext(NeoSystem neoSystem, DBFTPluginSettings settings, Wallet wallet) { }
```

**Comment by vncoelho** [comment]
I think this will not be a necessary change for now, @cschuchardt88 

Later we make this change

**Comment by cschuchardt88** [comment]
> I think this will not be a necessary change for now, @cschuchardt88
> 
> Later we make this change

We still need this in several plugins.

**Comment by vncoelho** [comment]
> > I think this will not be a necessary change for now, @cschuchardt88
> > Later we make this change
> 
> We still need this in several plugins.

I think that we can make the change to all plugins in the same PR, then we organize this correctly!

**Comment by vncoelho** [comment]
If you want to proceed with this in another PR it will be great.

**Pull request closed without merging**
