### PR TITLE
Debugging p2p master2x

### PR DESCRIPTION
**Pull request by vncoelho**
Draft for debugging (printing messages) on master-2x P2P protocolhandler,taskamanger and localnode.

This will not be merged. It is just a draft until we finish the issue hunting.

@lock9 @KickSeason @shargon

### CODE REVIEW

**Comment by shargon** [comment]
Could you use your own branch @vncoelho ?

**Comment by lock9** [comment]
@shargon  do you mean "his own fork"?

**Comment by lock9** [comment]
I wrongly pressed the `ready to review` 😢
How can I put this back to a draft? Sorry people!

**Comment by shargon** [comment]
Yes, his own fork

**Comment by vncoelho** [comment]
I will just close it for avoiding confusion.

Please leave the branch open for now.

**Pull request closed without merging**
