### PR TITLE
set block_receive_time after initialize

### PR DESCRIPTION
**Pull request by KickSeason**
fix block time always greater than TimePerBlock

### CODE REVIEW

**Comment by vncoelho** [comment]
No, time will be probably wrong.

**Comment by igormcoelho** [comment]
Do you think this will be correct @shargon ?

**Comment by shargon** [comment]
Yes, the difference is that we don't subtract the time wasted in the context initialization, is nothing critical, but why not?

**Comment by igormcoelho** [comment]
I'll check the unit tests.. because I think that block time is unset before persist.... so it will probably take garbage time on Initialize.

**Comment by shargon** [comment]
Yes, you are right, we need to initialize it first

**Comment by shargon** [comment]
mmm.... maybe we need a better mechanism for compute the span

**Comment by igormcoelho** [comment]
@shargon I think the really correct thing here is to take the time from the last block. This makes dbft timers deterministic.
I mean:
```cs
        private void OnPersistCompleted(Block block)
        {
            Log($"persist block: height={block.Index} hash={block.Hash} tx={block.Transactions.Length}");
            block_received_time = block.Timestamp;
            knownHashes.Clear();
            InitializeConsensus(0);
            
        }
```

However... we have to make sure this is recoverable after a possible crash.

**Comment by KickSeason** [comment]
yes, my change not works. 
so if always wait 15s, the reason blocktime now on mainnet is longer than before is that consensus process takes more time now, right?
we want to keep the block time as setted in protocol.json, we need a better mechanism for compute the span as Shargon said.

**Comment by shargon** [comment]
So, we will close it until find a better solution

**Comment by vncoelho** [comment]
@KickSeason, take a look at this previous draft and discussions:

https://github.com/neo-project/neo/pull/626

**Pull request closed without merging**
