### PR TITLE
Revert "Removed asp.net core"

### PR DESCRIPTION
**Pull request by shargon**
Reverts neo-project/neo#3065
Close https://github.com/neo-project/neo-modules/issues/862

### CODE REVIEW

**Review by vncoelho — COMMENTED** [review]
I will approve in a minute, I am just rebuilding my setup to ensure I did not made mistake when testing the error.

**Comment by cschuchardt88** [comment]
Just wait on this

**Comment by cschuchardt88** [comment]
Ill be adding to `neo-cli` instead, that will fix it

**Comment by vncoelho** [comment]
The fact is that without https://github.com/neo-project/neo-modules/commit/e9e7a07a3e170852b32784c5a48456c63fe55498 the module does not build.
But even with it is produces error when running, missing some dependencies. (it just occurs on nodes with RpcServer)

I forced added rpcserver published dlls into client (everything built with same framework and same environment), and still some errors.

**Review by vncoelho — APPROVED** [review]
With this broken all others PR can not be tested properly.

**Comment by cschuchardt88** [comment]
Plus in this introduces a new problem

**Comment by cschuchardt88** [comment]
> The fact is that without [neo-project/neo-modules@e9e7a07](https://github.com/neo-project/neo-modules/commit/e9e7a07a3e170852b32784c5a48456c63fe55498) the module does not build. But even with it is produces error when running, missing some dependencies. (it just occurs on nodes with RpcServer)
> 
> I forced added rpcserver published dlls into client (everything built with same framework and same environment), and still some errors.

YES THIS HAS TO DUE WITH `neo-cli`. and it will be fixed in a minute. Add this to `neo-cli` not `neo.dll`

**Comment by cschuchardt88** [comment]
btw if test are broken then github action test should be more thorough

**Comment by vncoelho** [comment]
https://github.com/neo-project/neo-modules/pull/864/files

**Comment by cschuchardt88** [comment]
Has to do with the host not targeting right framework

**Comment by vncoelho** [comment]
> > The fact is that without [neo-project/neo-modules@e9e7a07](https://github.com/neo-project/neo-modules/commit/e9e7a07a3e170852b32784c5a48456c63fe55498) the module does not build. But even with it is produces error when running, missing some dependencies. (it just occurs on nodes with RpcServer)
> > I forced added rpcserver published dlls into client (everything built with same framework and same environment), and still some errors.
> 
> YES THIS HAS TO DUE WITH `neo-cli`. and it will be fixed in a minute. Add this to `neo-cli` not `neo.dll`

Sure, if there is a good solution.

Just do not merge other PRs until we solve this.
I created another one on neo-modules in case this one is merged.
If not, let's just close it.

**Comment by vncoelho** [comment]
> Has to do with the host not targeting right framework

In the case I have here, as we discussed recently, we are targeting net7.0.
Building everything (neo-cli and modules) and publishing with `FROM mcr.microsoft.com/dotnet/sdk:7.0.404-jammy`

Running with `FROM mcr.microsoft.com/dotnet/aspnet:7.0.14-jammy`

**Comment by vncoelho** [comment]
I can try with another commands. The setup here is simple to modify, everything is one line command and dockerized.

**Comment by cschuchardt88** [comment]
has in host I mean the one running the process. In this case its `neo-cli` . Is it the same for you?

**Comment by cschuchardt88** [comment]
see #3067, close this.

**Comment by cschuchardt88** [comment]
Plus don't forget 12-hour waiting period before merge....

**Comment by vncoelho** [comment]
> Plus don't forget 12-hour waiting period before merge....

Plus, don't forget to push PRs that do not break everything...aehuahuea

**Comment by vncoelho** [comment]
The other  PR fixed, @shargon

**Comment by shargon** [comment]
@vncoelho this works with neo-node and neo-gui, and future clients, because plugins are used by neo, but you choose @vncoelho

**Comment by shargon** [comment]
> Has to do with the host not targeting right framework

The plugin is installed by the host, but is used by the framework, In my opinion, until we solve the dependency problem, we should revert it and find the good solucion

**Comment by cschuchardt88** [comment]
why not update the `exe` projects. It's only 3 lines of code.

**Comment by cschuchardt88** [comment]
I don't understand why we are moving backward here. You have no good reasons.

**Comment by shargon** [comment]
> You have no good reasons.

The other PR is not a fix, it moves the problem, the real problem is load the dependencies from the plugin folder, this only moves the problem to another place

**Comment by vncoelho** [comment]
@shargon ,I really appreciate your attention. 
But I am not expert in this libraries and frameworks to decide.

In fact,maybe revert is good decision.
As I understood, neo-cli needs its dll during execution. And plugins need aspnet framework for compilation. 

What is not clear to me is the image @cschuchardt88 is mentioning.

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
Wait a sec, if this is reverted, isn't it mean we still using core instead of standard? @cschuchardt88

**Comment by shargon** [comment]
> Wait a sec, if this is reverted, isn't it mean we still using core instead of standard? @cschuchardt88

We are trying to find the good solution

**Review by vncoelho — APPROVED** [review]
@shargon, too much instability on that other change. I am still not feeling safe to go.

The changes are requesting too much for the basic environment to build and run a simple client.

**Comment by cschuchardt88** [comment]
Its `RestServer` plugin its autoloading stuff it shouldnt

**Comment by cschuchardt88** [comment]
# AFTER TESTING EVERYTHING IS NO PROBLEMS!!! IT'S JUST USER ERROR!!!

**Comment by cschuchardt88** [comment]
@vncoelho 
image

**Comment by shargon** [comment]
We will fix exes or modules instead of neo

**Comment by cschuchardt88** [comment]
@shargon we need it in both

**Pull request closed without merging**
