### PR TITLE
Type cache

### PR DESCRIPTION
**Pull request by shargon**
I didn't found any build optimization for `release` when we used `typeof`

### CODE REVIEW

**Comment by erikzhang** [comment]
Does this optimize anything? Did you test it?

**Comment by shargon** [comment]
image

Half time, but very very very small optimization

**Comment by igormcoelho** [comment]
Man, these timers are amazing... I'm impressed such a thing could make a difference.

**Comment by shargon** [comment]
`sizeof` is optimized but `typeof` not..

**Comment by erikzhang** [comment]
10 million calculations are optimized for only 20 milliseconds. In this case I prefer to keep readability.

**Pull request closed without merging**
