### PR TITLE
Change max key length

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1472

### CODE REVIEW

**Comment by erikzhang** [comment]
Is there any scenario?

**Comment by Tommo-L** [comment]
> Is there any scenario?

If we want to use URLs as the key, we may face this restriction. Besides, increasing the length of the key has no bad effect on us.

**Comment by erikzhang** [comment]
Increasing the length of the key can significantly reduce search performance. So we must strictly limit the length of the key to the necessary range. For URLs, you can store the hashes of them.

**Comment by Tommo-L** [comment]
> Increasing the length of the key can significantly reduce search performance. 

As leveldb use `skiplist`, the time comlex of query operation is O(log(n)), I think it doesn't matter.

> For URLs, you can store the hashes of them.

Indeed it is somehow troublesome, just like we use C# `Dictionary`, where we need two `Dictionary` to have a complete `Dictionary` function.

**Comment by erikzhang** [comment]
https://github.com/google/leveldb#setup

As you can see, all performance report of leveldb is based on 16-byte keys. If you increase the length of the keys, performance will decrease.

The larger the key length, the lower the performance.

**Comment by Qiao-Jin** [comment]
> https://github.com/google/leveldb#setup
> 
> As you can see, all performance report of leveldb is based on 16-byte keys. If you increase the length of the keys, performance will decrease.
> 
> The larger the key length, the lower the performance.

I tried some tests on the relationship between key length & sequential reading:


key length(bytes) | seconds consumed per 10 million reads
-- | --
10 | 16.12296
20 | 18.80676
30 | 16.92695
40 | 16.21474
50 | 17.07611
60 | 17.66653
128 | 20.18627
256 | 22.40969
2560 | 51.1106

I think the time comlex of query operation is O(log(n)).

**Comment by erikzhang** [comment]
If it's for URLs, I think it's not enough. An URL can be more then 8000 bytes.

**Comment by Tommo-L** [comment]
I think 128 or 256 both are ok. But if you don't prefer,  it's ok for us to keep it.

**Comment by shargon** [comment]
Any decision?

**Comment by Tommo-L** [comment]
Ready to merge?

**Comment by erikzhang** [comment]
I prefer to keep the current value `64`. For URL scenarios, we can use short links.

**Pull request closed without merging**
