### PR TITLE
Dettaching Native NEP5 TState into separated keys

### PR DESCRIPTION
**Pull request by igormcoelho**
This is a draft implementation for https://github.com/neo-project/neo/issues/830

### CODE REVIEW

**Comment by shargon** [comment]
I like it, because is easier to extend in the future, but maybe is worst optimized because the key, the address, is duplicated

**Comment by igormcoelho** [comment]
If we put the byte as a suffix Shargon, it won't change space efficiency. 
Even if we don't put MPT hash in block header, we will eventually use MPT as storage, since it is optimized already for such cases.

Example: key abcdef1 and abcdef2 all share the same "path" ('abcdef'), so it doesn't matter how many suffixes you create, base key space is the same. But it's important that field options come as a suffix, not prefix.
Prefix can still be used for regular stuff, like Account marking, etc, since it's the first byte the be read, and may change the next ones to be read.

**Comment by erikzhang** [comment]
I think `Storage.Add` is useless. We can check fees without it.

**Comment by igormcoelho** [comment]
> I think Storage.Add is useless. We can check fees without it.

Ok Erik, I also think `Add` is a crazy shot.. but this change here is important with or without the `Add`... this is useful to simplify NEP-5 native code and allow garbage collection and template reutilization of Native NEP-5. When it comes to `Add` decision, then we think carefully if it's worth or not.

**Comment by igormcoelho** [comment]
Coming back to this when contract inheritance is available.

**Pull request closed without merging**
