### PR TITLE
Made `MemoryStore` the default whithout `config.json` for `neo-cli`

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Description
Made `MemoryStore` the default for `neo-cli` settings.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Test `config.json`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shargon** [comment]
I think that the default one should be persistent

**Review by vncoelho — COMMENTED** [review]
Usually we always use a config.json file @shargon 
I think that the config default can be kept as LevelDb and this one as MemoryStore

**Comment by shargon** [comment]
> Usually we always use a config.json file @shargon I think that the config default can be kept as LevelDb and this one as MemoryStore

It sounds reasonable that if it doesn't have config.json it won't be persistent, what do you think @Jim8y ?

**Comment by Jim8y** [comment]
Will it work at all? Cause the node will always have a config that sets leveldb by default. How to make it work? Delete the config file?

**Comment by shargon** [comment]
> The config.json should overwrite this default, @Jim8y. I still did not test the PR. Maybe other adjustments are needed.

@Jim8y ? xD

**Review by shargon — APPROVED** [review]

**Comment by Jim8y** [comment]
> The config.json should overwrite this default, @Jim8y. I still did not test the PR. Maybe other adjustments are needed.

What happend to my comments? this is not mine.....@shargon

**Comment by vncoelho** [comment]
I just reverted the edit

**Comment by vncoelho** [comment]
image

image


It worked in .devcontainer by just deleted the specification from config.json

**Review by vncoelho — APPROVED** [review]

**Comment by shargon** [comment]
> > The config.json should overwrite this default, @Jim8y. I still did not test the PR. Maybe other adjustments are needed.
> 
> What happend to my comments? this is not mine.....@shargon

I didn't remove anything...

**Comment by cschuchardt88** [comment]
I think we should have `config.json` but have the others and just let people pick switch one they want.

**Pull request merged**
