### PR TITLE
Redefine Opcode.Equal price for ByteString

### LINKED ISSUE #1855: Should redefine price of OpCode.EQUAL
**Summary or problem description**

OpCode.EQUAL can be a system vulnerability due to current fee model.

This is because of the definition of func [ByteString.Equals:](https://github.com/neo-project/neo-vm/blob/8e1c3b8525cba101eaa1154f11b4fb064aba8eb2/src/neo-vm/Types/ByteString.cs#L21)
image

After testing it shows that 900,000 execution of opcode sequence { LDARG0, LDARG1, EQUAL, DROP } between 2 1048,576-sized ByteStrings will exhaust 100 seconds while cost only 3.44 GAS.

**Do you have any solution you want to propose?**

We should redefine the price of OpCode.EQUAL depending on the size of compared objects.

Or, maybe we should run the sequenceEqual in parallel?

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- OpCode & price model
- VM

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #1855 
After balancing, running Opcode.Equal for type ByteString will cost 10 Gas per second.

### CODE REVIEW

**Comment by Qiao-Jin** [comment]
Should we modify the price of Opcode.EQUAL/NOTEQUAL?

**Comment by erikzhang** [comment]
I think there are two options. The first is to increase the cost of `EQUAL/NOTEQUAL`, and the second is to reduce the value of `MaxItemSize`. Since `EQUAL` is a very commonly used command, I think reducing the value of `MaxItemSize` is a better option.

Vote:

1. Increase the cost of `EQUAL/NOTEQUAL`. 👍
2. Reduce the value of `MaxItemSize`. ❤

**Comment by shargon** [comment]
Reduce `MaxItemSize` to 512 it's good for me

**Comment by Qiao-Jin** [comment]
As long as MaxItemSize is lower than 5000 I think is OK. Then even in worst cases (equal / nonEqual between ByteString) average price will be higher than 10 Gas/second during persisting.

**Comment by erikzhang** [comment]
If we limit `MaxItemSize` to `65535`, it consumes almost 1 GAS per second. This fits the design exactly.

**Comment by shargon** [comment]
I prefer to reduce it to `ushort.MaxValue` rather than throw an exception in a specific opcode.

**Comment by roman-khimov** [comment]
Maybe it's just me, but 64K seems to be so low... Though compared to other potential solutions it's not *that* bad, at least it's simple and fair. And if we're to add some VM versioning it could even be changed in the future if need be.

**Comment by erikzhang** [comment]
> Maybe it's just me, but 64K seems to be so low...

I also think so. There may be some scenarios that require larger `StackItem`s. So my idea is to allow 1MB `StackItem`s, but only `StackItem`s smaller than 64KB support `EQUAL` and `NOTEQUAL`.

Just like this:

https://github.com/neo-project/neo-vm/blob/e3f1584b1953dcc13075a57803240858c8a480de/src/neo-vm/Types/ByteString.cs#L28-L32

Only if the size is less then `Integer.MaxSize`, it can be converted to `bool`.

**Comment by shargon** [comment]
> Just like this:
https://github.com/neo-project/neo-vm/blob/e3f1584b1953dcc13075a57803240858c8a480de/src/neo-vm/Types/ByteString.cs#L28-L32
Only if the size is less then Integer.MaxSize, it can be converted to bool.

It have sense.

**Comment by erikzhang** [comment]
See https://github.com/neo-project/neo-vm/pull/367

**Pull request closed without merging**
