### PR TITLE
fix DataCache functions have inconsistent behaviour

### LINKED ISSUE #1186: DataCache functions have inconsistent behaviour
`TryGet()` and `GetOrAdd()` sometimes allow modifications of the returned item to be persisted to the real backend and other times not. 

Screenshot 2019-10-24 at 12 55 20
Screenshot 2019-10-24 at 12 55 47

For example; scenario 1 of the `GetOrAdd` table can be caused by
1. first having a`TryGet().scenario 6` (key not in cache, but in real db)
2. first having a `GetOrAdd().scenario 6` (key not in cache, but in real db)

**What is normal in C#?**
Let's first look at standard C# behaviour. `TryGetValue()` on a dictionary. 

The item returned can be modified and _will_ persist in the actual dictionary.

```C#
StorageKey key = new StorageKey { ScriptHash = UInt160.Zero, Key = new byte[] { 1 } };
StorageItem item = new StorageItem { IsConstant = false, Value = new byte[] { 0x1 } };

Dictionary<StorageKey, StorageItem> dictionary = new Dictionary<StorageKey, StorageItem>()
{
    {key, item }
};

// get and modify value
dictionary.TryGetValue(key, out StorageItem retrieved);
retrieved.Value = new byte[] { 0x2 };

// check if stored value was changed. True means by reference 
dictionary.TryGetValue(key, out StorageItem retrieved2);
Console.WriteLine(retrieved.Value == retrieved2.Value); // prints True
```

So for C# devs it should be natural that a `TryGet()`  like function allows to modify content, right? 

**Proposal**
I want to propose that all variants can modify the database. This can be done as follows.

Change the code for `TryGet().scenario6` 
https://github.com/neo-project/neo/blob/cd85039a1e9a671f1a5ca0f93087b6de2606febe/neo/IO/Caching/DataCache.cs#L278
to
```C#
State = TrackState.Changed
```
Now it behaves the same as the current `GetOrChange()` implementation for that scenario.

Next we can simplify both `GetOrAdd()` and `GetOrChange()` to re-use existing code as follows
```C#
public TValue GetAndChange(TKey key, Func<TValue> factory = null)
{
    TValue value = TryGet(key);
    if (value != null) return value;
    if (factory == null) throw new KeyNotFoundException();
    value = factory();
    Add(key, value);
    return value;
}

public TValue GetOrAdd(TKey key, Func<TValue> factory)
{
   return GetAndChange(key, factory);
}
```

Results:
* less and simplified code
* consistent and deterministic behaviour without having to know function internals and keep previous calls to the same cache in mind
* more inline with how C# standard library functions work

### PR DESCRIPTION
**Pull request by ixje**
fix #1186

### CODE REVIEW

**Comment by erikzhang** [comment]
I don't think these changes are correct...

**Comment by ixje** [comment]
@erikzhang can you be more explicit what part you think is incorrect about it? 

1. This PR makes is so that all functions in _all scenarios_ allow persisting to the real backend (as suggested in #1186). 
2. The `keyCount` values are different because `TryGet()` no longer produces `NONE` state trackables and thus in some scenarios we have an additional trackable returned from `GetChangeSet()`
3. Because of point 2 the implementations of `GetOrAdd()` and `GetAndChange()` can be simplified by reusing existing code.

**Comment by erikzhang** [comment]
Let's say we have a contract doing the following steps:

```
TryGet(key1)
TryGet(key2)
......
TryGet(key100)
GetAndChange(somekey)
```

It reads 100 entries, and update 1 entry. If we allow both `TryGet()` and `GetAndChange()` to persist data, we need to write to disk 101 times on commit. So we need `TryGet()` to keep entries being `TrackState.None` so that we write to disk only once on commit.

**Comment by ixje** [comment]
I agree it will attempt to modify 101 entries (assuming LevelDB doesn't do anything smart if it sees no changes). However, we need to keep in mind that everything is put into a `WriteBatch` and disk I/O happens only once when calling `Commit()` on the snapshot, not 101 times.
https://github.com/neo-project/neo/blob/cd85039a1e9a671f1a5ca0f93087b6de2606febe/neo/Persistence/LevelDB/DbCache.cs#L51-L54

My fear is that there is a security issue lurking around the corner because some people believe `TryGet()` is always read only. Example (https://github.com/neo-project/neo/issues/855#issuecomment-505071175):
> Because anything that you do with TryGet never will be committed, with GetAndChange, your changes will be applied

and this is not true as shown in this table (case 1 + 6)
Screenshot 2019-10-24 at 12 55 20
and the code example here: https://github.com/neo-project/neo/issues/855#issuecomment-505330855

**Comment by shargon** [comment]
What about if we use a different dictionaries for caching `TryGet` (readonly) and the others?

**Comment by ixje** [comment]
Option B, a copy would streamline the behaviour in all situations. 

Alternatively, an optional `read_only` parameter could be added. Then make `TryGet` results persistable by default, which is also how C# dictionaries work (for `TryGetValue`), and which also allows to re-use and simplify the code following this PR.

**Pull request closed without merging**
