### PR TITLE
Remove Callback APIs

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by erikzhang** [comment]
We don't need callback APIs if we have #2169.

**Comment by vncoelho** [comment]
we still would like to use some kind of callback like opeval.
Let's see.

**Comment by shargon** [comment]
If we remove the callbacks, we remove the possibility of doing lambda functions.

**Comment by erikzhang** [comment]
We have `Pointer`.

**Comment by erikzhang** [comment]
Go?

**Comment by shargon** [comment]
We need to remove this line first

https://github.com/neo-project/neo-vm/blob/defb2371d9a6a032bdea94e0c8b903a4729c9152/src/neo-vm/ExecutionEngine.cs#L298

But a I am worry about share pointers. How we will be isolated?

**Comment by erikzhang** [comment]
> We need to remove this line first

Why should we remove this line? The `Pointer` should be used in the same contract only.

**Comment by shargon** [comment]
But then, how can we use a contract library with a method as an argument?

**Comment by erikzhang** [comment]
> But then, how can we use a contract library with a method as an argument?

You can send the method name to it, just like what we did in Oracle contract.

**Review by shargon — APPROVED** [review]

**Pull request merged**
