### PR TITLE
Move to monorepo: Neo.Cryptography.BLS12_381

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/Neo.Cryptography.BLS12_381/issues/13

- Source copied from https://github.com/neo-project/Neo.Cryptography.BLS12_381.
- File headers was added.

### CODE REVIEW

**Comment by Jim8y** [comment]
@cschuchardt88 can you please check if this is the latest?

**Review by Jim8y — APPROVED** [review]

**Comment by shargon** [comment]
> @shargon do you mind to add an action that will run its unit test if C# code of this project is changed?

Currently we run all the ut always

**Comment by cschuchardt88** [comment]
> @shargon do you mind to add an action that will run its unit test if C# code of this project is changed?

Test are ran by solution https://github.com/neo-project/neo/blob/ff989a9c909ec7de57a0e86383f868ecd99e4630/.github/workflows/main.yml#L33

**Comment by cschuchardt88** [comment]
@shargon Everything checks out

**Comment by shargon** [comment]
We can optimize the workflow in a different PR

**Comment by cschuchardt88** [comment]
I replied to wrong to person. It was meant for @Jim8y

**Pull request merged**
