### PR TITLE
Remove mpt

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Move MPT to [neo-modules#410](https://github.com/neo-project/neo-modules/pull/410)
https://github.com/neo-project/neo-modules/pull/408#issuecomment-733545689

### CODE REVIEW

**Review by erikzhang — APPROVED** [review]

**Comment by shargon** [comment]
How it will be used as a plugin? as new `Storage`?

**Comment by Tommo-L** [comment]
plugin

**Comment by shargon** [comment]
We will have the message in the core and the logic in modules?
If we allow plugins to send his message should be signed by the commitee.

**Review by vncoelho — APPROVED** [review]

**Comment by Tommo-L** [comment]
> If we allow plugins to send his message should be signed by the commitee.

Indeed

**Review by shargon — APPROVED** [review]

**Pull request merged**
