### PR TITLE
Implement Runtime.CheckMultiWitness

### LINKED ISSUE #834: Multiple Witness Checking (Neo 3)
One useful feature, already proposed for Neo 2 (https://github.com/neo-project/neo/issues/700 but now not in schedule for implementation) is the ability to check multiple witness in a "multisig" format. This gives flexibility to Witness scripts, at the same time it allows composition in a "multisig" manner.

Using this, each consensus node could be itself a MultiSig contract, or any other verification mean, and still make part of a global multisig contract.

Example:

Witness A (scripthash1):
```
PUSH64 signature1
PUSH33 pubkey1
SYSCALL Neo.Crypto.CheckSig
```

Witness B (scripthash3):
```
PUSH64 signature3
PUSH33 pubkey3
SYSCALL Neo.Blockchain.GetHeight
PUSH 300000
GT # timelock contract... only release after height 300000
THROWIFNOT
SYSCALL Neo.Crypto.CheckSig
```

Witness C:
```
# 2/3 multi witness
PUSH20 scripthash1
PUSH20 scripthash2
PUSH20 scripthash3
PUSH3 # n
PUSH2 # m
SYSCALL Standard.Runtime.CheckMultiWitness
```

This should pass, because we require 2/3 witness, and scripthash1 and scripthash3 will be fulfilled :)

### PR DESCRIPTION
**Pull request by igormcoelho**
closes #834

### CODE REVIEW

**Comment by erikzhang** [comment]
Please do not implement proposals that have not been discussed. 😂

**Comment by igormcoelho** [comment]
> Please do not implement proposals that have not been discussed.

Sometimes is easier to express in coding than in text ;) hahahha but it's just a reference, we can close it.

**Comment by vncoelho** [comment]
Beautiful, @igormcoelho, this is a powerful and important feature.
The explanation and details in #834 are clear, good examples.
I believe that we should move in this direction and make this a standard.

**Comment by vncoelho** [comment]
This is a good standard to have, @igormcoelho, for being efficient we could also have a search for deployed verification's.
Then, we would not need to provide all verifications at the same time.

**Comment by igormcoelho** [comment]
Closing this now, pehaps come back in the future.

**Pull request closed without merging**
