### PR TITLE
Catch exception on UPNP that cause socket problem when reconnecting after network fail

### PR DESCRIPTION
**Pull request by vncoelho**
Commenting lines that cause socket problems on reconnecting and, consequently, blocks chain sync of some nodes.

### CODE REVIEW

**Comment by vncoelho** [comment]
Closed until further verification.

**Comment by vncoelho** [comment]
Reopened because even in normal operation the Discover loop is not passing from this line:
https://github.com/neo-project/neo/blob/60a02eedc156a66e3955340f0024026f32d296f6/neo/Network/UPnP.cs#L44

Exception are always being catch.

**Comment by vncoelho** [comment]
Maybe it is because port 1900 was already used by the system and closed incorrectly.
Let's try some random port and check if problem finishes as well.

**Comment by vncoelho** [comment]
Problem still persists in all my tests, it needs some refinement, I do not know exactly what these lines do, @erikzhang.

**Comment by erikzhang** [comment]
They are udp messages used to communicate with the router and request port mapping, and should be independent of the problem you describe.

**Comment by erikzhang** [comment]
@vncoelho Can you test it again?

**Comment by shargon** [comment]
I agree with @erikzhang , this messages could not produce this errors

**Comment by vncoelho** [comment]
Thanks, @erikzhang. I just tried again and the error just disappear by catching the exception, @erikzhang.
Nice catch... aheuaheuaea

@shargon, I also do not understand it completely.
I think that It should something related to an internal queue of the Operational System TCP layer.
As @erikzhang mentioned, this is used to communicate with the router, which probably lost connection and reconnected with new variables. I do not know exactly, I never worked with this before.

By the way, when is WebSocket currently used?
```cs
            if (ws_port > 0)
            {
                ws_host = new WebHostBuilder().UseKestrel().UseUrls($"http://*:{ws_port}").Configure(app => app.UseWebSockets().Run(ProcessWebSocketAsync)).Build();
                ws_host.Start();
            }
```

**Comment by shargon** [comment]
I prefer to use generic catch, not just catch `SocketException`

**Comment by vncoelho** [comment]
@erikzhang, I changed to generic exception, but if you want a more precise catch fell free to roll back to `SocketException`

**Comment by erikzhang** [comment]
> By the way, when is WebSocket currently used?

WebSocket is used for browser-type nodes, which allow nodes to communicate with each other through the WebSocket.

**Pull request merged**
