### PR TITLE
`[Change]` Neo Version to `3.8.0`

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Change Log
 - Changed `VersionPrefix` to `3.8.0` in `./src/Directory.Build.props`

## Type of change

- [ ] Optimization (the change is only an optimization)
- [x] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jim8y** [comment]
No. 3.8.0 will not be like this.

**Comment by shargon** [comment]
We don't want to release 3.8 now

**Comment by cschuchardt88** [comment]
This is for `myget`, `github` nuget repos. We working on `3.8.0` right? Than if best to update version, so version is `3.8.0-CI6523896` in those repos

**Comment by cschuchardt88** [comment]
People don't know how to versioning works

**Pull request closed without merging**
