### PR TITLE
Unit Test for Ledger Module

### PR DESCRIPTION
**Pull request by eryeer**
This PR contains two parts:
1. unit test for Ledger Module
2. fix files cleaning up in Wallets Module

### CODE REVIEW

**Comment by erikzhang** [comment]
@eryeer I think you should create a new branch from `neo-project:master` and create pull request from it, instead of creating PRs from your `master`.

image

**Comment by eryeer** [comment]
@erikzhang OK, I will create a new PR from another branch instead of my master branch.

**Comment by erikzhang** [comment]
And I suggest you better re-fork your repo, because your master branch is different from ours. 😂

**Comment by eryeer** [comment]
OK

> And I suggest you better re-fork your repo, because your master branch is different from ours. 😂

OK😂

**Pull request closed without merging**
