### PR TITLE
Reserve 4 bytes for NefFile

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
Maybe we can reserve more, 16 or 32

**Comment by erikzhang** [comment]
> Maybe we can reserve more, 16 or 32

I think 4 bytes are enough. Because each byte can be extended to a `varint`.

**Comment by shargon** [comment]
I will update dev-pack after merge it

**Comment by shargon** [comment]
If we will add a methods table, is not better to add this table instead of this reserved bytes (or both)?

**Comment by erikzhang** [comment]
Replaced by #2185

**Pull request closed without merging**
