### PR TITLE
Update notary branch

### PR DESCRIPTION
**Pull request by ZhangTao1596**

### CODE REVIEW

**Comment by Liaojinghui** [comment]
@shargon  Can you please rebase this pr to the latest master branch, too many changes that does not belong to this pr

**Comment by Liaojinghui** [comment]
@shargon how are we gonna do with this branch? if we create a momorepo, this branch will be useless?

**Comment by shargon** [comment]
> @shargon how are we gonna do with this branch? if we create a momorepo, this branch will be useless?

We will start with the mono repo only with neo-vm first. Notary still under discussion, it has only 6 votes in the community votes.

**Comment by AnnaShaleva** [comment]
This branch contains a lot of code, it is hard to maintain and review. At the same time we have https://github.com/neo-project/neo/issues/2895, https://github.com/neo-project/neo/issues/2896 and https://github.com/neo-project/neo/issues/2897, thus I'd suggest to close this PR and try to implement Notary functionality step-by-step, because it's always more easy to deal with a small set of changes (@roman-khimov loves it). If needed, some code may be just ported from this PR.

**Comment by vncoelho** [comment]
@shargon, maybe this PR should be merged and open a new one from notory to master.

**Comment by shargon** [comment]
2022, I think that should be closed, and design notary in a different one (if someone are interested in)

**Comment by Jim8y** [comment]
Close this pr as inactive. Open only if you are going to maintain this pr.

**Pull request closed without merging**
