### PR TITLE
Move `ReferenceCounter` to an interface

### PR DESCRIPTION
**Pull request by shargon**
# Description

First step of https://github.com/neo-project/neo/issues/3517

- Move `ReferenceCounter` to an interface

## Type of change

- [X] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shargon** [comment]
What do you think @neo-project/core ? if we push an item, we call Add, if we pop a item, we call remove, same for Compound items, and when a pop is done in a compound item, we call Remove also.

In this way, we have a better system, the worst, two same stack items, will be counted as two, but we will be faster, and we can increase the limmit

**Comment by Jim8y** [comment]
> What do you think @neo-project/core ? if we push an item, we call Add, if we pop a item, we call remove, same for Compound items, and when a pop is done in a compound item, we call Remove also.
> 
> In this way, we have a better system, the worst, two same stack items, will be counted as two, but we will be faster, and we can increase the limmit
> 
> sample [b50ab91](https://github.com/neo-project/neo/commit/b50ab912db0d7fc1c150928631b07cad8470e592)

but pop and push are very classical name for operations on stack~~~~

BTW, how about name the referencecounter as something like referencecounter with GC, or GC referencecounter,,,,

**Comment by vncoelho** [comment]
> What do you think @neo-project/core ? if we push an item, we call Add, if we pop a item, we call remove, same for Compound items, and when a pop is done in a compound item, we call Remove also.
> 
> In this way, we have a better system, the worst, two same stack items, will be counted as two, but we will be faster, and we can increase the limmit
> 
> sample [b50ab91](https://github.com/neo-project/neo/commit/b50ab912db0d7fc1c150928631b07cad8470e592)

Sure, @shargon

Let me discuss this internally here and soon reply with more ideas. Next Monday at least before merging this one.

**Comment by igormcoelho** [comment]
It's very nice to have a clear interface on ReferenceCounter. Congratulations @shargon .

**Review by Jim8y — APPROVED** [review]

**Pull request merged**
