### PR TITLE
Rename committee to council

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close https://github.com/neo-project/neo/pull/2152#issuecomment-745791046

### CODE REVIEW

**Comment by Qiao-Jin** [comment]
After merging this one corresponding changes are needed in neo-node, neo-modules & neo-devpack-dotnet.

**Review by vncoelho — APPROVED** [review]
Good choice.

**Review by shargon — APPROVED** [review]
I prefer to merge this after preview4, otherwise we never end

**Comment by erikzhang** [comment]
I thought about it again, I think maybe we shouldn't rename it. Because we once had a NEO council, it might cause confusion.

**Comment by Tommo-L** [comment]
>  we once had a NEO council

It seems, we've never used this organization before, and it doesn't even exist anymore?

**Comment by erikzhang** [comment]
https://www.google.com/search?q=neo+council

**Comment by Qiao-Jin** [comment]
Closed due to name confusion.

**Pull request closed without merging**
