### PR TITLE
Fix p2p connection

### PR DESCRIPTION
**Pull request by Tommo-L**
fix [#1123](https://github.com/neo-project/neo/issues/1123)

It's also need @superboyiii  to review.

### CODE REVIEW

**Comment by yongjiema** [comment]
@vncoelho @Tommo-L  Seems like should let the `Peer.MaxConnectionsPerAddress` to handle it.

**Comment by yongjiema** [comment]
@vncoelho @Tommo-L I think we can separate the connected peers for remote and local, and let `A` send a already connected message to `B` before disconnected, then `B` knows should connect `A` or not.

**Comment by Tommo-L** [comment]
@yongjiema  In actually, B already knows that A was connected.

Assumption:  A, B all listen 40333 port.  A's ip is `192.168.1.a`, B's ip is `192.168.1.b`

Step1:  A -- connecting ------> B. 
A will use a different port not 40333(eg 123456) to connect B.  Then B will have a `192.168.1.a:123456` node in B's remote nodes list.

Step2: A <-- send vesion payload --> B
A and B both will send `VersionPayload` message to each other attached with `NodeCapability`, which contains the listener port 40333(not 123456).  Therefore, B knows that A(`192.168.1.a:40333`) has already connected, and don't have to connect A again.

My solution is to add the `192.168.1.a:40333` node in B's connected list.

**Comment by yongjiema** [comment]
@Tommo-L It's not enough from `NodeCapability`, a address `A` may have multiple `NodeCapability` which contains the listener port 40333, `B` doesn't know which one is it for now.

**Comment by Tommo-L** [comment]
> a address `A` may have multiple `NodeCapability` which contains the listener port 40333


Sorry, do you mean, node A can have multiple `NodeCapability` with different listener port 40333 and other port?

**Comment by yongjiema** [comment]
> > a address `A` may have multiple `NodeCapability` which contains the listener port 40333
> 
> Sorry, do you mean, node A can have multiple `NodeCapability` with different listener port 40333 and other port? Then node B dosen't know which one is it for now.

A address `A` can have multiple nodes (e.g. `A1`, `A2`, `A3` etc...), each node can have a `NodeCapability` which contains the listener port 40333.

**Comment by Tommo-L** [comment]
But for B, connect one of those nodes is enough. 
And it dose not effect the other nodes(e,g. A2, A3,... etc) to connect B. 
It only effect B, not to connect the others actively.

**Comment by yongjiema** [comment]
But it cannot ensure `B` connects to the expected node, for example, `A1` connected to `B`, but `B` actually want to connect to `A2` which is for the address `A` maps the port 40333.

**Comment by Tommo-L** [comment]
> But it cannot ensure `B` connects to the expected node, for example, `A1` connected to `B`, but `B` actually want to connect to `A2` which is for the address `A` maps to the port 40333.

This case also exists in current situation. For B, it's impossible to distinguish A1, A2, and..., except for one-by-one connecting.

**Comment by yongjiema** [comment]
> > But it cannot ensure `B` connects to the expected node, for example, `A1` connected to `B`, but `B` actually want to connect to `A2` which is for the address `A` maps to the port 40333.
> 
> This case also exists in current situation. For B, it's impossible to distinguish A1, A2, and..., except for one-by-one connecting.

But `B` can know the expected node `A2` have connected or not.

**Comment by Tommo-L** [comment]
😂 A1, A2,...,  all share the same `IP:Port`, they only way to distinguish them is `VersionPayload`. Whether B connects Ai or Ai connects B, `VersionPayload` will be sent, which can be distinguished for B.

**Comment by Tommo-L** [comment]
merged by PR#1154

**Pull request closed without merging**
