### PR TITLE
GitHub Contribution Guide 

### PR DESCRIPTION
**Pull request by lock9**
Hello, 
I created a github contribution guide based on our github tags.
I hope this helps new developers to join our ecosystem.

Please review it here, otherwise you won't be able to see the images:
https://github.com/simplitech/neo/blob/contributing/CONTRIBUTING.md

Edit: Credits to Grace who helped me improve this

### CODE REVIEW

**Comment by lock9** [comment]
Hello, 
Please do not merge this yet, I want to use high-resolution images (I will see if it is possible).

**Comment by shargon** [comment]
It is planned to add the coding style rules?

**Comment by igormcoelho** [comment]
@lock9 I think this is an opportunity to "teach" a little bit of git and github plataform too.

I still struggle sometimes to make things right, so this is my personal guide (I never found on internet!).

To contribute on Neo Project via GitHub, it is recommended to follow these steps:
1) fork neo project on your own repo (let me call you `john`)
2) clone your own neo project fork locally using ssh (with write access): `git clone git@github.com:john/neo.git`
3) add upstream neo project locally using https (not ssh, to prevent direct write access): `git remote add upstream https://github.com/neo-project/neo.git`
4) add each of your development colleagues (let me call her `mary`) locally using ssh (to allow write access): `git remote add mary git@github.com:mary/neo.git`

That's ready to go! Every time you need to sync your own fork, you can do (working on `master` here):
1) `git checkout master`
2) `git pull upstream master` (updates from neo)

If you are collaborating on `mary`'s branch PR (called `feature-mary`), you can do this:
1) git fetch mary
2) git checkout feature-mary
3) add commits... and `git push` (this will automatically send updates via mary PR, not neo upstream)

@shargon @lock9 @vncoelho if you have a better way, please let me know...

**Comment by lock9** [comment]
@igormcoelho I think it is good to have some guidance, but more like "GitHub vs private repositories" (the need to create a fork, sending a PR from your repo, etc.).
I think that people who are totally new to development can't help us, there is no need to adjust our message for this public.

I think that some "forking instructions"  and "how to send a PR" may be helpful, but I don't think we need a "git guide" in our document.

**Comment by lock9** [comment]
Guys, please wait for one more change too:
2 reviewers must approve the code before someone can merge it (Neo 3)
3 reviewers must approve the code before someone can merge it (Neo 2)
I will add this (improved) in this doc.
@igormcoelho  I will also add basic fork & send PR instructions. Do you think that is enough?

**Comment by lock9** [comment]
I've updated it to add a reference to this link: https://opensource.guide/how-to-contribute/#opening-a-pull-request and also added the reviewers rule.

**Comment by igormcoelho** [comment]
In fact, I dont know if its useful to others rsrs its useful to me at least :)

**Comment by erikzhang** [comment]
Where are the pictures used?

**Comment by vncoelho** [comment]
I think it is good to have this file you proposed, @lock9, `CONTRIBUTING.md`, as well as the guidelines.


It is used like this, @erikzhang: https://github.com/simplitech/neo/blob/contributing/CONTRIBUTING.md

**Comment by igormcoelho** [comment]
> Where are the pictures used?

To represent each colored tag,and its meaning. If you click on the .md Vitor sent above, you'll see,its beautiful.

**Comment by lock9** [comment]
@igormcoelho  I understand that it is not easy to use git. There are a lot of features that I don't know and I often do things incorrectly.
The only reason I didn't add "complete instructions" is because I think this document is not meant to teach git, I think that the real motivation here is meant to show how to contribute to neo, not learn Git.
The URL I added shows how to fork and send a PR, because this is the "real difference" between using private and a public repository.

**Comment by lock9** [comment]
I'm merging this because after the 2 approvals I only fixed some typos.

**Pull request merged**
