### PR TITLE
Upgrade `System.Text.RegularExpressions` to fix vulnerability

### PR DESCRIPTION
**Pull request by nan01ab**
# Description

Compiling with net9.0:
There is a compile warning:
```
/neo/tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj : warning NU1903: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by cschuchardt88 — APPROVED** [review]

**Review by Jim8y — APPROVED** [review]

**Comment by roman-khimov** [comment]
I'd be better to fix https://github.com/neo-ngd/neofs-api-csharp/issues/8 properly.

**Comment by shargon** [comment]
> I'd be better to fix [neo-ngd/neofs-api-csharp#8](https://github.com/neo-ngd/neofs-api-csharp/issues/8) properly.

Me too

**Comment by shargon** [comment]
We can fork the api to this repository if it's not maintained

**Comment by nan01ab** [comment]
> We can fork the api to this repository if it's not maintained

`neofs-api` no update long time.

**Comment by shargon** [comment]
@Jim8y could you ping someone of @NGDAdmin ?

**Pull request merged**
