### PR TITLE
Make some class public to plugin

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Make `ByteArrayEqualityComparer ` `StoreDataCache ` `StoreMetaDataCache ` public to use in https://github.com/neo-project/neo-modules/pull/414.

### CODE REVIEW

**Review by shargon — DISMISSED** [review]

**Comment by erikzhang** [comment]
Can you copy the code of `ByteArrayEqualityComparer`?

**Comment by ZhangTao1596** [comment]
> Can you copy the code of `ByteArrayEqualityComparer`?

Make `StoreDataCache` `StoreMetaDataCache` public and copy `ByteArrayEqualityComparer `?

**Comment by erikzhang** [comment]
Yes.

**Comment by ZhangTao1596** [comment]
> Yes.

Will do.

**Comment by ZhangTao1596** [comment]
> Yes.

Done.

**Review by shargon — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
