### PR TITLE
Fix #1834

### PR DESCRIPTION
**Pull request by shargon**
We need to ensure that all the indexes can fit in LastSeenMessage, if we use a integer type, we have the half available chain.

Also, if heigh it's 0, `LastSeenMessage?.Count(p => Block.Index > 0 && p.Value < (Block.Index - 1)) ?? 0;` it will produce an integer overflow, and the condition always will be true.

### CODE REVIEW

**Comment by erikzhang** [comment]
`uint` is better?

**Comment by shargon** [comment]
Yes, it's better, but the consensus UT use -1, we can fix the UT and change to uint

**Comment by shargon** [comment]
The problem is that ConsensusService use Blockchain.Singleton and it has 1 Height. So it can't meet this UT https://github.com/neo-project/neo/blob/ca13358151113f1c11a744529e3e1ea2e80dea6b/tests/neo.UnitTests/Consensus/UT_Consensus.cs#L169-L180

**Comment by shargon** [comment]
I think that now it's better, because if `LastSeen` doesn't contain the pubKey, it will be counted as failed.

**Comment by erikzhang** [comment]
Test need to be fixed.

**Pull request merged**
