### PR TITLE
Incentive release storage

### PR DESCRIPTION
**Pull request by doubiliu**
Payback when destory contract

### CODE REVIEW

**Comment by erikzhang** [comment]
What's your plan?

**Comment by doubiliu** [comment]
I discussed with @Tommo-L  .We think that after the contract was destroyed, the sender could be given an incentive, which would encourage users to actively delete expired contracts on the chain and free up storage space.Incentives are returned 1: 1 in stored byte size.Of course, this is based on the system fee being burned. This is also mentioned in #278.

What‘s your opinion? @erikzhang

**Comment by erikzhang** [comment]
I don't think it is necessary to give users incentive to destroy the contracts. In the future, we can adopt a lease model: the owner needs to pay rent periodically to extend the life of his contract. If there is no renewal, the contract will be destroyed automatically.

**Comment by doubiliu** [comment]
'destroyed automatically'  mmmmm,it is also a good idea. 
This means that when the block is persisted, it is necessary to check and release the expired contract, which may consume certain resources.At the same time we need to add renewal interfaces and account models.I think we should open an issue to discuss

**Pull request closed without merging**
