### PR TITLE
Drop the duplicate NewTasks for the TaskManagerMailbox (2x)

### PR DESCRIPTION
**Pull request by yongjiema**

### CODE REVIEW

**Comment by vncoelho** [comment]
Great @yongjiema, I will work on this PR for us to be sure all duplication is finished.

We need this for protocol handler also, I think.

Lets make the title of the PR more generic.

**Comment by shargon** [comment]
It was tested in the previous Pull request, was splitted...

**Comment by lock9** [comment]
@shargon I will remove my request for changes, but I need to understand better the rules we have for the reviewers. I thought we had to test every PR before approving it, but without UT, there is no way to test it (except some cases where we use neo-cli).

**Comment by vncoelho** [comment]
No @shargo, look all my comments (ahauahah, I know it was too much). This did not solve the duplicated problem, check those logs.

I am still not in favor of this merge, in particular, after all experiments that were carried on.

I am going to focus on this, I agree with this merge when we really detect a difference in duplicated tasks. My experiments did not show that.

**Comment by vncoelho** [comment]
@yongjiema, I am opening other minor fix in another PR.

Give me 2-4 more days because I just want to be 99% sure that this is a needed fix.

**Comment by vncoelho** [comment]
@erikzhang,

who calls `OnRelay` of `RemoteNode.cs`:
```cs
        private void OnRelay(IInventory inventory)
        {
            if (Version?.Relay != true) return;
            if (inventory.InventoryType == InventoryType.TX)
            {
                if (bloom_filter != null && !bloom_filter.Test((Transaction)inventory))
                    return;
            }
            if (inventory.InventoryType == InventoryType.Consensus)
            {
                Console.WriteLine($"OnRelay(RN): {inventory.Hash}");
            }
            EnqueueMessage("inv", InvPayload.Create(inventory.InventoryType, inventory.Hash));
        }
```

The main source of the problems is the huge amount of calls of this OnRelay, which triggers a big queue of on its scope and, consequently, various calls of `OnInvMessageReceived` at `ProtocolHandler`, which, also consequently, calls a lot of `system.TaskManager.Tell(new TaskManager.NewTasks`.

**Comment by vncoelho** [comment]
@shargon, @igormcoelho, @erikzhang, @yongjiema,

I think that the main source of the problem has been found!!!!

```cs
        internal readonly RelayCache RelayCache = new RelayCache(100);
```

This Cached is very small and is causing the request of the same consensus multiple and multiple times!

**Comment by vncoelho** [comment]
In fact, this RelayDirect is just rebroadcasting to the Connections of the network, right?

**Comment by vncoelho** [comment]
```cs
TM-ShallDrop: Droping message Neo.Network.P2P.TaskManager+NewTasks Block Neo.UInt256[]
TM-ShallDrop: Droping message 0xb1654fb940d2da5702bf780213bfc3e38baf82e6466a4b808f1354c8e88c0d50
OnRelay(RN): 0x26eeb2582a272f4f117821ed489bda38debceef3a9993ce07c108eb67adc7548
OnRelay(RN): 0x48872dc58d5875f2ed93af2f4ab218f1f5c8087faee4b0bbfc8e9009dec0afd1
OnRelay(RN): 0x26eeb2582a272f4f117821ed489bda38debceef3a9993ce07c108eb67adc7548
OnRelay(RN): 0x48872dc58d5875f2ed93af2f4ab218f1f5c8087faee4b0bbfc8e9009dec0afd1
OnRelay(RN): 0x26eeb2582a272f4f117821ed489bda38debceef3a9993ce07c108eb67adc7548
OnRelay(RN): 0x48872dc58d5875f2ed93af2f4ab218f1f5c8087faee4b0bbfc8e9009dec0afd1
OnRelay(RN): 0x26eeb2582a272f4f117821ed489bda38debceef3a9993ce07c108eb67adc7548
OnRelay(RN): 0x48872dc58d5875f2ed93af2f4ab218f1f5c8087faee4b0bbfc8e9009dec0afd1
[23:59:55.721] relay block: height=6 hash=0xb1654fb940d2da5702bf780213bfc3e38baf82e6466a4b808f1354c8e88c0d50 tx=1
```

It is working also for `blocks`

**Comment by vncoelho** [comment]
and it is also working nice for `consensus`

OnInvMessageReceived(PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-1906654075-1565309258: 0xfc24939bc65e9d8e0103d9614f9d399d236e67ddca6830cc3af2bc7558ca9292
      printingHashesFiltered(PH)-1906654075-1565309258: 0xfc24939bc65e9d8e0103d9614f9d399d236e67ddca6830cc3af2bc7558ca9292
TM-IHP: Consensus I AM...
OnInReceive-OnInvMessageReceived(PH):
OnInvMessageReceived(PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-1633004902-1565309258: 0x2e3376034c8d04c58e168c919c69c0b0f337da3109c87a6ad586dddba3979cfa
      printingHashesFiltered(PH)-1633004902-1565309258: 0x2e3376034c8d04c58e168c919c69c0b0f337da3109c87a6ad586dddba3979cfa
TM-IHP: Consensus I AM...
OnInReceive-OnInvMessageReceived(PH):
OnInvMessageReceived(PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-811169209-1565309258: 0xfc24939bc65e9d8e0103d9614f9d399d236e67ddca6830cc3af2bc7558ca9292
      printingHashesFiltered(PH)-811169209-1565309258: 0xfc24939bc65e9d8e0103d9614f9d399d236e67ddca6830cc3af2bc7558ca9292
TM-ShallDrop: Droping message Neo.Network.P2P.TaskManager+NewTasks Consensus Neo.UInt256[]
TM-ShallDrop: Droping message 0xfc24939bc65e9d8e0103d9614f9d399d236e67ddca6830cc3af2bc7558ca9292

**Comment by vncoelho** [comment]
```cs
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-1881779158-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
      printingHashesFiltered(PH)-1881779158-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
TM-IHP: Consensus I AM...
      printingHashesFiltered(PH)-1488921154-1565309319: 0xc144f4eeb1e27890e1c047d77d76f5646990531f7f91fa1c597d9ce811d3b11d
TM-ShallDrop: Droping message Neo.Network.P2P.TaskManager+NewTasks Consensus Neo.UInt256[]
TM-ShallDrop: Droping message 0xc144f4eeb1e27890e1c047d77d76f5646990531f7f91fa1c597d9ce811d3b11d
OnInReceive-OnInvMessageReceived(PH):
OnInvMessageReceived(PH): hashes=0 sentByMe=False
OnInReceive-OnInvMessageReceived(PH):
OnInvMessageReceived(PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-2070483538-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
OnInReceive-OnInvMessageReceived(PH):
OnInvMessageReceived(PH): hashes=1 sentByMe=False
OnInvMessageReceived(PH):
      printingPayloadHashes(PH)-648271233-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
      printingHashesFiltered(PH)-648271233-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
TM-ShallDrop: Droping message Neo.Network.P2P.TaskManager+NewTasks Consensus Neo.UInt256[]
TM-ShallDrop: Droping message 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
      printingHashesFiltered(PH)-2070483538-1565309319: 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
TM-ShallDrop: Droping message Neo.Network.P2P.TaskManager+NewTasks Consensus Neo.UInt256[]
TM-ShallDrop: Droping message 0xb080a4fe6c2db5308ab63f8423a795bb30082e094f3938e4aad936522b05794d
```

In the log `printingPayloadHashes(PH)-1881779158-1565309319` the second number is a timestamp.

As can be seen all `OnInvMessageReceived` arrives at the same `ms` time in a localprivatenet.

The mechanism is working nice because it cuts from the queue of  `newtasks`.

@yongjiema, do you think that a similar PR could be done for `taskscompleted` or for the `OnInventoryReceived` of ProtocolHandler?

**Comment by vncoelho** [comment]
@yongjiema, I am confident that this will also be interesting for master3x.

**Pull request merged**
