### PR TITLE
Allow plugin to have dependencies

### PR DESCRIPTION
**Pull request by shargon**
Needed for https://github.com/neo-project/neo-modules/pull/160/files#diff-69f5bb07d501e021b374318421e22b7cR17

Related to https://github.com/neo-project/neo-node/pull/508

### CODE REVIEW

**Comment by erikzhang** [comment]
You don't need to load the dependencies. It will load them automatically if you put them in the right place.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/0f75741e2ec471235cba99b6ffc6b38b634dd47e/src/neo/Plugins/Plugin.cs#L43

https://github.com/neo-project/neo/blob/0f75741e2ec471235cba99b6ffc6b38b634dd47e/src/neo/Plugins/Plugin.cs#L83-L104

**Comment by shargon** [comment]
But then we need to to copy the dependencies outside the Plugin folder

**Comment by erikzhang** [comment]
@shargon Please review #1349

**Pull request closed without merging**
