### PR TITLE
Minnor plugin for stop loading on a defined height

### PR DESCRIPTION
**Pull request by vncoelho**
The same plugin of https://github.com/neo-project/neo-cli/pull/225

### CODE REVIEW

**Comment by erikzhang** [comment]
What is `ILoadingPlugin` for?

**Comment by vncoelho** [comment]
Do you think it would be better inside `IPolicyPlugin` or `IRpcPlugin`?
It could also be renamed to something like `IImportPlugin`.

But as I said, we need it the `neo-cli` `GetBlocks` function. Do you think that it is possible to load there?

**Comment by erikzhang** [comment]
What is the function implemented by this plugin?

**Comment by vncoelho** [comment]
We are doing a set of dockers from anyone to query the storage of any desired block height: https://github.com/NeoResearch/neo-tests/tree/master/history

This functions helps us to stop a RPC in a desired block height, a workaround that will probably work :dagger:

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/4280a5d7ac000bc94f5df5efde2f888aaac7a9c8/neo/Ledger/Blockchain.cs#L235-L246

You can use this method to implement your ImportPlugin.

**Comment by vncoelho** [comment]
Noooo, not good. It would be very easy... :dagger: 
Ehuaheauhuaea

Ok, @erikzhang, thanks.
This can a better position for that. 
Howeverrrrr, all the blocks will be inserted in the `blocks` object and we are going to  lose time with that =/.

I can handle that by creating small `chain.acc` objects.
On the other hand,  the other solution would stop directly there (on the loading). 
I do know how heavy it will be if `chain.acc` if big.
Do you think that it will impact on speed?

Imagine if:
* I have an image at block 2000000
* Someone asks the storage of 2010001
* thus, we need to load, exactly, 10001 blocks
* There are two cases now:
    * get a small `chain.acc` with something around 50000 blocks (from another image, the next one in our list)
   * or use a full `chain.acc` at the top of the chain.

**Comment by erikzhang** [comment]
`IEnumerable<T>` will lazy-load the blocks and you can stop it at any time. It won't load any block in `chain.acc` after you stop it.

**Comment by vncoelho** [comment]
I still need to test, @erikzhang.

Let me finish the plugin locally here first.
Do you want to suggest another class for the Plugin? Or should I keep this "crazy" `ILoadingPlugin` nomenclature?

**Comment by erikzhang** [comment]
In fact, I don't think it should be a plugin. Because it can only implement one function, it is to control how to import the block. Can we still use it to write a second plugin?

**Comment by vncoelho** [comment]
ahueahuehauea,

I do know,@erik, maybe someone could do another plugin related for some specific loading characteristic.
Otherwise, I think it that we could move it to the standard `IPolicyPlugin`.

**Comment by vncoelho** [comment]
Check it within the scope of `IPolicyPlugin`, Erik.
In fact, I did not like, because It will force everyone to updated their `config.json`.
What do you think?

**Comment by erikzhang** [comment]
I don't like it too. I am thinking about whether the functionality of import blocks should be moved to a plugin. This will support the import files in different formats.

**Comment by vncoelho** [comment]
That is it, @erikzhang.
That plugin solved this as well, I think that the `getblocks` there will make its task.

**Pull request closed without merging**
