### PR TITLE
[Neo CLI NEW] Part 1 of https://github.com/neo-project/neo/pull/3103

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

This is part one of pr https://github.com/neo-project/neo/pull/3103, this pr mainly focus on create the whole structure of new cli.

This pr does not introduce any real functonal logic, all of them are sort of tools and utils.

Fixes # https://github.com/neo-project/neo/pull/3103

## Type of change

- [ ] Optimization (the change is only an optimization)
- [ ] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Neo.Hosting.App.Tests

**Test Configuration**:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by cschuchardt88 — COMMENTED** [review]
Part `1` and Part `2` are the same code

**Comment by shargon** [comment]
> Part `1` and Part `2` are the same code

So only part 2 is needed?

**Comment by cschuchardt88** [comment]
ignore these these. start with #3372 and go up

**Comment by cschuchardt88** [comment]
@Jim8y thx for the help. But we don't need your PRs anymore.

**Comment by cschuchardt88** [comment]
No longer need this PR see #3372

**Pull request closed without merging**
