### PR TITLE
COVERALL: update to last version 2.3.0

### PR DESCRIPTION
**Pull request by vncoelho**
https://github.com/coverallsapp/github-action/releases

close https://github.com/neo-project/neo/issues/3251

### CODE REVIEW

**Review by Jim8y — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
Still not working

**Review by shargon — CHANGES_REQUESTED** [review]
maybe we need the old version, I think that this pr is not required, we need to solve the coverage issue first, after it, maybe this change is not required.

**Comment by vncoelho** [comment]
> maybe we need the old version, I think that this pr is not required, we need to solve the coverage issue first, after it, maybe this change is not required.

If you check the changelog you will see that the version will be update anyway.
It is a obvious change.

The current error is another thing.

**Comment by vncoelho** [comment]
> > maybe we need the old version, I think that this pr is not required, we need to solve the coverage issue first, after it, maybe this change is not required.
> 
> If you check the changelog you will see that the version will be updated anyway.
> It is an obvious change.
> 
> The current error is another thing.

**Comment by vncoelho** [comment]
I will reopen after the fix.

**Review by vncoelho — COMMENTED** [review]
@shargon, you can first merge on devpack and we can check the behavior. Then merge here.

**Comment by shargon** [comment]
Already updated with the format change, we need to know that it worked with the last version

**Comment by vncoelho** [comment]
> Already updated with the format change, we need to know that it worked with the last version

which format change? I did not understand.

**Comment by vncoelho** [comment]
Wait until https://github.com/neo-project/neo-devpack-dotnet/pull/1046 is merged and verified that it is running without problems.

**Comment by vncoelho** [comment]
@shargon 
Next time DO NOT CHANGE my pull request without permission, ok?
Commit [bbcb52d](https://github.com/neo-project/neo/pull/3252/commits/bbcb52d5c90f88b193f6ad7b0b2864edda2cca58) was masked with a name and you changed version. THIS IS A COMPLETE LACK OF RESPECT FROM YOUR SIDE.

You were better than this, @shargon . I do not know what is going on with you.

**Pull request closed without merging**
