### PR TITLE
[Neo Core] Ensure LevelDB Snapshot Only be Used by One Thread 

### PR DESCRIPTION
**Pull request by Jim8y**
# Description

Leveldb is not thread safe, thus we should be able to avoid leveldb being used cross threads.

Fixes # (issue)

## Type of change

- [ ] Optimization (the change is only an optimization)
- [x] Style (the change is only a code style for better maintenance or standard purpose)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] TestOneThreadLevelDbSnapshotPut
- [x] TestSingleExtraThreadLevelDbSnapshotPut
- [x] TestMultiThreadLevelDbSnapshotPut

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jim8y** [comment]
> Why are you trying to do this?

trying to avoid leveldb mis use.

**Review by shargon — COMMENTED** [review]
This was tested in a real environment?

**Comment by cschuchardt88** [comment]
> This was tested in a real environment?

This should be tests in real environment. Reason is the `blockchain` network (node) is multi-threaded. Each request runs on a different thread, because of `Akka.net`.

**Review by vncoelho — COMMENTED** [review]
Hi @Jim8y , maybe move to draft or this still should be reviewed?

**Comment by cschuchardt88** [comment]
This is way to much work needed. Plus it isn't correctly. #3414 fixes the problem.

**Comment by Jim8y** [comment]
close as fixed in another pr.

**Pull request closed without merging**
