### PR TITLE
Introducing Neo Blockchain Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Neo Blockchain Guru](https://gurubase.io/g/neo-blockchain) to Gurubase. Neo Blockchain Guru uses the data from this repo and data from the [docs](https://developers.neo.org/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Neo Blockchain Guru", which highlights that Neo Blockchain now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Neo Blockchain Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Is this a free service?

**Comment by kursataktas** [comment]
> Is this a free service?

Yes

**Review by vncoelho — CHANGES_REQUESTED** [review]
I do not think it is necessary

**Review by Jim8y — APPROVED** [review]

**Comment by lock9** [comment]
It doesn't work (not your fault @kursataktas). 

It won't work due to inconsistencies across SDKs, documentation and search/indexing issues.

Example:
Screenshot 2024-11-13 at 14 26 56


The code above works for Neo Legacy, and not N3. Unfortunately, there isn't any way to get the 'correct' documentation.

**Comment by kursataktas** [comment]
> It doesn't work (not your fault @kursataktas).
> 
> It won't work due to inconsistencies across SDKs, documentation and search/indexing issues.
> 
> Example output ('show me a smart contract example'): Screenshot 2024-11-13 at 14 26 56
> 
> The code above works for Neo Legacy, and not N3. Unfortunately, there isn't any way to get the 'correct' documentation.

I reviewed the data sources used for that question. It appears to rely on a relatively old blog post. Here are similar data sources indexed for Neo Blockchain. I can remove the outdated ones if you can guide me.

```
https://developers.neo.org/tutorials/2021/05/04/real-world-tokens
https://developers.neo.org/tutorials/2021/05/18/neo-go-workshop
https://developers.neo.org/tutorials/2021/05/27/getting-started-with-the-neo-blockchain-toolkit
https://developers.neo.org/tutorials/2021/05/27/simple-domain-registrar
https://developers.neo.org/tutorials/2021/06/26/dapp-wallet-integration-with-walletconnect
https://developers.neo.org/tutorials/2021/12/07/demo-of-n3-core-components
https://developers.neo.org/tutorials/2022/06/18/transfer-nft-with-props-sdk
https://developers.neo.org/tutorials/2022/10/17/transfer-neo-or-gas-with-neon-js
https://developers.neo.org/tutorials/2022/10/25/neons-as-a-public-key-server
https://developers.neo.org/tutorials/2022/10/30/neonjs-cheatsheet
https://developers.neo.org/tutorials/2023/07/05/neo3-boa-writing-a-fungible-token-contract-using-python
```

**Comment by cschuchardt88** [comment]
closing as not necessary.

**Pull request closed without merging**
