### PR TITLE
Add NotificationPlugin interface

### PR DESCRIPTION
**Pull request by localhuman**
This PR adds a `NotificationPlugin` interface for plugins that wish to persist events emitted from smart contracts, and provide a REST interface for applications that wish to query those events.

- `StartPersistingNotifications` would be called on any `NotificationPlugin` that is installed in the `plugins` directory.  This method creates a database and begins saving events to the database.

- `UserAgent` is an interface to instruct the NotificationPlugin what version of neo core is running when persisting events

- `StartRESTApi` would optionally be called on any `NotificationPlugin` interface in the event that the operator wishes to expose a REST interface for public consumption of notification events.

All feedback welcome!

### CODE REVIEW

**Comment by erikzhang** [comment]
When will this plugin be called?

**Comment by localhuman** [comment]
It would look something like this: 
https://github.com/localhuman/neo-cli/blob/feature/use-plugin-interface/neo-cli/Shell/MainService.cs#L1002

**Comment by erikzhang** [comment]
@localhuman Can you take a look at https://github.com/neo-project/neo-plugins/tree/master/ApplicationLogs?

**Comment by localhuman** [comment]
I have seen it.

**Comment by jsolman** [comment]
Can’t you just subscribe to blockchain BlockPersisted events instead of needing this?

**Comment by localhuman** [comment]
Yes.  But I do not want to serve the notifications via JSON-RPC, and would like to start a REST server for that.

**Comment by jsolman** [comment]
IMO, this is too specific of a type of plugin. Plugins should be for modifying behavior of the neo core or adding features to the RpcServer it exposes. For starting a completely separate REST server, why not do it from your project depending on the neo core. You can listen to BlockPersisted and then persist the notifications wherever you want and serve them up over your REST server that is started from your project depending on neo.dll.

Adding new plugin types to core for every type of additional server someone wants to build on top of Neo seems bloated.

**Comment by vncoelho** [comment]
I will close this PR due to lack of inactivity and also a better design for plugins that has been done in these last months.

As @jsolman emphasized, we may use the current templates for creating such plugin.

On the other hand, fell free to reopen it @localhuman if you believe that we still should move in this direction.

**Pull request closed without merging**
