### PR TITLE
Reduce blockchain space

### LINKED ISSUE #1962: Reduce blockchain size removing some verification scripts
**Summary or problem description**

We can reduce the blockchain size removing some `Blocks.VerificationScript` , when the verification script it's not present, it will be taken from the storage, so we can use this feature for reduce the blocks size. Also we can improve wallets in order to check if the verification script it's already stored.

**Do you have any solution you want to propose?**
#1963

**Neo Version**
- Neo 3

### PR DESCRIPTION
**Pull request by shargon**
Close #1962

It is a different version that cannot damage the light nodes.

### CODE REVIEW

**Comment by erikzhang** [comment]
This looks like a compression technique.

**Comment by shargon** [comment]
It's a piece of data that "almost always" will be the same

**Comment by shargon** [comment]
> This looks like a compression technique.

Yes, it is

**Comment by shargon** [comment]
Obsolete but I still think that it's useful, if we decide to implement it, I can create a new PR.

**Pull request closed without merging**
