### PR TITLE
LevelDB changes

### PR DESCRIPTION
**Pull request by shargon**
LevelDB changes of https://github.com/neo-project/neo/pull/1063

### CODE REVIEW

**Comment by erikzhang** [comment]
The leveldb will be moved to plugin soon. Why do we modify it now?

**Comment by shargon** [comment]
It will use a nuget package or it will copy this source?

**Comment by vncoelho** [comment]
Lets modify it when moved.

**Comment by erikzhang** [comment]
I will move it when https://github.com/neo-project/neo-plugins/pull/147 is merged.

**Comment by shargon** [comment]
then i will close it, we can improve it later

**Pull request closed without merging**
