### PR TITLE
Allow Log in Safe methods

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/2782

### CODE REVIEW

**Comment by erikzhang** [comment]
> From a purist POV safe methods are supposed to be free of any side-effects and logging is a side-effect.

I agree.

**Comment by shargon** [comment]
Log's side-effects depend on the plugin that uses it, because the core itself doesn't do it, so it's safe, until it stops being safe for a third party, which would be the third party's problem, I understand what you're saying but the the problem with not changing it is making error handling in `Safe` methods unusable.

Any alternative?

**Comment by erikzhang** [comment]
> Any alternative?

`throw`.

**Comment by shargon** [comment]
But `Throw` it's catcheable, different than `Assert`

**Comment by erikzhang** [comment]
> But Throw it's catcheable, different than Assert

`Safe` method has no side effects, so it doesn't matter if it is caught, right?

**Comment by shargon** [comment]
> > But Throw it's catcheable, different than Assert
> 
> `Safe` method has no side effects, so it doesn't matter if it is caught, right?

It matter because the developer expect to end the execution, so undesired results may happen

**Comment by erikzhang** [comment]
> It matter because the developer expect to end the execution, so undesired results may happen

It's a safe method. It doesn't matter if the execution is ended or not.

**Pull request closed without merging**
