### PR TITLE
Fix SpentCoinState.Clone

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1368

### CODE REVIEW

**Comment by shargon** [comment]
@superboyiii could you test this?

**Comment by cloud8little** [comment]
> @superboyiii could you test this?

@shargon is there any user scenario for this?

**Comment by shargon** [comment]
The UT ensure that both object can be changed without change the content of the other, I think that we need a backward compatibility test.

**Comment by superboyiii** [comment]
@shargon  @nicolegys is focusing on test of this PR, something still needs deep investigation. She will give you final result as soon as possible.

**Comment by nicolegys** [comment]
TestResults:
Mainnet: compatible with 2.10.3
Testnet: 7 files different with 2.10.3/master2.x

[Differences_pr1369.zip](https://github.com/neo-project/neo/files/4029853/Differences_pr1369.zip)

It is strange that this pr is compatible with pr 1376 both on mainnet and testnet.

**Comment by nicolegys** [comment]
I found out what the problem was.
My 2.10.3 testnet node didn't install RpcNep5Tracker plugin, but pr1369/pr1376 testnet node installed  RpcNep5Tracker.
I have tried several times, found out that the storage files of testnet were different when with and without RpcNep5Tracker. It's the issue of RpcNep5Tracker.
I'll sync two mainnet nodes to make sure whether the same problem exists.

**Comment by shargon** [comment]
Thanks @nicolegys we can wait, no problem :)

**Comment by nicolegys** [comment]
@shargon Thank you for your patience in waiting for the result.
The phenomenon didn't appear on mainnet.
Anyway, this is another issue. For me, the Compatibility test of pr1369/pr1376 have passed.

**Comment by superboyiii** [comment]
@shargon This PR is able to merge, but seems gitcheck is bogging down.

**Comment by shargon** [comment]
I think that neo2 is with travis and was down, @erikzhang could you help us for merge this?

**Pull request merged**
