### PR TITLE
Add StrictUTF8

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by roman-khimov** [comment]
I guess that's the required minimum, at least making the behavior more predictable. Not sure it covers all use cases for this API though, but you obviously have more experience with that.

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai Need test.

**Comment by cloud8little** [comment]
> @neo-project/ngd-shanghai Need test.

Got it, I will test.

**Comment by cloud8little** [comment]
engine execute faulted for this method:
07f006856116f79cd489a244a3a04d2

```cs
        public static string testbytearray2(byte[] a)
        {
            Map<string, string> some = new Map<string, string>();
            some[a.AsString()] = "teststring2";
            return Json.Serialize(some);
        }
```

Debug information:
3e71c249b1eca4f0688486762142e8a


while work well for this(only AsString() return):
48c1601dab93d6791ec4eade1790694

```cs
        public static string testasstring(byte[] a)
        {
            return a.AsString();
        }
```

**Comment by erikzhang** [comment]
I need the StackTrace of the exception.

**Comment by erikzhang** [comment]
I tested locally, and it works good. Maybe there's a problem in the console.

**Comment by erikzhang** [comment]
@cloud8little StackTrace?

**Comment by erikzhang** [comment]
@cloud8little I got it. It is because the max key of a `Map` is `64`, and the size of "おはようございます。こんにちは。こ んばんは。" is `65`. It's not a bug.

https://github.com/neo-project/neo-vm/blob/c979cabf476dbaf85b9e4e06821fa5080c8a9de4/src/neo-vm/Types/Map.cs#L11

**Comment by cloud8little** [comment]
> @cloud8little I got it. It is because the max key of a `Map` is `64`, and the size of "おはようございます。こんにちは。こ んばんは。" is `65`. It's not a bug.
> 
> https://github.com/neo-project/neo-vm/blob/c979cabf476dbaf85b9e4e06821fa5080c8a9de4/src/neo-vm/Types/Map.cs#L11

@erikzhang You're right, retest with this contract, and test length=64 ordinary string and length=65 ordinary string:
```cs
        public static string testunicodekeyvalue(string s)
        {
            Map<string, string> some = new Map<string, string>();
            some[s] = s;
            return Json.Serialize(some);
        }
```
```
neo> invoke 0x435477f77449cabbfd6444ff4a08aea235828369 testunicodekeyvalue [{"type":"String","value":"eyIweDhlODBhZDhmOGVlNDdiZTE4ZTU5YmJkZTdkMzBhNTU0MmFjNDYyYjYiOiJN"}]
Invoking script with: '0c40657949776544686c4f4442685a44686d4f47566c4e4464695a5445345a545535596d4a6b5a54646b4d7a42684e5455304d6d466a4e445979596a59694f694a4e11c00c1374657374756e69636f64656b657976616c75650c1469838235a2ae084aff4464fdbbca4974f777544341627d5b52'
VM State: HALT
Gas Consumed: 0.0137899
Result Stack: [{"type":"ByteString","value":"eyJleUl3ZURobE9EQmhaRGhtT0dWbE5EZGlaVEU0WlRVNVltSmtaVGRrTXpCaE5UVTBNbUZqTkRZeVlqWWlPaUpOIjoiWlhsSmQyVkVhR3hQUkVKb1drUm9iVTlIVm14T1JHUnBXbFJGTkZwVVZUVlpiVXByV2xSa2EwMTZRbWhPVkZVd1RXMUdhazVFV1hsWmFsbHBUMmxLVGc9PSJ9"}]
Relay tx(no|yes): no
neo> invoke 0x435477f77449cabbfd6444ff4a08aea235828369 testunicodekeyvalue [{"type":"String","value":"eyIweDhlODBhZDhmOGVlNDdiZTE4ZTU5YmJkZTdkMzBhNTU0MmFjNDYyYjYiOiJN9"}]
Invoking script with: '0c41657949776544686c4f4442685a44686d4f47566c4e4464695a5445345a545535596d4a6b5a54646b4d7a42684e5455304d6d466a4e445979596a59694f694a4e3911c00c1374657374756e69636f64656b657976616c75650c1469838235a2ae084aff4464fdbbca4974f777544341627d5b52'
VM State: FAULT
Gas Consumed: 0.0127881
Result Stack: []
Engine faulted.
Error: insufficient balance.
```

**Comment by Tommo-L** [comment]
```cs
public static string testbytearray2(byte[] a)
 {
            Map<string, string> some = new Map<string, string>();
            some[a.AsString()] = "teststring2";
            return Json.Serialize(some);
}
// execute faulted
```
It's a compiler bug, plz see https://github.com/neo-project/neo-devpack-dotnet/issues/297

**Comment by cloud8little** [comment]
> I need the StackTrace of the exception.

@ShawnYun  found that it is because AsString for byte[] actually does not convert to ByteString, but Buffer type. compiler need to take care of it. 

> ```cs
> public static string testbytearray2(byte[] a)
>  {
>             Map<string, string> some = new Map<string, string>();
>             some[a.AsString()] = "teststring2";
>             return Json.Serialize(some);
> }
> // execute faulted
> ```
> 
> @cloud8little It's a compiler bug, plz see [neo-project/neo-devpack-dotnet#297](https://github.com/neo-project/neo-devpack-dotnet/issues/297)

@erikzhang ALL other tests passed, good to merge.

**Pull request merged**
