### PR TITLE
Optimize NextConsensus

### LINKED ISSUE #2014: Consensus fail after updating validators
**Describe the bug**

**To Reproduce**
1. Start a CN and normal node.
2. Register all standby committee as candidate and the original validator as candidate too.
3. Register another account test1.json as candidate and vote him with 20000000 votes.
4. After generating another two blocks. consensus node show error.

**Expected behavior**
It should not show error but show role=WatchOnly.

**Screenshots**
34e49aefb476ff7b83f77f7bd52ee27

**Platform:**
 - OS: Windows 10 x64
 - Version master branch, Neo-VM 

Root Cause Analysis:

```cs

        public void Reset(byte viewNumber)
        {
            if (viewNumber == 0)
            {
                Snapshot?.Dispose();
                Snapshot = Blockchain.Singleton.GetSnapshot();
                Block = new Block
                {
                    PrevHash = Snapshot.CurrentBlockHash,
                    Index = Snapshot.Height + 1,
                    NextConsensus = Blockchain.GetConsensusAddress(NativeContract.NEO.ComputeNextBlockValidators(Snapshot))
                };
                var pv = Validators;
                Validators = NativeContract.NEO.GetNextBlockValidators(Snapshot);
                if (_witnessSize == 0 || (pv != null && pv.Length != Validators.Length))
                {
```

It was caused by ComputeNextBlockValidators get the new update key, GetNextBlockValidators still get the original validators.

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #2014

### CODE REVIEW

**Comment by cloud8little** [comment]
Test passed with #1848 . In block 10, voter vote to a new account with 2000,0000 votes, the validator update for consensus in block 13.
779da6ca270c0be95528ddf86952d56

and open the new account start consensus success.

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
Where is it used?

**Comment by Tommo-L** [comment]
The value of `NextConseus` is incorrent.
https://github.com/neo-project/neo/blob/6fc4161258408cae3d754cab784dcee2235b63ef/src/neo/Consensus/ConsensusContext.cs#L380

**Comment by erikzhang** [comment]
Can you move this logic to `ConsensusContext`? Or just use `GetNextBlockValidators()`.

**Comment by Qiao-Jin** [comment]
> Can you move this logic to `ConsensusContext`? Or just use `GetNextBlockValidators()`.

Have moved logic to `ConsensusContext`

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
Tested?

**Comment by cloud8little** [comment]
Testing

**Comment by cloud8little** [comment]
> Testing

Test Passed. Good to merge.

**Pull request merged**
