### PR TITLE
Make StorageIterator public

### PR DESCRIPTION
**Pull request by hal0x2328**
I'm writing a plugin to extend the RPC service on my nodes with a `findstorage` method to allow direct RPC queries in order to enumerate a smart contract's storage by key prefix, with pagination to better deal with queries that may contain hundreds or thousands of results, instead of passing them through the extra overhead of the VM and unnecessarily complicating the smart contract code. 

In order to do this in a plugin, first I need access to the `StorageIterator` class and the ability to use it as an enumerator in a `foreach` loop. This pull request addresses that need.

### CODE REVIEW

**Comment by erikzhang** [comment]
Can I view the plugin's code?

**Comment by hal0x2328** [comment]
Here is the plugin source: https://github.com/hal0x2328/RpcFindStorage

Any suggestions to make it more efficient are appreciated - I don't really like copying the whole result into a list and then using `Skip`/`Take` but I was unable to make it work on the enumerator itself.

**Comment by erikzhang** [comment]
@hal0x2328 In fact, your plugin does not need this modification. I made a pr please check it out.
https://github.com/hal0x2328/RpcFindStorage/pull/1

**Comment by hal0x2328** [comment]
Very cool, thanks for the assist!

**Pull request closed without merging**
